[package]
name = "scp-rust-client"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
scp-core = { path = "../../crates/scp-core", features = ["testing"] }
scp-did = { path = "../../crates/scp-did" }
scp-identity = { path = "../../crates/scp-identity" }
scp-platform = { path = "../../crates/scp-platform", features = ["testing"] }
tokio = { version = "1", features = ["full"] }

[workspace]
