//! Input validation for the FFI bridge boundary.
//!
//! All public `#[pyfunction]` bridge functions validate string inputs before
//! passing them to scp-core. This module provides the shared validation
//! functions used across the bridge layer.
//!
//! # Design rationale
//!
//! Defense-in-depth: these validators catch malformed input at the Python
//! boundary with clear, actionable error messages rather than allowing
//! invalid data to propagate into Rust internals where failures are harder
//! to diagnose.
//!
//! All validators are O(n) string scans with no allocations on the happy
//! path. They return `Result<(), ScpPyError::ValidationError>` so callers
//! can use the `?` operator.
//!
//! See GitHub issue #104 and ADR-013 §3-§7 (bridge function signatures).

use crate::error::ScpPyError;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Maximum length for a context ID (64 hex chars = 32 bytes).
pub const MAX_CONTEXT_ID_LEN: usize = 256;

/// Maximum length for a DID string. did:dht DIDs are typically ~60 chars;
/// allow generous headroom for other methods.
pub const MAX_DID_LEN: usize = 512;

/// Maximum length for a tool name.
pub const MAX_TOOL_NAME_LEN: usize = 256;

/// Maximum length for a tool ID (spec §5.4.1).
pub const MAX_TOOL_ID_LEN: usize = 128;

/// Maximum length for a capability URI string.
pub const MAX_CAPABILITY_URI_LEN: usize = 1024;

/// Maximum length for a UCAN token string (JWT format). UCAN tokens with
/// deep delegation chains can be large; 64 KiB is a generous upper bound.
pub const MAX_UCAN_TOKEN_LEN: usize = 65_536;

/// Maximum length for an MCP handle ID.
pub const MAX_MCP_HANDLE_LEN: usize = 256;

/// Maximum length for a relay URL.
pub const MAX_RELAY_URL_LEN: usize = 2048;

/// Maximum length for a transport mode string.
pub const MAX_TRANSPORT_MODE_LEN: usize = 64;

// ---------------------------------------------------------------------------
// String emptiness and length
// ---------------------------------------------------------------------------

/// Validates that a string is non-empty and within the given length limit.
fn validate_non_empty(value: &str, field_name: &str, max_len: usize) -> Result<(), ScpPyError> {
    if value.is_empty() {
        return Err(ScpPyError::validation(format!(
            "{field_name} must not be empty"
        )));
    }
    if value.len() > max_len {
        return Err(ScpPyError::validation(format!(
            "{field_name} exceeds maximum length ({} > {max_len} bytes)",
            value.len()
        )));
    }
    Ok(())
}

/// Validates that a string contains no control characters (U+0000..U+001F,
/// U+007F..U+009F). Control characters in identifiers can cause log injection,
/// display confusion, and format string issues.
fn reject_control_chars(value: &str, field_name: &str) -> Result<(), ScpPyError> {
    if let Some(pos) = value.chars().position(char::is_control) {
        return Err(ScpPyError::validation(format!(
            "{field_name} contains control character at position {pos}"
        )));
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Context ID validation
// ---------------------------------------------------------------------------

/// Validates a context ID string.
///
/// Context IDs are 64-character hex strings (32 bytes, per §18.4.1) when
/// generated by scp-core, but the bridge also accepts shorter IDs for
/// testing. Validation enforces:
/// - Non-empty
/// - Length <= [`MAX_CONTEXT_ID_LEN`]
/// - Alphanumeric + hyphens only (hex chars plus test IDs with hyphens)
/// - No control characters
///
/// # Errors
///
/// Returns [`ScpPyError::ValidationError`] if the context ID is empty,
/// too long, contains control characters, or contains invalid characters.
pub fn validate_context_id(context_id: &str) -> Result<(), ScpPyError> {
    validate_non_empty(context_id, "context_id", MAX_CONTEXT_ID_LEN)?;
    reject_control_chars(context_id, "context_id")?;

    if !context_id
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
    {
        return Err(ScpPyError::validation(format!(
            "context_id contains invalid characters: expected alphanumeric, \
             hyphens, or underscores, got {context_id:?}"
        )));
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// DID string validation
// ---------------------------------------------------------------------------

/// Validates a DID string.
///
/// DIDs must match the `did:{method}:{id}` format per the W3C DID Core
/// specification. Validation enforces:
/// - Non-empty
/// - Length <= [`MAX_DID_LEN`]
/// - Starts with `did:`
/// - Contains at least two `:` separators (method + id)
/// - No control characters
///
/// # Errors
///
/// Returns [`ScpPyError::ValidationError`] if the DID is empty, too long,
/// missing the `did:` prefix, missing the method or ID, or contains
/// control characters.
pub fn validate_did(did: &str) -> Result<(), ScpPyError> {
    validate_non_empty(did, "DID", MAX_DID_LEN)?;
    reject_control_chars(did, "DID")?;

    if !did.starts_with("did:") {
        return Err(ScpPyError::validation(format!(
            "DID must start with 'did:', got {did:?}"
        )));
    }

    // Must have at least `did:method:id` (two colons).
    let rest = &did[4..];
    if !rest.contains(':') {
        return Err(ScpPyError::validation(format!(
            "DID must match 'did:{{method}}:{{id}}' format, got {did:?}"
        )));
    }

    // Method must be non-empty and lowercase alphanumeric.
    let method = rest.split(':').next().unwrap_or("");
    if method.is_empty()
        || !method
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit())
    {
        return Err(ScpPyError::validation(format!(
            "DID method must be non-empty lowercase alphanumeric, got {method:?} in {did:?}"
        )));
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Tool name / ID validation
// ---------------------------------------------------------------------------

/// Validates a tool name string.
///
/// Tool names are human-readable identifiers used in tool registration.
/// Validation enforces:
/// - Non-empty
/// - Length <= [`MAX_TOOL_NAME_LEN`]
/// - No control characters
/// - No characters that could cause issues in format strings (`{`, `}`)
///
/// # Errors
///
/// Returns [`ScpPyError::ValidationError`] if the tool name is empty,
/// too long, contains control characters, or contains format string
/// characters.
pub fn validate_tool_name(name: &str) -> Result<(), ScpPyError> {
    validate_non_empty(name, "tool name", MAX_TOOL_NAME_LEN)?;
    reject_control_chars(name, "tool name")?;

    if name.contains('{') || name.contains('}') {
        return Err(ScpPyError::validation(format!(
            "tool name must not contain '{{' or '}}' (format string risk), got {name:?}"
        )));
    }

    Ok(())
}

/// Validates a tool ID string.
///
/// Tool IDs are derived from tool names (e.g., `tool-my-tool`). Per spec
/// §5.4.1, tool IDs must contain only lowercase alphanumeric characters,
/// hyphens, and underscores (`[a-z0-9_-]`). Validation enforces:
/// - Non-empty
/// - Length <= [`MAX_TOOL_ID_LEN`] (128 chars per §5.4.1)
/// - Characters restricted to `[a-z0-9_-]`
/// - No control characters
///
/// # Errors
///
/// Returns [`ScpPyError::ValidationError`] if the tool ID is empty,
/// too long, contains control characters, or contains characters outside
/// the `[a-z0-9_-]` class.
pub fn validate_tool_id(tool_id: &str) -> Result<(), ScpPyError> {
    validate_non_empty(tool_id, "tool_id", MAX_TOOL_ID_LEN)?;
    reject_control_chars(tool_id, "tool_id")?;

    if !tool_id
        .chars()
        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-' || c == '_')
    {
        return Err(ScpPyError::validation(format!(
            "tool_id contains invalid characters: expected [a-z0-9_-], got {tool_id:?}"
        )));
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Capability URI validation
// ---------------------------------------------------------------------------

/// Validates a capability URI string.
///
/// Capability URIs follow one of these patterns:
/// - `scp:ctx:{context_id}/{action}` — context-scoped capability
/// - Bare capability (e.g., `messages:write`) — resolved against context
///
/// Validation enforces:
/// - Non-empty
/// - Length <= [`MAX_CAPABILITY_URI_LEN`]
/// - No control characters
///
/// # Errors
///
/// Returns [`ScpPyError::ValidationError`] if the capability URI is empty,
/// too long, or contains control characters.
pub fn validate_capability_uri(uri: &str) -> Result<(), ScpPyError> {
    validate_non_empty(uri, "capability URI", MAX_CAPABILITY_URI_LEN)?;
    reject_control_chars(uri, "capability URI")?;
    Ok(())
}

// ---------------------------------------------------------------------------
// UCAN token validation
// ---------------------------------------------------------------------------

/// Validates a UCAN token string (JWT format) at the boundary.
///
/// This is a lightweight structural check — full JWT validation is handled
/// by scp-core's `parse_ucan`. The boundary check enforces:
/// - Non-empty
/// - Length <= [`MAX_UCAN_TOKEN_LEN`]
/// - No control characters other than those in the base64url alphabet
///
/// # Errors
///
/// Returns [`ScpPyError::ValidationError`] if the token is empty, too long,
/// or contains control characters.
pub fn validate_ucan_token(token: &str) -> Result<(), ScpPyError> {
    validate_non_empty(token, "UCAN token", MAX_UCAN_TOKEN_LEN)?;

    // JWT tokens should not contain newlines or other control chars
    // (base64url alphabet is [A-Za-z0-9_.-]).
    if token.chars().any(char::is_control) {
        return Err(ScpPyError::validation(
            "UCAN token contains control characters",
        ));
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// MCP handle validation
// ---------------------------------------------------------------------------

/// Validates an MCP server or client handle string.
///
/// Handles are opaque hex IDs generated by the bridge (e.g.,
/// `mcp-server-{hex}`). Validation enforces:
/// - Non-empty
/// - Length <= [`MAX_MCP_HANDLE_LEN`]
/// - No control characters
///
/// # Errors
///
/// Returns [`ScpPyError::ValidationError`] if the handle is empty, too
/// long, or contains control characters.
pub fn validate_mcp_handle(handle: &str) -> Result<(), ScpPyError> {
    validate_non_empty(handle, "MCP handle", MAX_MCP_HANDLE_LEN)?;
    reject_control_chars(handle, "MCP handle")?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Relay URL validation
// ---------------------------------------------------------------------------

/// Validates a relay URL string.
///
/// Relay URLs must be valid WebSocket or HTTP URLs. Validation enforces:
/// - Non-empty
/// - Length <= [`MAX_RELAY_URL_LEN`]
/// - No control characters (CRLF injection defense)
/// - Starts with a recognized scheme (`ws://`, `wss://`, `http://`, `https://`)
///
/// # Errors
///
/// Returns [`ScpPyError::ValidationError`] if the URL is empty, too long,
/// contains control characters, or does not start with a valid scheme.
pub fn validate_relay_url(url: &str) -> Result<(), ScpPyError> {
    validate_non_empty(url, "relay URL", MAX_RELAY_URL_LEN)?;
    reject_control_chars(url, "relay URL")?;

    let valid_scheme = url.starts_with("ws://")
        || url.starts_with("wss://")
        || url.starts_with("http://")
        || url.starts_with("https://");

    if !valid_scheme {
        return Err(ScpPyError::validation(format!(
            "relay URL must start with ws://, wss://, http://, or https://, got {url:?}"
        )));
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Transport mode validation
// ---------------------------------------------------------------------------

/// Validates a transport mode string.
///
/// Accepted values: `"stdio"`, `"sse"`.
///
/// # Errors
///
/// Returns [`ScpPyError::ValidationError`] if the mode is empty or not one
/// of the accepted values.
pub fn validate_transport_mode(mode: &str) -> Result<(), ScpPyError> {
    validate_non_empty(mode, "transport mode", MAX_TRANSPORT_MODE_LEN)?;

    match mode {
        "stdio" | "sse" => Ok(()),
        _ => Err(ScpPyError::validation(format!(
            "transport must be 'stdio' or 'sse', got {mode:?}"
        ))),
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    // -- Context ID --

    #[test]
    fn valid_hex_context_id() {
        let hex_id = "a".repeat(64);
        assert!(validate_context_id(&hex_id).is_ok());
    }

    #[test]
    fn valid_test_context_id_with_hyphens() {
        assert!(validate_context_id("ctx-test-123").is_ok());
    }

    #[test]
    fn empty_context_id_rejected() {
        let err = validate_context_id("").unwrap_err();
        assert!(err.to_string().contains("must not be empty"));
    }

    #[test]
    fn context_id_with_control_chars_rejected() {
        let err = validate_context_id("abc\0def").unwrap_err();
        assert!(err.to_string().contains("control character"));
    }

    #[test]
    fn context_id_with_special_chars_rejected() {
        let err = validate_context_id("abc/def").unwrap_err();
        assert!(err.to_string().contains("invalid characters"));
    }

    #[test]
    fn context_id_too_long_rejected() {
        let long_id = "a".repeat(MAX_CONTEXT_ID_LEN + 1);
        let err = validate_context_id(&long_id).unwrap_err();
        assert!(err.to_string().contains("exceeds maximum length"));
    }

    // -- DID --

    #[test]
    fn valid_did_dht() {
        assert!(validate_did("did:dht:z6Mkabcdef").is_ok());
    }

    #[test]
    fn valid_did_key() {
        assert!(validate_did("did:key:z6Mkabcdef").is_ok());
    }

    #[test]
    fn empty_did_rejected() {
        let err = validate_did("").unwrap_err();
        assert!(err.to_string().contains("must not be empty"));
    }

    #[test]
    fn did_without_prefix_rejected() {
        let err = validate_did("not-a-did").unwrap_err();
        assert!(err.to_string().contains("must start with 'did:'"));
    }

    #[test]
    fn did_without_id_rejected() {
        let err = validate_did("did:dht").unwrap_err();
        assert!(err.to_string().contains("did:{method}:{id}"));
    }

    #[test]
    fn did_with_empty_method_rejected() {
        let err = validate_did("did::something").unwrap_err();
        assert!(err.to_string().contains("method must be non-empty"));
    }

    #[test]
    fn did_with_uppercase_method_rejected() {
        let err = validate_did("did:DHT:z6Mk").unwrap_err();
        assert!(err.to_string().contains("lowercase alphanumeric"));
    }

    #[test]
    fn did_too_long_rejected() {
        let long_did = format!("did:dht:{}", "a".repeat(MAX_DID_LEN));
        let err = validate_did(&long_did).unwrap_err();
        assert!(err.to_string().contains("exceeds maximum length"));
    }

    #[test]
    fn did_with_control_chars_rejected() {
        let err = validate_did("did:dht:\nz6Mk").unwrap_err();
        assert!(err.to_string().contains("control character"));
    }

    // -- Tool name --

    #[test]
    fn valid_tool_name() {
        assert!(validate_tool_name("my-tool").is_ok());
    }

    #[test]
    fn empty_tool_name_rejected() {
        let err = validate_tool_name("").unwrap_err();
        assert!(err.to_string().contains("must not be empty"));
    }

    #[test]
    fn tool_name_with_braces_rejected() {
        let err = validate_tool_name("tool-{name}").unwrap_err();
        assert!(err.to_string().contains("format string risk"));
    }

    #[test]
    fn tool_name_too_long_rejected() {
        let long_name = "a".repeat(MAX_TOOL_NAME_LEN + 1);
        let err = validate_tool_name(&long_name).unwrap_err();
        assert!(err.to_string().contains("exceeds maximum length"));
    }

    // -- Tool ID --

    #[test]
    fn valid_tool_id() {
        assert!(validate_tool_id("tool-my-tool").is_ok());
    }

    #[test]
    fn valid_tool_id_with_underscores_and_digits() {
        assert!(validate_tool_id("my_tool_42").is_ok());
    }

    #[test]
    fn empty_tool_id_rejected() {
        let err = validate_tool_id("").unwrap_err();
        assert!(err.to_string().contains("must not be empty"));
    }

    #[test]
    fn tool_id_with_uppercase_rejected() {
        let err = validate_tool_id("Tool-My-Tool").unwrap_err();
        assert!(err.to_string().contains("invalid characters"));
        assert!(err.to_string().contains("[a-z0-9_-]"));
    }

    #[test]
    fn tool_id_with_spaces_rejected() {
        let err = validate_tool_id("tool my tool").unwrap_err();
        assert!(err.to_string().contains("invalid characters"));
    }

    #[test]
    fn tool_id_with_special_chars_rejected() {
        let err = validate_tool_id("tool/my.tool").unwrap_err();
        assert!(err.to_string().contains("invalid characters"));
    }

    #[test]
    fn tool_id_too_long_rejected() {
        let long_id = "a".repeat(MAX_TOOL_ID_LEN + 1);
        let err = validate_tool_id(&long_id).unwrap_err();
        assert!(err.to_string().contains("exceeds maximum length"));
    }

    #[test]
    fn tool_id_at_max_length_accepted() {
        let id = "a".repeat(MAX_TOOL_ID_LEN);
        assert!(validate_tool_id(&id).is_ok());
    }

    // -- Capability URI --

    #[test]
    fn valid_scoped_capability_uri() {
        assert!(validate_capability_uri("scp:ctx:abc123/messages:write").is_ok());
    }

    #[test]
    fn valid_bare_capability() {
        assert!(validate_capability_uri("messages:write").is_ok());
    }

    #[test]
    fn empty_capability_uri_rejected() {
        let err = validate_capability_uri("").unwrap_err();
        assert!(err.to_string().contains("must not be empty"));
    }

    // -- UCAN token --

    #[test]
    fn valid_ucan_token() {
        assert!(
            validate_ucan_token("eyJhbGciOiJFZERTQSJ9.eyJpc3MiOiJkaWQ6ZGh0Ono2TWsifQ.sig").is_ok()
        );
    }

    #[test]
    fn empty_ucan_token_rejected() {
        let err = validate_ucan_token("").unwrap_err();
        assert!(err.to_string().contains("must not be empty"));
    }

    #[test]
    fn ucan_token_with_newlines_rejected() {
        let err = validate_ucan_token("token\ninjection").unwrap_err();
        assert!(err.to_string().contains("control characters"));
    }

    #[test]
    fn ucan_token_too_long_rejected() {
        let long_token = "a".repeat(MAX_UCAN_TOKEN_LEN + 1);
        let err = validate_ucan_token(&long_token).unwrap_err();
        assert!(err.to_string().contains("exceeds maximum length"));
    }

    // -- MCP handle --

    #[test]
    fn valid_mcp_handle() {
        assert!(validate_mcp_handle("mcp-server-a1b2c3d4").is_ok());
    }

    #[test]
    fn empty_mcp_handle_rejected() {
        let err = validate_mcp_handle("").unwrap_err();
        assert!(err.to_string().contains("must not be empty"));
    }

    // -- Relay URL --

    #[test]
    fn valid_ws_relay_url() {
        assert!(validate_relay_url("ws://127.0.0.1:9000/scp/v1").is_ok());
    }

    #[test]
    fn valid_wss_relay_url() {
        assert!(validate_relay_url("wss://relay.example.com/scp/v1").is_ok());
    }

    #[test]
    fn valid_http_relay_url() {
        assert!(validate_relay_url("http://localhost:8080").is_ok());
    }

    #[test]
    fn empty_relay_url_rejected() {
        let err = validate_relay_url("").unwrap_err();
        assert!(err.to_string().contains("must not be empty"));
    }

    #[test]
    fn relay_url_with_invalid_scheme_rejected() {
        let err = validate_relay_url("ftp://relay.example.com").unwrap_err();
        assert!(err.to_string().contains("must start with"));
    }

    #[test]
    fn relay_url_with_crlf_rejected() {
        let err = validate_relay_url("ws://relay.example.com\r\nHost: evil.com").unwrap_err();
        assert!(err.to_string().contains("control character"));
    }

    #[test]
    fn relay_url_too_long_rejected() {
        let long_url = format!("ws://{}", "a".repeat(MAX_RELAY_URL_LEN));
        let err = validate_relay_url(&long_url).unwrap_err();
        assert!(err.to_string().contains("exceeds maximum length"));
    }

    // -- Transport mode --

    #[test]
    fn valid_transport_modes() {
        assert!(validate_transport_mode("stdio").is_ok());
        assert!(validate_transport_mode("sse").is_ok());
    }

    #[test]
    fn invalid_transport_mode_rejected() {
        let err = validate_transport_mode("grpc").unwrap_err();
        assert!(err.to_string().contains("'stdio' or 'sse'"));
    }

    #[test]
    fn empty_transport_mode_rejected() {
        let err = validate_transport_mode("").unwrap_err();
        assert!(err.to_string().contains("must not be empty"));
    }
}
