import Foundation

// BridgeRegistrationResult and ShadowIdentityResult are now generated by
// UniFFI in ScpBindings.swift. The SDK structs have been removed to avoid
// duplicate type definitions.

// MARK: - BridgeConnectorBridge

/// Namespace for UniFFI bridge function references used by bridge connector
/// operations. Each typealias maps 1:1 to a UniFFI-generated function.
/// Closures are injected for testability; defaults call through to
/// ScpBindings.
///
/// See spec section 12 (Bridge System) and ADR-023.
public enum BridgeConnectorBridge {
    /// Evaluate trust level for a bridge action.
    public typealias EvaluateTrustFn = @Sendable (
        _ isBridged: Bool,
        _ isNativeTransport: Bool,
        _ shadowStatus: String
    ) throws -> UInt8

    /// Register a bridge connector with a context.
    public typealias RegisterFn = @Sendable (
        _ contextId: String,
        _ operatorDid: String,
        _ governanceDid: String,
        _ platform: String,
        _ mode: String
    ) throws -> BridgeRegistrationResult

    /// Create a shadow identity for an external platform participant.
    public typealias CreateShadowFn = @Sendable (
        _ bridgeId: String,
        _ platformHandle: String,
        _ bridgeMode: String,
        _ contextId: String
    ) throws -> ShadowIdentityResult

    /// Default evaluate trust function — delegates to UniFFI
    /// ``bridgeEvaluateTrust``.
    public static let defaultEvaluateTrust: EvaluateTrustFn = { isBridged, isNativeTransport, shadowStatus in
        try bridgeEvaluateTrust(
            isBridged: isBridged,
            isNativeTransport: isNativeTransport,
            shadowStatus: shadowStatus
        )
    }

    /// Default register function — delegates to UniFFI
    /// ``bridgeRegister(contextId:operatorDid:governanceDid:platform:mode:)``.
    public static let defaultRegister: RegisterFn = { contextId, operatorDid, governanceDid, platform, mode in
        try bridgeRegister(
            contextId: contextId,
            operatorDid: operatorDid,
            governanceDid: governanceDid,
            platform: platform,
            mode: mode
        )
    }

    /// Default create shadow function — delegates to UniFFI
    /// ``bridgeCreateShadow(bridgeId:platformHandle:bridgeMode:contextId:)``.
    public static let defaultCreateShadow: CreateShadowFn = { bridgeId, platformHandle, bridgeMode, contextId in
        try bridgeCreateShadow(
            bridgeId: bridgeId,
            platformHandle: platformHandle,
            bridgeMode: bridgeMode,
            contextId: contextId
        )
    }
}

// MARK: - Public API

/// Evaluates the trust level for an action based on bridge provenance.
///
/// Returns an integer (0-3) representing the trust tier:
/// - 0: Shadow-bridged (lowest trust)
/// - 1: Claimed-bridged
/// - 2: Native-bridged
/// - 3: Native-native (highest trust)
///
/// - Parameters:
///   - isBridged: Whether the action originates from a bridge.
///   - isNativeTransport: Whether native SCP transport is used.
///   - shadowStatus: Shadow provenance status: "shadow" or "claimed".
///   - evaluateTrustFn: Bridge function override for testing.
/// - Returns: Trust tier integer (0-3).
/// - Throws: ``ScpError/Validation(msg:code:)`` if the shadow status
///   is not recognized.
///
/// ## Provenance
///
/// - Spec section 12 (Bridge System)
/// - ADR-023 (Bridge Connector)
public func evaluateBridgeTrust(
    isBridged: Bool,
    isNativeTransport: Bool,
    shadowStatus: String,
    evaluateTrustFn: BridgeConnectorBridge.EvaluateTrustFn = BridgeConnectorBridge.defaultEvaluateTrust
) throws -> UInt8 {
    try evaluateTrustFn(isBridged, isNativeTransport, shadowStatus)
}

/// Registers a bridge connector with a context.
///
/// Creates a registration for a bridge that connects an external platform
/// (e.g., Discord, Slack) to an SCP context. The bridge operator is
/// accountable for all messages relayed through the bridge.
///
/// - Parameters:
///   - contextId: The context to register the bridge in.
///   - operatorDid: DID of the human operator accountable for the bridge.
///   - governanceDid: DID of the governance authority approving the
///     registration.  Must differ from `operatorDid` (self-approval is
///     forbidden per ADR-023).
///   - platform: External platform name (e.g., `"discord"`, `"slack"`).
///   - mode: Bridge mode: `"relay"`, `"puppet"`, `"api"`, or
///     `"cooperative"`.
///   - registerFn: Bridge function override for testing.
/// - Returns: A ``BridgeRegistrationResult`` with the registration details.
/// - Throws: ``ScpError`` if registration fails (including self-approval).
///
/// ## Provenance
///
/// - Spec section 12 (Bridge System)
/// - ADR-023 (Bridge Connector)
public func bridgeRegister(
    contextId: String,
    operatorDid: String,
    governanceDid: String,
    platform: String,
    mode: String,
    registerFn: BridgeConnectorBridge.RegisterFn = BridgeConnectorBridge.defaultRegister
) throws -> BridgeRegistrationResult {
    try registerFn(contextId, operatorDid, governanceDid, platform, mode)
}

/// Creates a shadow identity for an external platform participant.
///
/// Shadow identities represent non-SCP participants in a bridged context.
/// They carry provenance metadata indicating they are not native SCP
/// identities.
///
/// - Parameters:
///   - bridgeId: The bridge connector ID that owns this shadow.
///   - platformHandle: External platform handle (e.g., `"@user#1234"`).
///   - bridgeMode: Bridge mode: `"relay"`, `"puppet"`, `"api"`, or
///     `"cooperative"`.
///   - contextId: Context the shadow is being created in.
///   - createShadowFn: Bridge function override for testing.
/// - Returns: A ``ShadowIdentityResult`` with the shadow identity details.
/// - Throws: ``ScpError`` if shadow creation fails.
///
/// ## Provenance
///
/// - Spec section 12 (Bridge System)
/// - ADR-023 (Bridge Connector)
public func bridgeCreateShadow(
    bridgeId: String,
    platformHandle: String,
    bridgeMode: String,
    contextId: String,
    createShadowFn: BridgeConnectorBridge.CreateShadowFn = BridgeConnectorBridge.defaultCreateShadow
) throws -> ShadowIdentityResult {
    try createShadowFn(bridgeId, platformHandle, bridgeMode, contextId)
}

// MARK: - Typed overloads

/// Evaluates bridge trust using typed ``ShadowStatus``.
///
/// Convenience overload that accepts a ``ShadowStatus`` enum value
/// instead of a raw string.
///
/// - Parameters:
///   - isBridged: Whether the action originates from a bridge.
///   - isNativeTransport: Whether native SCP transport is used.
///   - shadowStatus: Shadow provenance status.
///   - evaluateTrustFn: Bridge function override for testing.
/// - Returns: Trust tier integer (0-3).
/// - Throws: ``ScpError/Validation(msg:code:)`` if evaluation fails.
public func evaluateBridgeTrust(
    isBridged: Bool,
    isNativeTransport: Bool,
    shadowStatus: ShadowStatus,
    evaluateTrustFn: BridgeConnectorBridge.EvaluateTrustFn = BridgeConnectorBridge.defaultEvaluateTrust
) throws -> UInt8 {
    try evaluateTrustFn(isBridged, isNativeTransport, shadowStatus.rawValue)
}

/// Registers a bridge connector using typed ``BridgeMode``.
///
/// Convenience overload that accepts a ``BridgeMode`` enum value
/// instead of a raw string.
///
/// - Parameters:
///   - contextId: The context to register the bridge in.
///   - operatorDid: DID of the human operator accountable for the bridge.
///   - governanceDid: DID of the governance authority approving the
///     registration.  Must differ from `operatorDid` (self-approval is
///     forbidden per ADR-023).
///   - platform: External platform name (e.g., `"discord"`, `"slack"`).
///   - mode: Bridge mode.
///   - registerFn: Bridge function override for testing.
/// - Returns: A ``BridgeRegistrationResult`` with the registration details.
/// - Throws: ``ScpError`` if registration fails (including self-approval).
public func bridgeRegister(
    contextId: String,
    operatorDid: String,
    governanceDid: String,
    platform: String,
    mode: BridgeMode,
    registerFn: BridgeConnectorBridge.RegisterFn = BridgeConnectorBridge.defaultRegister
) throws -> BridgeRegistrationResult {
    try registerFn(contextId, operatorDid, governanceDid, platform, mode.rawValue)
}

/// Creates a shadow identity using typed ``BridgeMode``.
///
/// Convenience overload that accepts a ``BridgeMode`` enum value
/// instead of a raw string.
///
/// - Parameters:
///   - bridgeId: The bridge connector ID that owns this shadow.
///   - platformHandle: External platform handle (e.g., `"@user#1234"`).
///   - bridgeMode: Bridge mode.
///   - contextId: Context the shadow is being created in.
///   - createShadowFn: Bridge function override for testing.
/// - Returns: A ``ShadowIdentityResult`` with the shadow identity details.
/// - Throws: ``ScpError`` if shadow creation fails.
public func bridgeCreateShadow(
    bridgeId: String,
    platformHandle: String,
    bridgeMode: BridgeMode,
    contextId: String,
    createShadowFn: BridgeConnectorBridge.CreateShadowFn = BridgeConnectorBridge.defaultCreateShadow
) throws -> ShadowIdentityResult {
    try createShadowFn(bridgeId, platformHandle, bridgeMode.rawValue, contextId)
}
