import Foundation

// MARK: - McpToolDefinition

/// An MCP tool definition as reported by an external MCP server.
///
/// Represents a tool available through the Model Context Protocol. When
/// consumed via SCP, tool results are wrapped with provenance metadata
/// recording the external source, invoking agent, and context.
///
/// See ADR-015 in `.docs/adrs/phase-3.md`.
public nonisolated struct McpToolDefinition: Sendable {
    /// The tool name.
    public let name: String

    /// A human-readable description of what the tool does, if available.
    public let description: String?

    /// The JSON Schema describing the tool's input shape (as a JSON string).
    public let inputSchema: String

    /// Memberwise initializer.
    public init(name: String, description: String?, inputSchema: String) {
        self.name = name
        self.description = description
        self.inputSchema = inputSchema
    }
}

// MARK: - McpToolResult

/// The result of invoking an external MCP tool, wrapped with SCP provenance.
///
/// Maintains the protocol's provenance-everywhere principle: even tool calls
/// to external (non-SCP) MCP servers carry verifiable origin metadata.
///
/// See ADR-015 in `.docs/adrs/phase-3.md`.
public nonisolated struct McpToolResult: Sendable {
    /// The tool output content as serialized JSON.
    public let content: Data

    /// Whether the tool call resulted in an error.
    public let isError: Bool

    /// The source of the tool result, formatted as `"mcp:{tool_name}"`.
    public let source: String

    /// The DID of the agent that invoked the tool.
    public let invokedBy: String

    /// The SCP context ID in which the invocation was made.
    public let contextId: String

    /// The timestamp of the invocation (milliseconds since Unix epoch).
    public let timestamp: UInt64

    /// Memberwise initializer.
    public init(
        content: Data,
        isError: Bool,
        source: String,
        invokedBy: String,
        contextId: String,
        timestamp: UInt64
    ) {
        self.content = content
        self.isError = isError
        self.source = source
        self.invokedBy = invokedBy
        self.contextId = contextId
        self.timestamp = timestamp
    }
}

// MARK: - McpServerConfig

//
// McpServerConfig is generated by UniFFI at build time from the Rust bridge
// (`#[derive(uniffi::Record)]` in `crates/scp-ffi/uniffi/`). The committed
// `ScpBindings.swift` may not contain it (stale snapshot), but the CI build
// pipeline regenerates `ScpBindings.swift` before `swift build`, so the type
// is always available at compile time. Do NOT add a hand-written definition
// here — it will conflict with the generated one.

// MARK: - McpClientConfig

/// Configuration for connecting to an external MCP server.
///
/// Specifies how to connect to an external (non-SCP) MCP server. Tool results
/// from external servers are wrapped with SCP provenance metadata.
public nonisolated enum McpClientConfig: Sendable {
    /// Connect via stdio: spawn a subprocess and communicate over stdin/stdout.
    ///
    /// - Parameters:
    ///   - command: The command to execute (e.g., `"uvx"`).
    ///   - args: Arguments to pass to the command.
    case stdio(command: String, args: [String])

    /// Connect via SSE: HTTP client with Server-Sent Events.
    ///
    /// - Parameter url: The URL of the SSE endpoint.
    case sse(url: String)
}

// MARK: - McpBridge

/// Namespace for MCP bridge function references.
///
/// Server-side MCP functions are now part of the UniFFI bridge (see
/// `ScpBindings.swift`). Client-side functions use the injectable bridge
/// pattern: defaults delegate to placeholder implementations.
///
/// See ADR-015 for MCP spec and ADR-026 for the delegation pattern.
public enum McpBridge {
    /// Start an MCP server.
    public typealias ServeFn = @Sendable (
        _ config: McpServerConfig
    ) async throws -> Void

    /// Create an MCP client connection.
    public typealias ClientCreateFn = @Sendable (
        _ config: McpClientConfig
    ) async throws -> McpClientHandle

    /// List tools from an MCP client.
    public typealias ClientListToolsFn = @Sendable (
        _ handle: McpClientHandle
    ) async throws -> [McpToolDefinition]

    /// Invoke a tool via an MCP client.
    public typealias ClientInvokeFn = @Sendable (
        _ handle: McpClientHandle,
        _ toolName: String,
        _ input: Data,
        _ contextId: String,
        _ invokerDid: String
    ) async throws -> McpToolResult

    /// Default serve function. Will delegate to UniFFI when MCP exports land.
    public static let defaultServe: ServeFn = { _ in
        throw ScpError.Tool(
            msg: "MCP server bridge not yet wired to UniFFI — awaiting mcp_serve export",
            code: "SCP-MCP-10001"
        )
    }

    /// Default client create function. Will delegate to UniFFI when MCP exports land.
    public static let defaultClientCreate: ClientCreateFn = { _ in
        throw ScpError.Tool(
            msg: "MCP client bridge not yet wired to UniFFI — awaiting mcp_client_create export",
            code: "SCP-MCP-10002"
        )
    }

    /// Default client list tools function.
    public static let defaultClientListTools: ClientListToolsFn = { _ in
        throw ScpError.Tool(
            msg: "MCP client bridge not yet wired to UniFFI — awaiting mcp_client_list_tools export",
            code: "SCP-MCP-10003"
        )
    }

    /// Default client invoke function.
    public static let defaultClientInvoke: ClientInvokeFn = { _, _, _, _, _ in
        throw ScpError.Tool(
            msg: "MCP client bridge not yet wired to UniFFI — awaiting mcp_client_invoke export",
            code: "SCP-MCP-10004"
        )
    }
}

// MARK: - McpClientHandle

/// Internal opaque handle wrapping the UniFFI-generated MCP client binding.
///
/// This placeholder mirrors the handle type that UniFFI will generate from
/// the Rust `McpClient` struct. When the XCFramework build pipeline ships
/// (SCP-103), this definition is replaced by the auto-generated type.
public final class McpClientHandle: Sendable {
    /// Whether the MCP handshake has completed.
    let initialized: Bool

    /// Creates an ``McpClientHandle``.
    init(initialized: Bool = false) {
        self.initialized = initialized
    }
}

// MARK: - serveMcp

/// Starts an MCP server that exposes SCP context tools to MCP-compatible models.
///
/// Any MCP-compatible model (Claude, GPT, Gemini, open-source models) can
/// participate in SCP contexts through this server without knowing SCP exists.
/// The model sees MCP tools namespaced by context, calls them, and gets results.
///
/// The server handles:
/// - Tool listing (`tools/list`) with capability filtering
/// - Tool invocation (`tools/call`) with UCAN validation and provenance
/// - Resource listing and reading
/// - MCP lifecycle (`initialize`, `ping`)
///
/// Delegates to the MCP bridge serve function. When the UniFFI MCP exports
/// land, this will call through to the generated `mcp_serve` binding.
///
/// - Parameters:
///   - config: The ``McpServerConfig`` specifying which contexts to expose
///     and the transport type.
///   - serveFn: Bridge function override for testing.
/// - Throws: ``ScpError/Tool(msg:code:)`` if the server fails to start.
///
/// ## Provenance
///
/// - ADR-015 (MCP) in `.docs/adrs/phase-3.md`
/// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
/// - Story SCP-221
public func serveMcp(
    config: McpServerConfig,
    serveFn: McpBridge.ServeFn = McpBridge.defaultServe
) async throws {
    try await serveFn(config)
}

// MARK: - McpClient

/// An MCP client for consuming external tools with SCP provenance.
///
/// Connects to an external MCP server (non-SCP) and wraps tool results with
/// SCP provenance metadata. This maintains SCP's provenance-everywhere
/// principle even for external tool calls.
///
/// ## Usage
///
/// ```swift
/// let client = try await McpClient.connect(config: .stdio(
///     command: "uvx",
///     args: ["some-mcp-server"]
/// ))
/// let tools = try await client.listTools()
/// let result = try await client.invoke(
///     tool: "weather_lookup",
///     input: jsonData,
///     contextId: "ctx-123",
///     invokerDid: "did:dht:z6Mk..."
/// )
/// ```
///
/// ## Provenance
///
/// - ADR-015 (MCP) in `.docs/adrs/phase-3.md`
/// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
/// - Story SCP-101
public actor McpClient {
    /// The internal handle wrapping the native UniFFI MCP client.
    private let handle: McpClientHandle

    /// Bridge function for listing tools (injectable for testing).
    private let listToolsFn: McpBridge.ClientListToolsFn

    /// Bridge function for invoking tools (injectable for testing).
    private let invokeFn: McpBridge.ClientInvokeFn

    // MARK: - Internal Initializer

    /// Creates an ``McpClient`` from an internal ``McpClientHandle``.
    ///
    /// This initializer is internal -- callers use ``connect(config:)`` to
    /// obtain an ``McpClient``.
    ///
    /// - Parameters:
    ///   - handle: The opaque MCP client handle from the UniFFI bridge.
    ///   - listToolsFn: Bridge function for listing tools.
    ///   - invokeFn: Bridge function for invoking tools.
    init(
        handle: McpClientHandle,
        listToolsFn: @escaping McpBridge.ClientListToolsFn = McpBridge.defaultClientListTools,
        invokeFn: @escaping McpBridge.ClientInvokeFn = McpBridge.defaultClientInvoke
    ) {
        self.handle = handle
        self.listToolsFn = listToolsFn
        self.invokeFn = invokeFn
    }

    // MARK: - Factory

    /// Connects to an external MCP server and completes the MCP handshake.
    ///
    /// Delegates to the MCP bridge client create function. When the UniFFI
    /// MCP exports land, this will call through to the generated binding.
    ///
    /// - Parameters:
    ///   - config: The ``McpClientConfig`` specifying the connection transport.
    ///   - createFn: Bridge function override for testing.
    /// - Returns: A connected ``McpClient`` ready to list and invoke tools.
    /// - Throws: ``ScpError/Tool(msg:code:)`` if the connection or
    ///   handshake fails.
    ///
    /// ## Provenance
    ///
    /// - ADR-015 (MCP) in `.docs/adrs/phase-3.md`
    /// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
    /// - Story SCP-221
    public static func connect(
        config: McpClientConfig,
        createFn: McpBridge.ClientCreateFn = McpBridge.defaultClientCreate
    ) async throws -> McpClient {
        let handle = try await createFn(config)
        return McpClient(handle: handle)
    }

    // MARK: - Tool Listing

    /// Lists available tools from the external MCP server.
    ///
    /// Sends a `tools/list` JSON-RPC request and returns the tool definitions.
    ///
    /// - Returns: An array of ``McpToolDefinition`` values describing available
    ///   tools.
    /// - Throws: ``ScpError/Tool(msg:code:)`` if the listing fails.
    public func listTools() async throws -> [McpToolDefinition] {
        try await listToolsFn(handle)
    }

    // MARK: - Tool Invocation

    /// Invokes an external tool and wraps the result with SCP provenance.
    ///
    /// Sends a `tools/call` JSON-RPC request to the external MCP server, then
    /// wraps the result with provenance metadata recording the external tool
    /// source, the invoking agent's DID, the SCP context, and the timestamp.
    ///
    /// - Parameters:
    ///   - tool: The name of the external tool to invoke.
    ///   - input: The tool's input as serialized JSON data.
    ///   - contextId: The SCP context ID for provenance tracking.
    ///   - invokerDid: The DID of the agent invoking the tool.
    /// - Returns: An ``McpToolResult`` containing the output and provenance.
    /// - Throws: ``ScpError/Tool(msg:code:)`` if invocation fails.
    public func invoke(
        tool: String,
        input: Data,
        contextId: String,
        invokerDid: String
    ) async throws -> McpToolResult {
        try await invokeFn(handle, tool, input, contextId, invokerDid)
    }
}
