import Foundation

// OutletDefinition, OutletCostDefinition, and OutletVerificationResult are now defined by UniFFI in ScpBindings.swift.
//
// UniFFI OutletDefinition fields: name, description, inputSchemaJson, outputSchemaJson,
//     operatorDid, testVectorsJson, implementationHash, cost
// UniFFI OutletCostDefinition fields: amount, currency, payee, costFormula
// UniFFI OutletVerificationResult fields: outletId, passed, failures
//
// OutletInvocationResult is a pure Swift type (not in UniFFI) and is kept here.

// MARK: - OutletInvocationResult

/// The result of invoking an outlet within an SCP context.
///
/// Contains the outlet's output payload and provenance metadata recording which
/// agent invoked the outlet, in which context, and when.
///
/// This type is a pure Swift convenience type not generated by UniFFI.
///
/// See `.docs/sketch.md` section 4 "Outlets (within a context)".
public nonisolated struct OutletInvocationResult: Sendable {
    /// The serialized output from the outlet invocation (JSON).
    public let output: Data

    /// The DID of the agent that invoked the outlet.
    public let invokerDid: String

    /// The context ID in which the outlet was invoked.
    public let contextId: String

    /// Unix timestamp (milliseconds since epoch) of the invocation.
    public let timestamp: UInt64

    /// Memberwise initializer.
    public init(
        output: Data,
        invokerDid: String,
        contextId: String,
        timestamp: UInt64
    ) {
        self.output = output
        self.invokerDid = invokerDid
        self.contextId = contextId
        self.timestamp = timestamp
    }
}

// MARK: - OutletSessionResult

/// The result of creating a stateful outlet session.
///
/// Contains the session ID and metadata needed to invoke the outlet within
/// the session.
///
/// See spec section 6.2.1 (Stateful Outlet Sessions).
public nonisolated struct OutletSessionResult: Sendable {
    /// The unique session ID (UUID).
    public let sessionId: String

    /// Memberwise initializer.
    public init(sessionId: String) {
        self.sessionId = sessionId
    }
}

// Phase 4 PR 4 (ADR-048 demolition, #1549): the `OutletBridge` namespace —
// injectable closures whose defaults called `Scp.defaultInstance()` — has
// been deleted. Every outlet operation dispatches through the ``SCP``
// instance stored on the owning ``Context`` actor (see ``Context/scp``),
// which matches the Kotlin SDK shape.

// MARK: - Context Outlet Extensions

/// Outlet invocation and management extensions for ``Context``.
public extension Context {
    /// Invokes a registered outlet in this context.
    ///
    /// Delegates to the UniFFI ``outletInvoke`` bridge function. The input Data
    /// is converted to a UTF-8 JSON string for the bridge call, and the output
    /// JSON string is wrapped in a ``OutletInvocationResult`` with provenance.
    ///
    /// - Parameters:
    ///   - outlet: The name of the outlet to invoke.
    ///   - input: The outlet input as serialized JSON data.
    ///   - identity: The ``Identity`` of the invoking agent.
    ///   - invokeFn: Bridge function override for testing.
    /// - Returns: A ``OutletInvocationResult`` containing the outlet's output and
    ///   provenance metadata.
    /// - Throws: ``ScpError/Outlet(msg:code:)`` if the outlet is not found,
    ///   the input fails schema validation, or the invocation is unauthorized.
    ///   ``ScpError/Context(msg:code:)`` if the context is not active.
    ///
    /// ## Provenance
    ///
    /// - ADR-011 (Event Log) in `.docs/adrs/phase-2.md`
    /// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
    /// - Story SCP-221
    func invokeOutlet(
        _ outlet: String,
        input: Data,
        identity: Identity,
        ucanToken: String? = nil,
        proofTokens: [String]? = nil,
        spendingUcan: String? = nil,
        invokerDid: String? = nil
    ) async throws -> OutletInvocationResult {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        guard let inputJson = String(data: input, encoding: .utf8) else {
            throw ScpError.Outlet(
                msg: "Outlet input is not valid UTF-8",
                code: "SCP-OUTLET-6001"
            )
        }
        let outputJson = try await scp.outletInvoke(
            handle: handle,
            outletId: outlet,
            inputJson: inputJson,
            identity: identity,
            ucanToken: ucanToken,
            proofTokens: proofTokens,
            spendingUcanJwt: spendingUcan
        )
        return OutletInvocationResult(
            output: Data(outputJson.utf8),
            invokerDid: invokerDid ?? identity.did(),
            contextId: contextId,
            timestamp: UInt64(Date().timeIntervalSince1970 * 1000)
        )
    }

    /// Registers an outlet in this context.
    ///
    /// Delegates to the UniFFI ``outletRegister`` bridge function.
    ///
    /// - Parameters:
    ///   - definition: The ``OutletDefinition`` describing the outlet.
    ///   - registerFn: Bridge function override for testing.
    /// - Returns: The assigned outlet identifier.
    /// - Throws: ``ScpError/Outlet(msg:code:)`` if registration fails.
    ///   ``ScpError/Context(msg:code:)`` if the context is not active.
    ///
    /// ## Provenance
    ///
    /// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
    /// - Story SCP-221
    func registerOutlet(
        _ definition: OutletDefinition
    ) async throws -> String {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        return try await scp.outletRegister(handle: handle, definition: definition)
    }

    /// Verifies an outlet against its registered test vectors.
    ///
    /// Delegates to the UniFFI ``outletVerify`` bridge function.
    ///
    /// - Parameters:
    ///   - outlet: The name of the outlet to verify.
    ///   - verifyFn: Bridge function override for testing.
    /// - Returns: A ``OutletVerificationResult`` describing the outcome.
    /// - Throws: ``ScpError/Outlet(msg:code:)`` if the outlet is not found
    ///   or verification fails. ``ScpError/Context(msg:code:)`` if the
    ///   context is not active.
    ///
    /// ## Provenance
    ///
    /// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
    /// - Story SCP-221
    func verifyOutlet(
        _ outlet: String
    ) async throws -> OutletVerificationResult {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        return try await scp.outletVerify(handle: handle, outletId: outlet)
    }

    /// Invokes an outlet registered in a different context (cross-context).
    ///
    /// Delegates to the UniFFI ``outletInvokeCrossContext`` bridge function.
    /// Requires bidirectional consent: the source context must allow outbound
    /// outlet calls and the target context must allow inbound outlet calls.
    /// Chain depth is enforced (max 3 hops per spec section 6.2).
    ///
    /// - Parameters:
    ///   - outlet: The outlet ID to invoke in the target context.
    ///   - input: The outlet input as serialized JSON data.
    ///   - identity: The ``Identity`` of the invoking agent.
    ///   - targetContext: The ``Context`` containing the target outlet.
    ///   - chainDepth: Current chain depth (0 for direct invocation).
    ///   - invokeCrossContextFn: Bridge function override for testing.
    /// - Returns: A ``OutletInvocationResult`` containing the outlet's output
    ///   and provenance metadata.
    /// - Throws: ``ScpError/Outlet(msg:code:)`` if the outlet is not found,
    ///   chain depth exceeds the limit, or consent is denied.
    ///   ``ScpError/Context(msg:code:)`` if either context is not active.
    ///
    /// ## Provenance
    ///
    /// - Spec section 6.2 (Cross-Context Outlet Interfaces)
    /// - Story #322
    func invokeOutletCrossContext(
        _ outlet: String,
        input: Data,
        identity: Identity,
        targetContext: Context,
        ucanToken: String,
        chainDepth: UInt8 = 0,
        proofTokens: [String]? = nil,
        invokerDid: String? = nil
    ) async throws -> OutletInvocationResult {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Source context is not active",
                code: "SCP-CTX-2001"
            )
        }
        guard let inputJson = String(data: input, encoding: .utf8) else {
            throw ScpError.Outlet(
                msg: "Outlet input is not valid UTF-8",
                code: "SCP-OUTLET-6001"
            )
        }
        let targetHandle = targetContext.handle
        let outputJson = try await scp.outletInvokeCrossContext(
            sourceHandle: handle,
            targetHandle: targetHandle,
            outletId: outlet,
            inputJson: inputJson,
            identity: identity,
            ucanToken: ucanToken,
            chainDepth: chainDepth,
            proofTokens: proofTokens
        )
        return OutletInvocationResult(
            output: Data(outputJson.utf8),
            invokerDid: invokerDid ?? identity.did(),
            contextId: contextId,
            timestamp: UInt64(Date().timeIntervalSince1970 * 1000)
        )
    }

    /// Runs the §6.2.4 atomic cross-context outlet-invocation saga.
    ///
    /// Delegates to the UniFFI ``outletInvokeCrossContextSaga`` bridge function.
    /// Unlike ``invokeOutletCrossContext(_:input:identity:targetContext:ucanToken:chainDepth:proofTokens:invokerDid:)``
    /// (a single synchronous cross-context call), this drives the durable
    /// two-phase saga to a terminal: the call blocks until the saga either
    /// commits — resolving to a ``SagaResult`` carrying the supervisor-minted
    /// ``SagaResult/sagaId`` plus the target's signed receipt and captured
    /// output bytes — or reaches a typed terminal, surfaced directly as one of
    /// the generated ``ScpError`` saga cases:
    ///
    /// - ``ScpError/SagaAborted(msg:code:retryAfterMs:)`` — a Prepare-phase
    ///   abort: a PERMANENT rejection OR a RETRYABLE transient (rate limit /
    ///   participant actor unavailable), distinguished by the `SCP-SAGA-*`
    ///   code. `retryAfterMs` is the limiter's computed back-off, or `nil`
    ///   (never `0`) when no precise back-off instant exists.
    /// - ``ScpError/SagaNeedsRepair(msg:code:sagaId:)`` — Commit retries
    ///   exhausted (a possible divergence); carries the durable `sagaId`
    ///   operator-repair handle.
    /// - ``ScpError/SagaBusy(msg:code:contendedContext:)`` — the participant
    ///   context set overlapped an in-flight saga; carries the contended
    ///   context id (retry with back-off).
    ///
    /// The `chainDepth` (`UInt8`) and `timestampMs` (`UInt64`) parameters
    /// cannot encode an out-of-range or negative value, so no manual range
    /// validation is performed — Swift's type system enforces the bridge's
    /// `u8` / `u64` boundaries by construction.
    ///
    /// - Parameters:
    ///   - targetContext: The ``Context`` hosting the target outlet.
    ///   - callerDid: The DID of the invoking principal (bound to the
    ///     authenticated FFI identity by the bridge).
    ///   - outletRegistrationId: The target outlet's registration id.
    ///   - input: The outlet input as serialized JSON data.
    ///   - assertedNonceHex: The caller-asserted freshness nonce, as 32 hex
    ///     characters (16 bytes); the bridge rejects other lengths with a
    ///     `Validation` error.
    ///   - timestampMs: The caller-asserted freshness timestamp
    ///     (milliseconds since epoch).
    ///   - chainDepth: The caller-asserted inbound chain depth (0 for a
    ///     direct invocation).
    ///   - ucanProofId: Optional UCAN proof id authorizing the invocation.
    /// - Returns: A ``SagaResult`` on a committed terminal — a faithful
    ///   pass-through of the bridge result (`receipt` / `output` are surfaced
    ///   exactly as returned, `nil` when absent, never synthesized).
    /// - Throws: ``ScpError/SagaAborted(msg:code:retryAfterMs:)``,
    ///   ``ScpError/SagaNeedsRepair(msg:code:sagaId:)``, or
    ///   ``ScpError/SagaBusy(msg:code:contendedContext:)`` on a non-committed
    ///   terminal; ``ScpError/Context(msg:code:)`` (`SCP-CTX-2001`) if the
    ///   source context is not active; ``ScpError/Outlet(msg:code:)``
    ///   (`SCP-OUTLET-6001`) if the input is not valid UTF-8;
    ///   ``ScpError/Outlet(msg:code:)`` (`SCP-OUTLET-6002`, propagated from the
    ///   bridge) if `input` is valid UTF-8 but not valid JSON;
    ///   ``ScpError/Validation(msg:code:)`` (propagated from the bridge) if
    ///   `assertedNonceHex` is not 16-byte hex, or `callerDid` /
    ///   `outletRegistrationId` is malformed; ``ScpError/Permission(msg:code:)``
    ///   (`SCP-PERM-3030`, propagated from the bridge) if `targetContext` is a
    ///   foreign / cross-instance handle.
    ///
    /// ## Provenance
    ///
    /// - Spec section 6.2.4 (Cross-Context Outlet Invocation Saga)
    /// - ADR-049 §3a (per-participant-context-set saga gating)
    func invokeOutletCrossContextSaga(
        targetContext: Context,
        callerDid: String,
        outletRegistrationId: String,
        input: Data,
        assertedNonceHex: String,
        timestampMs: UInt64,
        chainDepth: UInt8,
        ucanProofId: String? = nil
    ) async throws -> SagaResult {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Source context is not active",
                code: "SCP-CTX-2001"
            )
        }
        guard let inputJson = String(data: input, encoding: .utf8) else {
            throw ScpError.Outlet(
                msg: "Outlet input is not valid UTF-8",
                code: "SCP-OUTLET-6001"
            )
        }
        let targetHandle = targetContext.handle
        return try await scp.outletInvokeCrossContextSaga(
            sourceHandle: handle,
            targetHandle: targetHandle,
            callerDid: callerDid,
            outletRegistrationId: outletRegistrationId,
            inputJson: inputJson,
            assertedNonceHex: assertedNonceHex,
            timestampMs: timestampMs,
            chainDepth: chainDepth,
            ucanProofId: ucanProofId
        )
    }

    /// Creates a stateful outlet session for repeated invocations.
    ///
    /// Delegates to the UniFFI ``outletSessionCreate`` bridge function.
    /// Sessions have an optional TTL and a per-caller cap (default 1000, ADR-043).
    ///
    /// - Parameters:
    ///   - outletId: The outlet ID to create a session for.
    ///   - sourceContextId: The context ID of the calling context.
    ///   - ttlSeconds: Time-to-live for the session in seconds, or `nil` for
    ///     a session that persists for the lifetime of the context (spec section 6.2.1).
    ///   - sessionCreateFn: Bridge function override for testing.
    /// - Returns: A ``OutletSessionResult`` containing the session ID.
    /// - Throws: ``ScpError/Outlet(msg:code:)`` if session creation fails.
    ///   ``ScpError/Context(msg:code:)`` if the context is not active.
    ///
    /// ## Provenance
    ///
    /// - Spec section 6.2.1 (Stateful Outlet Sessions)
    /// - Story #322
    func createOutletSession(
        outletId: String,
        sourceContextId: String,
        ttlSeconds: UInt64? = nil
    ) async throws -> OutletSessionResult {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        let sessionId = try await scp.outletSessionCreate(
            handle: handle,
            outletId: outletId,
            sourceContextId: sourceContextId,
            ttlSeconds: ttlSeconds
        )
        return OutletSessionResult(sessionId: sessionId)
    }

    /// Invokes an outlet within an active session.
    ///
    /// Delegates to the UniFFI ``outletSessionInvoke`` bridge function.
    /// Each invocation increments the session call count and checks
    /// TTL expiry.
    ///
    /// - Parameters:
    ///   - sessionId: The session ID from ``createOutletSession``.
    ///   - input: The outlet input as serialized JSON data.
    ///   - identity: The ``Identity`` of the invoking agent.
    ///   - sessionInvokeFn: Bridge function override for testing.
    /// - Returns: A ``OutletInvocationResult`` containing the outlet's output.
    /// - Throws: ``ScpError/Outlet(msg:code:)`` if the session is expired
    ///   or not found. ``ScpError/Context(msg:code:)`` if the context
    ///   is not active.
    ///
    /// ## Provenance
    ///
    /// - Spec section 6.2.1 (Stateful Outlet Sessions)
    /// - Story #322
    func invokeOutletSession(
        sessionId: String,
        input: Data,
        identity: Identity,
        ucanToken: String,
        proofTokens: [String]? = nil,
        invokerDid: String? = nil
    ) async throws -> OutletInvocationResult {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        guard let inputJson = String(data: input, encoding: .utf8) else {
            throw ScpError.Outlet(
                msg: "Outlet input is not valid UTF-8",
                code: "SCP-OUTLET-6001"
            )
        }
        let outputJson = try await scp.outletSessionInvoke(
            handle: handle,
            sessionId: sessionId,
            inputJson: inputJson,
            identity: identity,
            ucanToken: ucanToken,
            proofTokens: proofTokens
        )
        return OutletInvocationResult(
            output: Data(outputJson.utf8),
            invokerDid: invokerDid ?? identity.did(),
            contextId: contextId,
            timestamp: UInt64(Date().timeIntervalSince1970 * 1000)
        )
    }

    /// Closes a stateful outlet session.
    ///
    /// Delegates to the UniFFI ``outletSessionClose`` bridge function.
    /// The session is removed and can no longer be invoked.
    ///
    /// - Parameters:
    ///   - sessionId: The session ID to close.
    ///   - sessionCloseFn: Bridge function override for testing.
    /// - Throws: ``ScpError/Outlet(msg:code:)`` if the session is not
    ///   found. ``ScpError/Context(msg:code:)`` if the context is
    ///   not active.
    ///
    /// ## Provenance
    ///
    /// - Spec section 6.2.1 (Stateful Outlet Sessions)
    /// - Story #322
    func closeOutletSession(
        sessionId: String
    ) async throws {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        try await scp.outletSessionClose(handle: handle, sessionId: sessionId)
    }

    // MARK: - Bidirectional Consent Protocol (§6.2.0.1)

    /// Exposes an outlet interface for cross-context sharing (step 1).
    ///
    /// The caller (admin of the source context) proposes sharing a specific
    /// outlet with a target context.
    ///
    /// - Parameters:
    ///   - outletId: The ID of the outlet to expose.
    ///   - targetContextId: The target context to expose the outlet to.
    ///   - rateLimitJson: Optional per-interface rate limit as a JSON string.
    ///   - interfaceExposeFn: Bridge function override for testing.
    /// - Returns: The ``OutletInterface`` as a JSON string.
    /// - Throws: ``ScpError/Outlet(msg:code:)`` if the caller is not an admin
    ///   or the outlet is not found.
    func exposeOutletInterface(
        outletId: String,
        targetContextId: String,
        rateLimitJson: String? = nil
    ) async throws -> String {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        return try await scp.outletInterfaceExpose(
            handle: handle,
            outletId: outletId,
            targetContextId: targetContextId,
            rateLimitJson: rateLimitJson
        )
    }

    /// Accepts a cross-context outlet interface (step 4).
    ///
    /// Sets `approved_by_target = true` on the interface.
    ///
    /// - Parameters:
    ///   - interfaceJson: The ``OutletInterface`` JSON string to accept.
    ///   - interfaceAcceptFn: Bridge function override for testing.
    /// - Returns: The updated ``OutletInterface`` as a JSON string.
    /// - Throws: ``ScpError/Outlet(msg:code:)`` if the caller is not an admin
    ///   or context mismatch.
    func acceptOutletInterface(
        interfaceJson: String
    ) async throws -> String {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        return try await scp.outletInterfaceAccept(handle: handle, interfaceJson: interfaceJson)
    }

    /// Revokes a cross-context outlet interface (step 5).
    ///
    /// Either context may revoke unilaterally.
    ///
    /// - Parameters:
    ///   - interfaceIdHex: The 32-byte interface/offer ID as a hex string.
    ///   - interfaceRevokeFn: Bridge function override for testing.
    /// - Returns: The ``InterfaceRevoked`` event as a JSON string.
    /// - Throws: ``ScpError/Validation(msg:code:)`` if the hex ID is invalid.
    func revokeOutletInterface(
        interfaceIdHex: String
    ) async throws -> String {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        return try await scp.outletInterfaceRevoke(handle: handle, interfaceIdHex: interfaceIdHex)
    }
}
