import Foundation

// SCP-OUT-037 (UniFFI portion) — Swift streaming surface.
//
// Wraps the UniFFI-generated `OutletStreamHandle` as an `AsyncSequence`
// so callers can iterate chunks with `for await chunk in stream`. The
// underlying `next()` polling is generated by UniFFI in
// `Internal/ScpBindings.swift`; this file is the pure-Swift ergonomics
// layer (ADR-021 — protocol logic stays in Rust, idioms in the SDK).
//
// UniFFI-generated symbols this file uses (regenerated from
// `crates/scp-ffi/uniffi/src/outlet_stream.rs`):
// - `OutletStreamHandle` — opaque async-iterator class with `next()`
//   and `cancel(nextSeq:)`
// - `OutletStreamChunkRecord` — chunk payload record
// - `OutletStreamSubscriber` — push-style callback interface
// - `outletInvokeStream(...)` — open returns OutletStreamHandle
// - `outletInvokeStreamWithSubscriber(...)` — open + push
// - `outletStreamGrantCredit(requestIdHex:grant:)`
// - `outletStreamCancel(requestIdHex:nextSeq:)`
// - `verifyChunkSignature(chunkJson:operatorPk:contextId:outletId:caveatsBinding:)`
// - `computeCaveatsBinding(ucanCid:requestId:invokerDid:estimatedChunkCount:effectiveCaveatsJson:)`

// MARK: - StreamChunk (Swift-native record)

/// One chunk yielded by ``OutletStreamSequence`` or pushed to a
/// ``OutletStreamSubscriber``. Mirrors the §5.4.5 wire form variant-by-
/// variant — callers branch on `payloadType` and read the variant
/// fields directly.
public struct OutletStreamChunkRecordSwift: Sendable, Equatable {
    /// 16-byte §5.4.5 `request_id` of the stream this chunk belongs to.
    public let requestId: Data
    /// Strictly-monotonic per-stream chunk sequence number.
    public let sequence: UInt64
    /// 64-byte `SCP-OUTLET-CHUNK-SIG-V1:` Ed25519 signature.
    public let sig: Data
    /// One of `"data"` / `"progress"` / `"end"` / `"error"`.
    public let payloadType: String
    public let valueJson: String?
    public let pct: UInt16?
    public let note: String?
    public let aggregateJson: String?
    public let provenanceJson: String?
    public let executionTimeMs: UInt64?
    public let code: String?
    public let message: String?
    public let terminal: Bool?

    public init(from raw: OutletStreamChunkRecord) {
        requestId = Data(raw.requestId)
        sequence = raw.sequence
        sig = Data(raw.sig)
        payloadType = raw.payloadType
        valueJson = raw.valueJson
        pct = raw.pct
        note = raw.note
        aggregateJson = raw.aggregateJson
        provenanceJson = raw.provenanceJson
        executionTimeMs = raw.executionTimeMs
        code = raw.code
        message = raw.message
        terminal = raw.terminal
    }
}

// MARK: - OutletStreamSequence (AsyncSequence wrapper)

/// `AsyncSequence` wrapper around the UniFFI-generated
/// `OutletStreamHandle`. Iteration drives `next()` until the handle
/// reports `done`; subsequent iteration yields no values.
///
/// Construct via ``Context/openOutletStream(outletId:inputJson:ucanToken:caveatsBindingHex:streamEpoch:proofTokens:creditWindow:estimatedChunkCount:)``.
public struct OutletStreamSequence: AsyncSequence, Sendable {
    public typealias Element = OutletStreamChunkRecordSwift
    public typealias AsyncIterator = OutletStreamIterator

    /// The UniFFI handle. `internal` so extensions can call control-plane
    /// operations on the same handle without exposing it publicly.
    let handle: OutletStreamHandle

    public init(handle: OutletStreamHandle) {
        self.handle = handle
    }

    public func makeAsyncIterator() -> OutletStreamIterator {
        OutletStreamIterator(handle: handle)
    }

    /// 32-char lowercase hex `request_id`. Use this to address the stream
    /// from the SDK control-plane methods.
    public var requestIdHex: String {
        handle.requestId()
    }

    /// Returns `true` once a terminal chunk has been observed (or the
    /// receiver has been closed).
    public var isDone: Bool {
        handle.done()
    }

    /// Signs and applies an `OutletStreamCredit` grant for this stream.
    ///
    /// `grant` must be > 0 (round-6 uniform `InvalidGrant` rule).
    /// Returns the new total credit budget on success.
    @discardableResult
    public func grantCredit(_ grant: UInt32) async throws -> UInt32 {
        try await outletStreamGrantCredit(requestIdHex: requestIdHex, grant: grant)
    }

    /// Applies an `OutletCancel` to this stream.
    ///
    /// `nextSeq` is the receiver's view of the next-to-emit chunk
    /// sequence (defaults to `0`).
    @discardableResult
    public func cancel(nextSeq: UInt64? = nil) async throws -> UInt64? {
        try await handle.cancel(nextSeq: nextSeq)
    }
}

/// `AsyncIterator` for `OutletStreamSequence`.
public struct OutletStreamIterator: AsyncIteratorProtocol, Sendable {
    let handle: OutletStreamHandle

    public init(handle: OutletStreamHandle) {
        self.handle = handle
    }

    public mutating func next() async throws -> OutletStreamChunkRecordSwift? {
        guard let raw = try await handle.next() else {
            return nil
        }
        return OutletStreamChunkRecordSwift(from: raw)
    }
}

// MARK: - Context streaming entry points

public extension Context {
    /// Opens a §5.4.5 streaming outlet invocation and returns an
    /// `AsyncSequence` of chunks.
    ///
    /// Mirrors the PyO3 / NAPI / SDK contracts: re-validates the UCAN
    /// under the full 11-step ADR-016 pipeline, reserves a per-stream
    /// `request_id`, and registers the session for later
    /// `grantCredit` / `cancel` lookups.
    ///
    /// - Parameters:
    ///   - outletId: Outlet to invoke.
    ///   - inputJson: JSON-encoded input matching the outlet's input
    ///     schema.
    ///   - ucanToken: UCAN authorising the invocation.
    ///   - caveatsBindingHex: 32-byte `caveats_binding` rendered as
    ///     64-char lowercase hex. Compute via
    ///     ``OutletsStreaming/computeCaveatsBinding(ucanCid:requestId:invokerDid:estimatedChunkCount:effectiveCaveatsJson:)``.
    ///   - streamEpoch: Hosting context's MLS epoch counter at open
    ///     acceptance.
    ///   - proofTokens: Optional encoded parent UCANs for delegation-
    ///     chain traversal.
    ///   - creditWindow: Initial credit-window size; defaults to §5.4.5
    ///     `DEFAULT_CREDIT_WINDOW` when `nil`.
    ///   - estimatedChunkCount: Optional upper bound on billable chunks.
    /// - Returns: An ``OutletStreamSequence`` ready for `for await`
    ///   iteration. Use ``OutletStreamSequence/grantCredit(_:)`` /
    ///   ``OutletStreamSequence/cancel(nextSeq:)`` to manage flow.
    func openOutletStream(
        outletId: String,
        inputJson: String,
        ucanToken: String,
        caveatsBindingHex: String,
        streamEpoch: UInt64,
        proofTokens: [String]? = nil,
        creditWindow: UInt32? = nil,
        estimatedChunkCount: UInt32? = nil
    ) async throws -> OutletStreamSequence {
        let raw = try await outletInvokeStream(
            handle: handle,
            outletId: outletId,
            inputJson: inputJson,
            identity: identity,
            ucanToken: ucanToken,
            caveatsBindingHex: caveatsBindingHex,
            streamEpoch: streamEpoch,
            proofTokens: proofTokens,
            creditWindow: creditWindow,
            estimatedChunkCount: estimatedChunkCount
        )
        return OutletStreamSequence(handle: raw)
    }

    /// Push-style variant of ``openOutletStream`` that drives every
    /// chunk into a caller-supplied `OutletStreamSubscriber`. Returns
    /// the 32-char hex `request_id` so the caller can address the
    /// active stream from
    /// ``OutletsStreaming/grantCredit(requestIdHex:grant:)`` /
    /// ``OutletsStreaming/cancel(requestIdHex:nextSeq:)`` before the
    /// pump exits.
    @discardableResult
    func openOutletStreamWithSubscriber(
        outletId: String,
        inputJson: String,
        ucanToken: String,
        caveatsBindingHex: String,
        streamEpoch: UInt64,
        proofTokens: [String]? = nil,
        creditWindow: UInt32? = nil,
        estimatedChunkCount: UInt32? = nil,
        subscriber: OutletStreamSubscriber
    ) async throws -> String {
        try await outletInvokeStreamWithSubscriber(
            handle: handle,
            outletId: outletId,
            inputJson: inputJson,
            identity: identity,
            ucanToken: ucanToken,
            caveatsBindingHex: caveatsBindingHex,
            streamEpoch: streamEpoch,
            proofTokens: proofTokens,
            creditWindow: creditWindow,
            estimatedChunkCount: estimatedChunkCount,
            subscriber: subscriber
        )
    }
}

// MARK: - Top-level streaming helpers

/// Top-level convenience namespace for the streaming-helper free
/// functions that do not require a `Context`.
public enum OutletsStreaming {
    /// Verifies a chunk's `SCP-OUTLET-CHUNK-SIG-V1:` Ed25519 signature.
    public static func verifyChunkSignature(
        chunkJson: String,
        operatorPk: Data,
        contextId: String,
        outletId: String,
        caveatsBinding: Data
    ) throws -> Bool {
        try SCP.verifyChunkSignature(
            chunkJson: chunkJson,
            operatorPk: operatorPk,
            contextId: contextId,
            outletId: outletId,
            caveatsBinding: caveatsBinding
        )
    }

    /// Recomputes the §5.4.5 `caveats_binding` 32-byte SHA-256 over the
    /// `SCP-OUTLET-CAVEAT-BIND-V1:` preimage.
    public static func computeCaveatsBinding(
        ucanCid: Data,
        requestId: Data,
        invokerDid: String,
        estimatedChunkCount: UInt32,
        effectiveCaveatsJson: String
    ) throws -> Data {
        try SCP.computeCaveatsBinding(
            ucanCid: ucanCid,
            requestId: requestId,
            invokerDid: invokerDid,
            estimatedChunkCount: estimatedChunkCount,
            effectiveCaveatsJson: effectiveCaveatsJson
        )
    }

    /// Signs and applies an `OutletStreamCredit` grant against an active
    /// stream identified by `requestIdHex`.
    @discardableResult
    public static func grantCredit(
        requestIdHex: String,
        grant: UInt32
    ) async throws -> UInt32 {
        try await outletStreamGrantCredit(requestIdHex: requestIdHex, grant: grant)
    }

    /// Applies an `OutletCancel` to an active stream by `requestIdHex`.
    @discardableResult
    public static func cancel(
        requestIdHex: String,
        nextSeq: UInt64? = nil
    ) async throws -> UInt64? {
        try await outletStreamCancel(requestIdHex: requestIdHex, nextSeq: nextSeq)
    }
}

/// Module-internal trampoline namespace that calls the UniFFI-generated
/// free functions. Centralised here so the public API can stay stable
/// when UniFFI regenerates bindings.
private enum SCP {
    static func verifyChunkSignature(
        chunkJson: String,
        operatorPk: Data,
        contextId: String,
        outletId: String,
        caveatsBinding: Data
    ) throws -> Bool {
        // `verifyChunkSignature` is a UniFFI free function generated at
        // module scope (in `Internal/ScpBindings.swift`).
        try verifyChunkSignature(
            chunkJson: chunkJson,
            operatorPk: operatorPk,
            contextId: contextId,
            outletId: outletId,
            caveatsBinding: caveatsBinding
        )
    }

    static func computeCaveatsBinding(
        ucanCid: Data,
        requestId: Data,
        invokerDid: String,
        estimatedChunkCount: UInt32,
        effectiveCaveatsJson: String
    ) throws -> Data {
        try computeCaveatsBinding(
            ucanCid: ucanCid,
            requestId: requestId,
            invokerDid: invokerDid,
            estimatedChunkCount: estimatedChunkCount,
            effectiveCaveatsJson: effectiveCaveatsJson
        )
    }
}
