import Foundation

// SCP-OUT-037 (UniFFI portion) — Swift streaming surface.
//
// Wraps the UniFFI-generated `OutletStreamHandle` as an `AsyncSequence`
// so callers can iterate chunks with `for await chunk in stream`. The
// underlying `next()` polling is generated by UniFFI in
// `Internal/ScpBindings.swift`; this file is the pure-Swift ergonomics
// layer (ADR-021 — protocol logic stays in Rust, idioms in the SDK).
//
// UniFFI-generated symbols this file uses (regenerated from
// `crates/scp-ffi/uniffi/src/outlet_stream.rs`):
// - `OutletStreamHandle` — opaque async-iterator class with `next()`
//   and `cancel()` (CRITICAL #3 — `next_seq` is no longer accepted)
// - `OutletStreamChunkRecord` — chunk payload record
// - `OutletStreamSubscriber` — push-style callback interface
// - `outletInvokeStream(...)` — open returns OutletStreamHandle
// - `outletInvokeStreamWithSubscriber(...)` — open + push
// - `outletStreamGrantCredit(requestIdHex:grant:)`
// - `outletStreamCancel(requestIdHex:)`
// - `verifyChunkSignature(chunkJson:operatorPk:contextId:outletId:caveatsBinding:)`
// - `computeCaveatsBinding(ucanCid:requestId:invokerDid:estimatedChunkCount:effectiveCaveatsJson:)`

// MARK: - StreamChunk (Swift-native record)

/// One chunk pushed to an ``OutletStreamSubscriber`` (push-style
/// streaming). Mirrors the §5.4.5 wire form variant-by-variant —
/// callers branch on `payloadType` and read the variant fields directly.
public struct OutletStreamChunkRecordSwift: Sendable, Equatable {
    /// 16-byte §5.4.5 `request_id` of the stream this chunk belongs to.
    public let requestId: Data
    /// Strictly-monotonic per-stream chunk sequence number.
    public let sequence: UInt64
    /// 64-byte `SCP-OUTLET-CHUNK-SIG-V1:` Ed25519 signature.
    public let sig: Data
    /// One of `"data"` / `"progress"` / `"end"` / `"error"`.
    public let payloadType: String
    public let valueJson: String?
    public let pct: UInt16?
    public let note: String?
    public let aggregateJson: String?
    public let provenanceJson: String?
    public let executionTimeMs: UInt64?
    public let code: String?
    public let message: String?
    public let terminal: Bool?

    public init(from raw: OutletStreamChunkRecord) {
        requestId = Data(raw.requestId)
        sequence = raw.sequence
        sig = Data(raw.sig)
        payloadType = raw.payloadType
        valueJson = raw.valueJson
        pct = raw.pct
        note = raw.note
        aggregateJson = raw.aggregateJson
        provenanceJson = raw.provenanceJson
        executionTimeMs = raw.executionTimeMs
        code = raw.code
        message = raw.message
        terminal = raw.terminal
    }
}

// MARK: - Context streaming entry points

extension Context {
    /// Push-style §5.4.5 streaming entry point — internal per AC1;
    /// routes through the streaming UniFFI export with a caller-
    /// supplied `OutletStreamSubscriber`.
    ///
    /// The pull-style session opener (`openOutletStreamSession`) and its
    /// `AsyncSequence` wrapper (`OutletStreamSequence` /
    /// `OutletStreamIterator`) were removed: the SDK's single public verb
    /// `ctx.outlets.invoke(...)` drives streaming through
    /// `makeStreamingHandle`, which calls `outletInvokeStream` +
    /// `pumpStreamingChunks` directly. The parallel surface was redundant
    /// and — worse — carried a divergent abnormal-closure slug
    /// (`execution.stream-gap`, unregistered in the spec). The pull
    /// control plane is now exclusively the `InvocationHandle` methods;
    /// the canonical abnormal-closure error lives in `streamGapEnvelope()`.
    @discardableResult
    func openOutletStreamSessionWithSubscriber(
        outletId: String,
        inputJson: String,
        ucanToken: String,
        caveatsBindingHex: String,
        streamEpoch: UInt64,
        proofTokens: [String]? = nil,
        creditWindow: UInt32? = nil,
        estimatedChunkCount: UInt32? = nil,
        spendingUcan: String? = nil,
        subscriber: OutletStreamSubscriber
    ) async throws -> String {
        try await outletInvokeStreamWithSubscriber(
            handle: handle,
            outletId: outletId,
            inputJson: inputJson,
            identity: identity,
            ucanToken: ucanToken,
            caveatsBindingHex: caveatsBindingHex,
            streamEpoch: streamEpoch,
            proofTokens: proofTokens,
            creditWindow: creditWindow,
            estimatedChunkCount: estimatedChunkCount,
            spendingUcan: spendingUcan,
            subscriber: subscriber
        )
    }
}

/// Spawns the §5.4.5 receiver-side revocation re-check task that
/// runs alongside the streaming pump for the lifetime of the stream.
///
/// Per spec ("Revocation re-check cadence (receiver-side)") the SDK
/// framework MUST periodically re-check the opening UCAN's revocation
/// status during the stream's active lifetime, every
/// `stream_ucan_recheck_secs`, and on observed revocation MUST
/// terminate the stream with `RevokedMidStream` / `SCP-TOOL-6110`.
///
/// Returns the spawned `Task` so the caller (the streaming pump) can
/// cancel it via `defer { recheckTask.cancel() }` when the parent pump
/// resolves naturally — once the stream emits a terminal chunk, the
/// recheck loop has nothing more to do — OR via
/// `InvocationHandle.close()` for an UNBOUNDED, never-consumed stream
/// whose eager pump never reaches a terminal chunk. Spec:
/// "Already-emitted chunks remain authorized; the stream closes at or
/// before `stream_ucan_recheck_secs` after the revocation event
/// regardless of executor behavior."
///
/// `validate` and `terminate` are injectable closures defaulting to the
/// real UniFFI `ucanValidate` / `OutletsStreaming.terminate`. The defaults
/// are the production path; the injectable seam lets tests drive the loop
/// against a synthetic validator (e.g. counting calls) without the
/// XCFramework binary, so a test can assert that `close()` /
/// `recheckTask.cancel()` actually stops the polling.
/// `validate` / `terminate` default to `nil`, in which case the loop binds
/// the production UniFFI `ucanValidate` / `OutletsStreaming.terminate`
/// (using the captured `contextHandle` / `requestIdHex` / `invokerDid`).
/// A non-`nil` closure overrides the default — the injectable seam tests
/// use to drive the loop against a synthetic validator without the
/// XCFramework binary, so a test can assert that `recheckTask.cancel()`
/// (the mechanism `InvocationHandle.close()` invokes) stops the polling.
@Sendable
func makeRevocationRecheckTask(
    contextHandle: ContextHandle,
    outletId: String,
    ucanToken: String,
    proofTokens: [String]?,
    recheckSecs: UInt32,
    requestIdHex: String,
    invokerDid: String,
    validate: (@Sendable (
        _ token: String,
        _ capability: String,
        _ proofTokens: [String]?
    ) async throws -> Void)? = nil,
    terminate: (@Sendable () async -> Void)? = nil
) -> Task<Void, Never> {
    // Production bindings used when the caller does not inject a seam.
    // `ucanValidate` is a UniFFI free function generated at module scope.
    let effectiveValidate: @Sendable (String, String, [String]?) async throws -> Void =
        validate ?? { token, capability, proof in
            try await ucanValidate(
                handle: contextHandle,
                token: token,
                capability: capability,
                presentingAgentDid: nil,
                proofTokens: proof
            )
        }
    let effectiveTerminate: @Sendable () async -> Void =
        terminate ?? {
            _ = try? await OutletsStreaming.terminate(
                requestIdHex: requestIdHex,
                callerDid: invokerDid,
                reason: .revokedMidStream,
                messageOverride: "ucan revoked or invalid mid-stream"
            )
        }
    return Task { [weak contextHandle] in
        guard contextHandle != nil else { return }
        let capability = "tool_invoke:\(outletId)"
        let interval = max(UInt64(1), UInt64(recheckSecs))
        while !Task.isCancelled {
            try? await Task.sleep(nanoseconds: interval * 1_000_000_000)
            if Task.isCancelled { return }
            do {
                guard contextHandle != nil else { return }
                try await effectiveValidate(ucanToken, capability, proofTokens)
            } catch {
                // UCAN no longer valid — terminate the stream with
                // the spec slug + code. Recoverable failures
                // (already terminated / pending) stop the loop
                // naturally because outletStreamTerminate's contract
                // is idempotent on the runtime side.
                await effectiveTerminate()
                return
            }
        }
    }
}

/// Drains an open `OutletStreamHandle` into the InvocationHandle's
/// pump sink. Called by `OutletNamespace.invoke` in streaming mode —
/// kept at module scope so the per-mode helper functions in
/// `Outlets.swift` stay short enough to satisfy SwiftLint's
/// `function_body_length` rule.
///
/// Per OUT-038 AC14 the iterator yields the terminal chunk too: every
/// chunk read from the bridge is forwarded to `yieldChunk` before any
/// terminal-state transition. End resolves the aggregate with the
/// chunk's `aggregate` field; terminal Error{terminal:true} rejects
/// with an `OutletError.execution(...)` envelope.
///
/// Abnormal-closure handling: if `raw.next()` returns `nil` BEFORE a
/// terminal chunk (`End` / `Error{terminal:true}`) was observed, the
/// pump surfaces an `execution.stream-gap` (`SCP-TOOL-6131`) error via
/// `rejectAggregate` — a transport drop, executor crash, or bridge
/// fault MUST NOT be reported as a successful aggregate-null outcome.
func pumpStreamingChunks(
    from raw: OutletStreamHandle,
    yieldChunk: @Sendable (OutletStreamChunk) -> Void,
    resolveAggregate: @Sendable (Aggregate) -> Void,
    rejectAggregate: @Sendable (Error) -> Void
) async throws {
    try await pumpStreamingChunksWithNext(
        next: { try await raw.next() },
        yieldChunk: yieldChunk,
        resolveAggregate: resolveAggregate,
        rejectAggregate: rejectAggregate
    )
}

/// Captured configuration for the streaming-mode pump closure. Bundles
/// the §5.4.5 open parameters plus the shared `RequestIdBox` /
/// `CancelRegistry` so `makeStreamingPump` can be a module-scope free
/// function (keeping `OutletNamespace.makeStreamingHandle`'s body within
/// SwiftLint's `function_body_length`). All fields are `Sendable`.
struct StreamingPumpConfig: @unchecked Sendable {
    let handle: ContextHandle
    let identity: Identity
    let invokerDid: String
    let outletId: String
    let inputJson: String
    let ucanToken: String
    let caveatsBindingHex: String
    let streamEpoch: UInt64
    let proofTokens: [String]?
    let creditWindow: UInt32?
    let estimatedChunkCount: UInt32?
    let spendingUcan: String?
    let ucanRecheckSecs: UInt32
    let requestIdBox: RequestIdBox
    let cancelRegistry: CancelRegistry
}

/// Builds the streaming-mode pump closure for `InvocationHandle` — opens
/// the §5.4.5 stream, resolves the `request_id` box, spawns the
/// receiver-side revocation re-check task, and drains chunks. The chunk-
/// pump `Task` and the recheck `Task` cancels are registered into the
/// shared `CancelRegistry` so `InvocationHandle.close()` can tear them
/// down for an UNBOUNDED, never-consumed stream whose eager pump never
/// reaches a terminal chunk on its own.
///
/// Module-scope (not a method) so the calling factory's body stays short;
/// mirrors `pumpStreamingChunks` living at module scope for the same
/// reason.
func makeStreamingPump(
    _ config: StreamingPumpConfig
) -> @Sendable (
    @Sendable @escaping (OutletStreamChunk) -> Void,
    @Sendable @escaping (Aggregate) -> Void,
    @Sendable @escaping (Error) -> Void
) -> Void {
    { yieldChunk, resolveAggregate, rejectAggregate in
        let pumpTask = Task {
            do {
                let raw = try await outletInvokeStream(
                    handle: config.handle,
                    outletId: config.outletId,
                    inputJson: config.inputJson,
                    identity: config.identity,
                    ucanToken: config.ucanToken,
                    caveatsBindingHex: config.caveatsBindingHex,
                    streamEpoch: config.streamEpoch,
                    proofTokens: config.proofTokens,
                    creditWindow: config.creditWindow,
                    estimatedChunkCount: config.estimatedChunkCount,
                    spendingUcan: config.spendingUcan
                )
                // Thread the real §5.4.5 `request_id` into the handle as
                // soon as the open resolves — BEFORE pumping chunks — so
                // control-plane callers that raced to `grantCredit` /
                // `cancel` immediately after `invoke()` unblock with a
                // valid id.
                let requestIdHex = raw.requestId()
                await config.requestIdBox.resolve(requestIdHex)
                let recheckTask = makeRevocationRecheckTask(
                    contextHandle: config.handle,
                    outletId: config.outletId,
                    ucanToken: config.ucanToken,
                    proofTokens: config.proofTokens,
                    recheckSecs: config.ucanRecheckSecs,
                    requestIdHex: requestIdHex,
                    invokerDid: config.invokerDid
                )
                // Register the recheck `Task` cancel so `close()` can stop
                // the §5.4.5 revocation-recheck loop for an UNBOUNDED,
                // never-consumed stream. The `defer` below still covers
                // the normal path (pump reaches a terminal chunk). Both
                // are idempotent — `Task.cancel()` is safe to call more
                // than once. If `close()` already ran, the registry fires
                // this immediately so the just-spawned task is cancelled
                // at once.
                config.cancelRegistry.register { recheckTask.cancel() }
                defer { recheckTask.cancel() }
                try await pumpStreamingChunks(
                    from: raw,
                    yieldChunk: yieldChunk,
                    resolveAggregate: resolveAggregate,
                    rejectAggregate: rejectAggregate
                )
            } catch {
                // Open failed before a `request_id` was known — resolve
                // the box to `nil` so awaiting control-plane callers
                // unblock and surface `streamAlreadyClosed` (no streaming
                // session) rather than hanging forever.
                await config.requestIdBox.resolve(nil)
                rejectAggregate(error)
            }
        }
        // Register the outer pump `Task` cancel so `close()` tears down
        // the open + chunk drain too (not only the recheck loop). The open
        // (`outletInvokeStream`) and `pumpStreamingChunks` observe
        // cancellation and unwind, which also runs the `defer` that
        // cancels the recheck task.
        config.cancelRegistry.register { pumpTask.cancel() }
    }
}

/// Injectable test-seam variant of `pumpStreamingChunks` — accepts a
/// `next` closure so tests can drive the pump against a synthetic
/// chunk source without constructing a UniFFI `OutletStreamHandle`
/// (the latter requires the XCFramework binary). The production
/// `pumpStreamingChunks` is a thin wrapper that pins `next` to
/// `raw.next()`.
///
/// `internal` so the SCPTests target can reach it without exposing
/// the helper publicly.
func pumpStreamingChunksWithNext(
    next: @Sendable () async throws -> OutletStreamChunkRecord?,
    yieldChunk: @Sendable (OutletStreamChunk) -> Void,
    resolveAggregate: @Sendable (Aggregate) -> Void,
    rejectAggregate: @Sendable (Error) -> Void
) async throws {
    var terminalObserved = false
    while true {
        guard let bridgeChunk = try await next() else {
            // Abnormal closure — `next()` returned `nil` before the
            // executor emitted a terminal chunk. Surface as
            // `execution.stream-gap` (`SCP-TOOL-6131`) per §5.4.4. A
            // prior terminal observation means this `nil` is the
            // normal end-of-receiver marker.
            if terminalObserved {
                return
            }
            rejectAggregate(OutletError.execution(streamGapEnvelope()))
            return
        }
        let sdkChunk = bridgeChunkToSdk(bridgeChunk)
        yieldChunk(sdkChunk)
        switch sdkChunk.payload {
        case let .end(aggregate, executionTimeMs):
            terminalObserved = true
            resolveAggregate(Aggregate(valueJson: aggregate, executionTimeMs: executionTimeMs))
            return
        case let .error(code, message, terminal):
            if terminal {
                terminalObserved = true
                rejectAggregate(OutletError.execution(terminalErrorEnvelope(code: code, message: message)))
                return
            }
        default:
            break
        }
    }
}

/// Abnormal-closure envelope for the receiver-closed-early path (bridge
/// receiver returned `nil` before any terminal chunk).
///
/// Code `SCP-TOOL-6131`, NO slug — matching the Python reference and the
/// other SDKs. §5.4.5 does register `execution.stream-gap` on the shared
/// 6131 code band, but that slug names a DISTINCT condition (an explicit
/// in-stream gap signal). The condition the SDK surfaces here — the
/// receiver closed before any terminal chunk — is not the spec's
/// StreamGap, so the SDK intentionally omits the slug to avoid
/// conflating the two. `OutletEnvelope.slug` is a non-optional `String`,
/// so "no slug" is the empty string.
private func streamGapEnvelope() -> OutletEnvelope {
    OutletEnvelope(
        classWire: .execution,
        code: "SCP-TOOL-6131",
        slug: "",
        message: "stream closed without terminal chunk",
        retry: .never,
        detail: nil,
        sourceChain: [],
        padNonce: nil,
        registrationEventId: nil
    )
}

/// Envelope for a terminal `Error{terminal: true}` chunk observed
/// mid-stream — the chunk's own code+message become the envelope's.
///
/// The §5.4.5 Error chunk wire form carries `code` / `message` /
/// `terminal` only — there is no per-chunk slug field. So the envelope
/// MUST NOT borrow `code` as the slug: `code` is the `SCP-TOOL-NNNN`
/// string, which is not a valid slug (slugs match `^[a-z][a-z0-9-]…`).
/// `OutletEnvelope.slug` is a non-optional `String`, so absence of a
/// slug is the empty string — matching `streamGapEnvelope()`.
private func terminalErrorEnvelope(code: String, message: String) -> OutletEnvelope {
    OutletEnvelope(
        classWire: .execution,
        code: code,
        slug: "",
        message: message,
        retry: .never,
        detail: nil,
        sourceChain: [],
        padNonce: nil,
        registrationEventId: nil
    )
}

/// Convert a UniFFI-generated `OutletStreamChunkRecord` to the SDK-
/// shaped `OutletStreamChunk` variant (used by
/// `OutletNamespace.invoke` when streaming-mode is engaged).
func bridgeChunkToSdk(_ raw: OutletStreamChunkRecord) -> OutletStreamChunk {
    let requestId = Data(raw.requestId)
    let payload: OutletStreamChunk.Payload
    switch raw.payloadType {
    case "data":
        payload = .data(value: raw.valueJson ?? "null")
    case "progress":
        payload = .progress(pct: raw.pct ?? 0, note: raw.note)
    case "end":
        payload = .end(
            aggregate: raw.aggregateJson ?? "null",
            executionTimeMs: raw.executionTimeMs ?? 0
        )
    case "error":
        payload = .error(
            code: raw.code ?? "SCP-TOOL-6200",
            message: raw.message ?? "",
            terminal: raw.terminal ?? false
        )
    default:
        // Unknown payload type — synthesize an Error chunk so the
        // pump terminates cleanly instead of stalling.
        payload = .error(
            code: "SCP-TOOL-6200",
            message: "unknown chunk payload type: \(raw.payloadType)",
            terminal: true
        )
    }
    return OutletStreamChunk(
        requestId: requestId,
        sequence: raw.sequence,
        payload: payload
    )
}

// MARK: - Top-level streaming helpers

/// Top-level convenience namespace for the streaming-helper free
/// functions that do not require a `Context`.
public enum OutletsStreaming {
    /// Verifies a chunk's `SCP-OUTLET-CHUNK-SIG-V1:` Ed25519 signature.
    public static func verifyChunkSignature(
        chunkJson: String,
        operatorPk: Data,
        contextId: String,
        outletId: String,
        caveatsBinding: Data
    ) throws -> Bool {
        try SCP.verifyChunkSignature(
            chunkJson: chunkJson,
            operatorPk: operatorPk,
            contextId: contextId,
            outletId: outletId,
            caveatsBinding: caveatsBinding
        )
    }

    /// Recomputes the §5.4.5 `caveats_binding` 32-byte SHA-256 over the
    /// `SCP-OUTLET-CAVEAT-BIND-V1:` preimage.
    public static func computeCaveatsBinding(
        ucanCid: Data,
        requestId: Data,
        invokerDid: String,
        estimatedChunkCount: UInt32,
        effectiveCaveatsJson: String
    ) throws -> Data {
        try SCP.computeCaveatsBinding(
            ucanCid: ucanCid,
            requestId: requestId,
            invokerDid: invokerDid,
            estimatedChunkCount: estimatedChunkCount,
            effectiveCaveatsJson: effectiveCaveatsJson
        )
    }

    /// Signs and applies an `OutletStreamCredit` grant against an active
    /// stream identified by `requestIdHex`. `callerDid` MUST match the
    /// pinned invoker DID at stream open (CRITICAL #1).
    ///
    /// `internal` — the public credit control plane is exclusively
    /// `InvocationHandle.grantCredit(_:)`. This free-function form exists
    /// only for framework-internal call sites that already hold a
    /// `requestIdHex` + pinned `callerDid`.
    @discardableResult
    static func grantCredit(
        requestIdHex: String,
        callerDid: String,
        grant: UInt32
    ) async throws -> UInt32 {
        try await outletStreamGrantCredit(
            requestIdHex: requestIdHex,
            callerDid: callerDid,
            grant: grant
        )
    }

    /// Applies an `OutletCancel` to an active stream by `requestIdHex`.
    /// `callerDid` MUST match the pinned invoker DID. CRITICAL #3 —
    /// `next_seq` is no longer caller-supplied; the bridge derives
    /// the canonical next-emission cursor from runtime state.
    ///
    /// `internal` — the public cancel control plane is exclusively
    /// `InvocationHandle.cancel()`.
    @discardableResult
    static func cancel(
        requestIdHex: String,
        callerDid: String
    ) async throws -> UInt64? {
        try await outletStreamCancel(
            requestIdHex: requestIdHex,
            callerDid: callerDid
        )
    }

    /// Forces a terminal `Error{terminal:true}` chunk into an active
    /// stream (§5.4.5 framework-initiated stream termination).
    ///
    /// `reason` is a closed-set enum mirroring the Rust protocol-layer
    /// `TerminateReason`. The bridge derives the canonical §5.4.4 slug
    /// + code from this value — caller-supplied slug/code strings are
    /// no longer accepted. `messageOverride` is the only caller-
    /// controlled string; pass `nil` to use the spec's canonical
    /// default message.
    ///
    /// `callerDid` MUST match the pinned invoker DID (CRITICAL #1).
    ///
    /// `internal` — used by the framework revocation-recheck loop
    /// (`makeRevocationRecheckTask`) to force-close a stream whose UCAN
    /// was revoked mid-stream. Not part of the public control plane.
    static func terminate(
        requestIdHex: String,
        callerDid: String,
        reason: TerminateReason,
        messageOverride: String?
    ) async throws {
        try await outletStreamTerminate(
            requestIdHex: requestIdHex,
            callerDid: callerDid,
            reason: reason,
            messageOverride: messageOverride
        )
    }
}

/// Module-internal trampoline namespace that calls the UniFFI-generated
/// free functions. Centralised here so the public API can stay stable
/// when UniFFI regenerates bindings.
private enum SCP {
    static func verifyChunkSignature(
        chunkJson: String,
        operatorPk: Data,
        contextId: String,
        outletId: String,
        caveatsBinding: Data
    ) throws -> Bool {
        // `verifyChunkSignature` is a UniFFI free function generated at
        // module scope (in `Internal/ScpBindings.swift`).
        try verifyChunkSignature(
            chunkJson: chunkJson,
            operatorPk: operatorPk,
            contextId: contextId,
            outletId: outletId,
            caveatsBinding: caveatsBinding
        )
    }

    static func computeCaveatsBinding(
        ucanCid: Data,
        requestId: Data,
        invokerDid: String,
        estimatedChunkCount: UInt32,
        effectiveCaveatsJson: String
    ) throws -> Data {
        try computeCaveatsBinding(
            ucanCid: ucanCid,
            requestId: requestId,
            invokerDid: invokerDid,
            estimatedChunkCount: estimatedChunkCount,
            effectiveCaveatsJson: effectiveCaveatsJson
        )
    }
}
