import Foundation

// SCP-OUT-037 (UniFFI portion) — Swift streaming surface.
//
// Wraps the UniFFI-generated `OutletStreamHandle` as an `AsyncSequence`
// so callers can iterate chunks with `for await chunk in stream`. The
// underlying `next()` polling is generated by UniFFI in
// `Internal/ScpBindings.swift`; this file is the pure-Swift ergonomics
// layer (ADR-021 — protocol logic stays in Rust, idioms in the SDK).
//
// UniFFI-generated symbols this file uses (regenerated from
// `crates/scp-ffi/uniffi/src/outlet_stream.rs`):
// - `OutletStreamHandle` — opaque async-iterator class with `next()`
//   and `cancel(nextSeq:)`
// - `OutletStreamChunkRecord` — chunk payload record
// - `OutletStreamSubscriber` — push-style callback interface
// - `outletInvokeStream(...)` — open returns OutletStreamHandle
// - `outletInvokeStreamWithSubscriber(...)` — open + push
// - `outletStreamGrantCredit(requestIdHex:grant:)`
// - `outletStreamCancel(requestIdHex:nextSeq:)`
// - `verifyChunkSignature(chunkJson:operatorPk:contextId:outletId:caveatsBinding:)`
// - `computeCaveatsBinding(ucanCid:requestId:invokerDid:estimatedChunkCount:effectiveCaveatsJson:)`

// MARK: - StreamChunk (Swift-native record)

/// One chunk yielded by ``OutletStreamSequence`` or pushed to a
/// ``OutletStreamSubscriber``. Mirrors the §5.4.5 wire form variant-by-
/// variant — callers branch on `payloadType` and read the variant
/// fields directly.
public struct OutletStreamChunkRecordSwift: Sendable, Equatable {
    /// 16-byte §5.4.5 `request_id` of the stream this chunk belongs to.
    public let requestId: Data
    /// Strictly-monotonic per-stream chunk sequence number.
    public let sequence: UInt64
    /// 64-byte `SCP-OUTLET-CHUNK-SIG-V1:` Ed25519 signature.
    public let sig: Data
    /// One of `"data"` / `"progress"` / `"end"` / `"error"`.
    public let payloadType: String
    public let valueJson: String?
    public let pct: UInt16?
    public let note: String?
    public let aggregateJson: String?
    public let provenanceJson: String?
    public let executionTimeMs: UInt64?
    public let code: String?
    public let message: String?
    public let terminal: Bool?

    public init(from raw: OutletStreamChunkRecord) {
        requestId = Data(raw.requestId)
        sequence = raw.sequence
        sig = Data(raw.sig)
        payloadType = raw.payloadType
        valueJson = raw.valueJson
        pct = raw.pct
        note = raw.note
        aggregateJson = raw.aggregateJson
        provenanceJson = raw.provenanceJson
        executionTimeMs = raw.executionTimeMs
        code = raw.code
        message = raw.message
        terminal = raw.terminal
    }
}

// MARK: - OutletStreamSequence (AsyncSequence wrapper)

/// `AsyncSequence` wrapper around the UniFFI-generated
/// `OutletStreamHandle`. Iteration drives `next()` until the handle
/// reports `done`; subsequent iteration yields no values.
///
/// Construct via ``Context/openOutletStream(outletId:inputJson:ucanToken:caveatsBindingHex:streamEpoch:proofTokens:creditWindow:estimatedChunkCount:)``.
public struct OutletStreamSequence: AsyncSequence, Sendable {
    public typealias Element = OutletStreamChunkRecordSwift
    public typealias AsyncIterator = OutletStreamIterator

    /// The UniFFI handle. `internal` so extensions can call control-plane
    /// operations on the same handle without exposing it publicly.
    let handle: OutletStreamHandle

    public init(handle: OutletStreamHandle) {
        self.handle = handle
    }

    public func makeAsyncIterator() -> OutletStreamIterator {
        OutletStreamIterator(handle: handle)
    }

    /// 32-char lowercase hex `request_id`. Use this to address the stream
    /// from the SDK control-plane methods.
    public var requestIdHex: String {
        handle.requestId()
    }

    /// Returns `true` once a terminal chunk has been observed (or the
    /// receiver has been closed).
    public var isDone: Bool {
        handle.done()
    }

    /// Signs and applies an `OutletStreamCredit` grant for this stream.
    ///
    /// `grant` must be > 0 (round-6 uniform `InvalidGrant` rule).
    /// Returns the new total credit budget on success.
    @discardableResult
    public func grantCredit(_ grant: UInt32) async throws -> UInt32 {
        try await outletStreamGrantCredit(requestIdHex: requestIdHex, grant: grant)
    }

    /// Applies an `OutletCancel` to this stream.
    ///
    /// `nextSeq` is the receiver's view of the next-to-emit chunk
    /// sequence (defaults to `0`).
    @discardableResult
    public func cancel(nextSeq: UInt64? = nil) async throws -> UInt64? {
        try await handle.cancel(nextSeq: nextSeq)
    }
}

/// `AsyncIterator` for `OutletStreamSequence`.
public struct OutletStreamIterator: AsyncIteratorProtocol, Sendable {
    let handle: OutletStreamHandle

    public init(handle: OutletStreamHandle) {
        self.handle = handle
    }

    public mutating func next() async throws -> OutletStreamChunkRecordSwift? {
        guard let raw = try await handle.next() else {
            return nil
        }
        return OutletStreamChunkRecordSwift(from: raw)
    }
}

// MARK: - Context streaming entry points

extension Context {
    /// Internal §5.4.5 streaming entry point. Per SCP-OUT-038 AC1 the
    /// public surface exposes ONLY `ctx.outlets.invoke(...)`; this
    /// helper is `internal` so the SDK's invoke implementation can
    /// open a streaming session without surfacing the verb at the
    /// public API.
    ///
    /// Mirrors the PyO3 / NAPI / Kotlin contracts: re-validates the
    /// UCAN under the full 11-step ADR-016 pipeline, reserves a
    /// per-stream `request_id`, and registers the session for later
    /// `grantCredit` / `cancel` lookups.
    func openOutletStreamSession(
        outletId: String,
        inputJson: String,
        ucanToken: String,
        caveatsBindingHex: String,
        streamEpoch: UInt64,
        proofTokens: [String]? = nil,
        creditWindow: UInt32? = nil,
        estimatedChunkCount: UInt32? = nil
    ) async throws -> OutletStreamSequence {
        let raw = try await outletInvokeStream(
            handle: handle,
            outletId: outletId,
            inputJson: inputJson,
            identity: identity,
            ucanToken: ucanToken,
            caveatsBindingHex: caveatsBindingHex,
            streamEpoch: streamEpoch,
            proofTokens: proofTokens,
            creditWindow: creditWindow,
            estimatedChunkCount: estimatedChunkCount
        )
        return OutletStreamSequence(handle: raw)
    }

    /// Push-style variant of `openOutletStreamSession` — internal per
    /// AC1; routes through the streaming UniFFI export with a caller-
    /// supplied `OutletStreamSubscriber`.
    @discardableResult
    func openOutletStreamSessionWithSubscriber(
        outletId: String,
        inputJson: String,
        ucanToken: String,
        caveatsBindingHex: String,
        streamEpoch: UInt64,
        proofTokens: [String]? = nil,
        creditWindow: UInt32? = nil,
        estimatedChunkCount: UInt32? = nil,
        subscriber: OutletStreamSubscriber
    ) async throws -> String {
        try await outletInvokeStreamWithSubscriber(
            handle: handle,
            outletId: outletId,
            inputJson: inputJson,
            identity: identity,
            ucanToken: ucanToken,
            caveatsBindingHex: caveatsBindingHex,
            streamEpoch: streamEpoch,
            proofTokens: proofTokens,
            creditWindow: creditWindow,
            estimatedChunkCount: estimatedChunkCount,
            subscriber: subscriber
        )
    }
}

/// Spawns the §5.4.5 receiver-side revocation re-check task that
/// runs alongside the streaming pump for the lifetime of the stream.
///
/// Per spec ("Revocation re-check cadence (receiver-side)") the SDK
/// framework MUST periodically re-check the opening UCAN's revocation
/// status during the stream's active lifetime, every
/// `stream_ucan_recheck_secs`, and on observed revocation MUST
/// terminate the stream with `RevokedMidStream` / `SCP-TOOL-6110`.
///
/// Returns the spawned `Task` so the caller (the streaming pump) can
/// cancel it via `defer { recheckTask.cancel() }` when the parent pump
/// resolves naturally — once the stream emits a terminal chunk, the
/// recheck loop has nothing more to do. Spec: "Already-emitted chunks
/// remain authorized; the stream closes at or before
/// `stream_ucan_recheck_secs` after the revocation event regardless of
/// executor behavior."
@Sendable
func makeRevocationRecheckTask(
    contextHandle: ContextHandle,
    outletId: String,
    ucanToken: String,
    proofTokens: [String]?,
    recheckSecs: UInt32,
    requestIdHex: String
) -> Task<Void, Never> {
    Task { [weak contextHandle] in
        guard contextHandle != nil else { return }
        let capability = "tool_invoke:\(outletId)"
        let interval = max(UInt64(1), UInt64(recheckSecs))
        while !Task.isCancelled {
            try? await Task.sleep(nanoseconds: interval * 1_000_000_000)
            if Task.isCancelled { return }
            do {
                guard let ctxHandle = contextHandle else { return }
                try await ucanValidate(
                    handle: ctxHandle,
                    token: ucanToken,
                    capability: capability,
                    presentingAgentDid: nil,
                    proofTokens: proofTokens
                )
            } catch {
                // UCAN no longer valid — terminate the stream with
                // the spec slug + code. Recoverable failures
                // (already terminated / pending) stop the loop
                // naturally because outletStreamTerminate's contract
                // is idempotent on the runtime side.
                _ = try? await OutletStream.terminate(
                    requestIdHex: requestIdHex,
                    slug: "authorization.revoked-mid-stream",
                    code: "SCP-TOOL-6110",
                    message: "ucan revoked or invalid mid-stream"
                )
                return
            }
        }
    }
}

/// Drains an open `OutletStreamHandle` into the InvocationHandle's
/// pump sink. Called by `OutletNamespace.invoke` in streaming mode —
/// kept at module scope so the per-mode helper functions in
/// `Outlets.swift` stay short enough to satisfy SwiftLint's
/// `function_body_length` rule.
///
/// Per OUT-038 AC14 the iterator yields the terminal chunk too: every
/// chunk read from the bridge is forwarded to `yieldChunk` before any
/// terminal-state transition. End resolves the aggregate with the
/// chunk's `aggregate` field; terminal Error{terminal:true} rejects
/// with an `OutletError.execution(...)` envelope.
func pumpStreamingChunks(
    from raw: OutletStreamHandle,
    yieldChunk: @Sendable (OutletStreamChunk) -> Void,
    resolveAggregate: @Sendable (Aggregate) -> Void,
    rejectAggregate: @Sendable (Error) -> Void
) async throws {
    while true {
        guard let bridgeChunk = try await raw.next() else {
            resolveAggregate(Aggregate(valueJson: "null"))
            return
        }
        let sdkChunk = bridgeChunkToSdk(bridgeChunk)
        yieldChunk(sdkChunk)
        switch sdkChunk.payload {
        case let .end(aggregate, executionTimeMs):
            resolveAggregate(Aggregate(
                valueJson: aggregate,
                executionTimeMs: executionTimeMs
            ))
            return
        case let .error(code, message, terminal):
            if terminal {
                let env = OutletEnvelope(
                    classWire: .execution,
                    code: code,
                    slug: code,
                    message: message,
                    retry: .never,
                    detail: nil,
                    sourceChain: [],
                    padNonce: nil,
                    registrationEventId: nil
                )
                rejectAggregate(OutletError.execution(env))
                return
            }
        default:
            break
        }
    }
}

/// Convert a UniFFI-generated `OutletStreamChunkRecord` to the SDK-
/// shaped `OutletStreamChunk` variant (used by
/// `OutletNamespace.invoke` when streaming-mode is engaged).
func bridgeChunkToSdk(_ raw: OutletStreamChunkRecord) -> OutletStreamChunk {
    let requestId = Data(raw.requestId)
    let payload: OutletStreamChunk.Payload
    switch raw.payloadType {
    case "data":
        payload = .data(value: raw.valueJson ?? "null")
    case "progress":
        payload = .progress(pct: raw.pct ?? 0, note: raw.note)
    case "end":
        payload = .end(
            aggregate: raw.aggregateJson ?? "null",
            executionTimeMs: raw.executionTimeMs ?? 0
        )
    case "error":
        payload = .error(
            code: raw.code ?? "SCP-TOOL-6200",
            message: raw.message ?? "",
            terminal: raw.terminal ?? false
        )
    default:
        // Unknown payload type — synthesize an Error chunk so the
        // pump terminates cleanly instead of stalling.
        payload = .error(
            code: "SCP-TOOL-6200",
            message: "unknown chunk payload type: \(raw.payloadType)",
            terminal: true
        )
    }
    return OutletStreamChunk(
        requestId: requestId,
        sequence: raw.sequence,
        payload: payload
    )
}

// MARK: - Top-level streaming helpers

/// Top-level convenience namespace for the streaming-helper free
/// functions that do not require a `Context`.
public enum OutletsStreaming {
    /// Verifies a chunk's `SCP-OUTLET-CHUNK-SIG-V1:` Ed25519 signature.
    public static func verifyChunkSignature(
        chunkJson: String,
        operatorPk: Data,
        contextId: String,
        outletId: String,
        caveatsBinding: Data
    ) throws -> Bool {
        try SCP.verifyChunkSignature(
            chunkJson: chunkJson,
            operatorPk: operatorPk,
            contextId: contextId,
            outletId: outletId,
            caveatsBinding: caveatsBinding
        )
    }

    /// Recomputes the §5.4.5 `caveats_binding` 32-byte SHA-256 over the
    /// `SCP-OUTLET-CAVEAT-BIND-V1:` preimage.
    public static func computeCaveatsBinding(
        ucanCid: Data,
        requestId: Data,
        invokerDid: String,
        estimatedChunkCount: UInt32,
        effectiveCaveatsJson: String
    ) throws -> Data {
        try SCP.computeCaveatsBinding(
            ucanCid: ucanCid,
            requestId: requestId,
            invokerDid: invokerDid,
            estimatedChunkCount: estimatedChunkCount,
            effectiveCaveatsJson: effectiveCaveatsJson
        )
    }

    /// Signs and applies an `OutletStreamCredit` grant against an active
    /// stream identified by `requestIdHex`.
    @discardableResult
    public static func grantCredit(
        requestIdHex: String,
        grant: UInt32
    ) async throws -> UInt32 {
        try await outletStreamGrantCredit(requestIdHex: requestIdHex, grant: grant)
    }

    /// Applies an `OutletCancel` to an active stream by `requestIdHex`.
    @discardableResult
    public static func cancel(
        requestIdHex: String,
        nextSeq: UInt64? = nil
    ) async throws -> UInt64? {
        try await outletStreamCancel(requestIdHex: requestIdHex, nextSeq: nextSeq)
    }

    /// Forces a terminal `Error{terminal:true}` chunk into an active
    /// stream (§5.4.5 receiver-side revocation re-check,
    /// `RevokedMidStream` / `SCP-TOOL-6110`).
    ///
    /// Called by the SDK framework's periodic UCAN re-check loop when
    /// it observes the opening UCAN has been revoked since stream
    /// open. The runtime emits a synthetic terminal Error chunk under
    /// the pinned operator key and runs settlement (admission release,
    /// escrow refund, OutletInvokedEvent emission) identically to
    /// other framework-emitted closes.
    public static func terminate(
        requestIdHex: String,
        slug: String,
        code: String,
        message: String
    ) async throws {
        try await outletStreamTerminate(
            requestIdHex: requestIdHex,
            slug: slug,
            code: code,
            message: message
        )
    }
}

/// Module-internal trampoline namespace that calls the UniFFI-generated
/// free functions. Centralised here so the public API can stay stable
/// when UniFFI regenerates bindings.
private enum SCP {
    static func verifyChunkSignature(
        chunkJson: String,
        operatorPk: Data,
        contextId: String,
        outletId: String,
        caveatsBinding: Data
    ) throws -> Bool {
        // `verifyChunkSignature` is a UniFFI free function generated at
        // module scope (in `Internal/ScpBindings.swift`).
        try verifyChunkSignature(
            chunkJson: chunkJson,
            operatorPk: operatorPk,
            contextId: contextId,
            outletId: outletId,
            caveatsBinding: caveatsBinding
        )
    }

    static func computeCaveatsBinding(
        ucanCid: Data,
        requestId: Data,
        invokerDid: String,
        estimatedChunkCount: UInt32,
        effectiveCaveatsJson: String
    ) throws -> Data {
        try computeCaveatsBinding(
            ucanCid: ucanCid,
            requestId: requestId,
            invokerDid: invokerDid,
            estimatedChunkCount: estimatedChunkCount,
            effectiveCaveatsJson: effectiveCaveatsJson
        )
    }
}
