import Foundation

// ToolDefinition, ToolCostDefinition, and ToolVerificationResult are now defined by UniFFI in ScpBindings.swift.
//
// UniFFI ToolDefinition fields: name, description, inputSchemaJson, outputSchemaJson,
//     operatorDid, testVectorsJson, implementationHash, cost
// UniFFI ToolCostDefinition fields: amount, currency, payee, costFormula
// UniFFI ToolVerificationResult fields: toolId, passed, failures
//
// ToolInvocationResult is a pure Swift type (not in UniFFI) and is kept here.

// MARK: - ToolInvocationResult

/// The result of invoking a tool within an SCP context.
///
/// Contains the tool's output payload and provenance metadata recording which
/// agent invoked the tool, in which context, and when.
///
/// This type is a pure Swift convenience type not generated by UniFFI.
///
/// See `.docs/sketch.md` section 4 "Tools (within a context)".
public nonisolated struct ToolInvocationResult: Sendable {
    /// The serialized output from the tool invocation (JSON).
    public let output: Data

    /// The DID of the agent that invoked the tool.
    public let invokerDid: String

    /// The context ID in which the tool was invoked.
    public let contextId: String

    /// Unix timestamp (milliseconds since epoch) of the invocation.
    public let timestamp: UInt64

    /// Memberwise initializer.
    public init(
        output: Data,
        invokerDid: String,
        contextId: String,
        timestamp: UInt64
    ) {
        self.output = output
        self.invokerDid = invokerDid
        self.contextId = contextId
        self.timestamp = timestamp
    }
}

// MARK: - ToolSessionResult

/// The result of creating a stateful tool session.
///
/// Contains the session ID and metadata needed to invoke the tool within
/// the session.
///
/// See spec section 6.2.1 (Stateful Tool Sessions).
public nonisolated struct ToolSessionResult: Sendable {
    /// The unique session ID (UUID).
    public let sessionId: String

    /// Memberwise initializer.
    public init(sessionId: String) {
        self.sessionId = sessionId
    }
}

// MARK: - ToolBridge

/// Namespace for UniFFI bridge function references used by tool operations.
/// Each typealias maps 1:1 to a UniFFI-generated async function. Closures are
/// injected for testability; defaults call through to ScpBindings.
///
/// See ADR-026 for the flat delegation pattern and ADR-011 for tool spec.
public enum ToolBridge {
    /// Invoke a tool. Maps to ``toolInvoke`` in ScpBindings.
    ///
    /// Tool invocation flows through
    /// `ContextManager::invoke_tool_with_economy` in the Rust runtime
    /// (per-invocation pricing, velocity tracking, escalation, budget,
    /// payment escrow, hard rate limit). The optional ``spendingUcan``
    /// parameter carries a JWT-encoded ``SpendingCapability`` for paid
    /// tool invocations under spec section 19.5 (AND-composition with
    /// the action UCAN). See PR #1606 / C4.
    public typealias InvokeFn = @Sendable (
        _ handle: ContextHandle,
        _ toolId: String,
        _ inputJson: String,
        _ identity: Identity,
        _ ucanToken: String?,
        _ proofTokens: [String]?,
        _ spendingUcan: String?
    ) async throws -> String

    /// Register a tool. Maps to ``toolRegister`` in ScpBindings.
    public typealias RegisterFn = @Sendable (
        _ handle: ContextHandle,
        _ definition: ToolDefinition
    ) async throws -> String

    /// Verify a tool. Maps to ``toolVerify`` in ScpBindings.
    public typealias VerifyFn = @Sendable (
        _ handle: ContextHandle,
        _ toolId: String
    ) async throws -> ToolVerificationResult

    /// Invoke a tool across context boundaries (spec section 6.2).
    public typealias InvokeCrossContextFn = @Sendable (
        _ sourceHandle: ContextHandle,
        _ targetHandle: ContextHandle,
        _ toolId: String,
        _ inputJson: String,
        _ identity: Identity,
        _ ucanToken: String,
        _ chainDepth: UInt8,
        _ proofTokens: [String]?
    ) async throws -> String

    /// Create a stateful tool session (spec section 6.2.1).
    public typealias SessionCreateFn = @Sendable (
        _ handle: ContextHandle,
        _ toolId: String,
        _ sourceContextId: String,
        _ ttlSeconds: UInt64?
    ) async throws -> String

    /// Invoke a tool within an active session.
    public typealias SessionInvokeFn = @Sendable (
        _ handle: ContextHandle,
        _ sessionId: String,
        _ inputJson: String,
        _ identity: Identity,
        _ ucanToken: String,
        _ proofTokens: [String]?
    ) async throws -> String

    /// Close a stateful tool session.
    public typealias SessionCloseFn = @Sendable (
        _ handle: ContextHandle,
        _ sessionId: String
    ) async throws -> Void

    /// Default invoke function — delegates to the process-wide default
    /// ``Scp`` instance's ``Scp/toolInvoke`` method.
    public static let defaultInvoke: InvokeFn = { handle, toolId, inputJson, identity, ucanToken, proofTokens, spendingUcan in
        try await Scp.defaultInstance().toolInvoke(
            handle: handle,
            toolId: toolId,
            inputJson: inputJson,
            identity: identity,
            ucanToken: ucanToken,
            proofTokens: proofTokens,
            spendingUcanJwt: spendingUcan
        )
    }

    /// Default register function — delegates to the process-wide default
    /// ``Scp`` instance's ``Scp/toolRegister(handle:definition:)`` method.
    public static let defaultRegister: RegisterFn = { handle, definition in
        try await Scp.defaultInstance().toolRegister(handle: handle, definition: definition)
    }

    /// Default verify function — delegates to the process-wide default
    /// ``Scp`` instance's ``Scp/toolVerify(handle:toolId:)`` method.
    public static let defaultVerify: VerifyFn = { handle, toolId in
        try await Scp.defaultInstance().toolVerify(handle: handle, toolId: toolId)
    }

    /// Default cross-context invoke function — delegates to the
    /// process-wide default ``Scp`` instance's ``Scp/toolInvokeCrossContext``
    /// method.
    public static let defaultInvokeCrossContext: InvokeCrossContextFn = { sourceHandle, targetHandle, toolId, inputJson, identity, ucanToken, chainDepth, proofTokens in
        try await Scp.defaultInstance().toolInvokeCrossContext(
            sourceHandle: sourceHandle,
            targetHandle: targetHandle,
            toolId: toolId,
            inputJson: inputJson,
            identity: identity,
            ucanToken: ucanToken,
            chainDepth: chainDepth,
            proofTokens: proofTokens
        )
    }

    /// Default session create function — delegates to the process-wide
    /// default ``Scp`` instance's ``Scp/toolSessionCreate`` method.
    public static let defaultSessionCreate: SessionCreateFn = { handle, toolId, sourceContextId, ttlSeconds in
        try await Scp.defaultInstance().toolSessionCreate(
            handle: handle,
            toolId: toolId,
            sourceContextId: sourceContextId,
            ttlSeconds: ttlSeconds
        )
    }

    /// Default session invoke function — delegates to the process-wide
    /// default ``Scp`` instance's ``Scp/toolSessionInvoke`` method.
    public static let defaultSessionInvoke: SessionInvokeFn = { handle, sessionId, inputJson, identity, ucanToken, proofTokens in
        try await Scp.defaultInstance().toolSessionInvoke(
            handle: handle,
            sessionId: sessionId,
            inputJson: inputJson,
            identity: identity,
            ucanToken: ucanToken,
            proofTokens: proofTokens
        )
    }

    /// Default session close function — delegates to the process-wide
    /// default ``Scp`` instance's
    /// ``Scp/toolSessionClose(handle:sessionId:)`` method.
    public static let defaultSessionClose: SessionCloseFn = { handle, sessionId in
        try await Scp.defaultInstance().toolSessionClose(handle: handle, sessionId: sessionId)
    }

    /// Expose a tool interface for cross-context sharing. Maps to ``toolInterfaceExpose`` in ScpBindings.
    public typealias InterfaceExposeFn = @Sendable (
        _ handle: ContextHandle,
        _ toolId: String,
        _ targetContextId: String,
        _ rateLimitJson: String?
    ) async throws -> String

    /// Accept a cross-context tool interface. Maps to ``toolInterfaceAccept`` in ScpBindings.
    public typealias InterfaceAcceptFn = @Sendable (
        _ handle: ContextHandle,
        _ interfaceJson: String
    ) async throws -> String

    /// Revoke a cross-context tool interface. Maps to ``toolInterfaceRevoke`` in ScpBindings.
    public typealias InterfaceRevokeFn = @Sendable (
        _ handle: ContextHandle,
        _ interfaceIdHex: String
    ) async throws -> String

    /// Default interface expose function — delegates to the process-wide
    /// default ``Scp`` instance's ``Scp/toolInterfaceExpose`` method.
    public static let defaultInterfaceExpose: InterfaceExposeFn = { handle, toolId, targetContextId, rateLimitJson in
        try await Scp.defaultInstance().toolInterfaceExpose(
            handle: handle,
            toolId: toolId,
            targetContextId: targetContextId,
            rateLimitJson: rateLimitJson
        )
    }

    /// Default interface accept function — delegates to the process-wide
    /// default ``Scp`` instance's
    /// ``Scp/toolInterfaceAccept(handle:interfaceJson:)`` method.
    public static let defaultInterfaceAccept: InterfaceAcceptFn = { handle, interfaceJson in
        try await Scp.defaultInstance().toolInterfaceAccept(handle: handle, interfaceJson: interfaceJson)
    }

    /// Default interface revoke function — delegates to the process-wide
    /// default ``Scp`` instance's
    /// ``Scp/toolInterfaceRevoke(handle:interfaceIdHex:)`` method.
    public static let defaultInterfaceRevoke: InterfaceRevokeFn = { handle, interfaceIdHex in
        try await Scp.defaultInstance().toolInterfaceRevoke(handle: handle, interfaceIdHex: interfaceIdHex)
    }
}

// MARK: - Context Tool Extensions

/// Tool invocation and management extensions for ``Context``.
public extension Context {
    /// Invokes a registered tool in this context.
    ///
    /// Delegates to the UniFFI ``toolInvoke`` bridge function. The input Data
    /// is converted to a UTF-8 JSON string for the bridge call, and the output
    /// JSON string is wrapped in a ``ToolInvocationResult`` with provenance.
    ///
    /// - Parameters:
    ///   - tool: The name of the tool to invoke.
    ///   - input: The tool input as serialized JSON data.
    ///   - identity: The ``Identity`` of the invoking agent.
    ///   - invokeFn: Bridge function override for testing.
    /// - Returns: A ``ToolInvocationResult`` containing the tool's output and
    ///   provenance metadata.
    /// - Throws: ``ScpError/Tool(msg:code:)`` if the tool is not found,
    ///   the input fails schema validation, or the invocation is unauthorized.
    ///   ``ScpError/Context(msg:code:)`` if the context is not active.
    ///
    /// ## Provenance
    ///
    /// - ADR-011 (Event Log) in `.docs/adrs/phase-2.md`
    /// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
    /// - Story SCP-221
    func invokeTool(
        _ tool: String,
        input: Data,
        identity: Identity,
        ucanToken: String? = nil,
        proofTokens: [String]? = nil,
        spendingUcan: String? = nil,
        invokerDid: String? = nil,
        invokeFn: ToolBridge.InvokeFn = ToolBridge.defaultInvoke
    ) async throws -> ToolInvocationResult {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        guard let inputJson = String(data: input, encoding: .utf8) else {
            throw ScpError.Tool(
                msg: "Tool input is not valid UTF-8",
                code: "SCP-TOOL-6001"
            )
        }
        let outputJson = try await invokeFn(
            handle, tool, inputJson, identity, ucanToken, proofTokens, spendingUcan
        )
        return ToolInvocationResult(
            output: Data(outputJson.utf8),
            invokerDid: invokerDid ?? identity.did(),
            contextId: contextId,
            timestamp: UInt64(Date().timeIntervalSince1970 * 1000)
        )
    }

    /// Registers a tool in this context.
    ///
    /// Delegates to the UniFFI ``toolRegister`` bridge function.
    ///
    /// - Parameters:
    ///   - definition: The ``ToolDefinition`` describing the tool.
    ///   - registerFn: Bridge function override for testing.
    /// - Returns: The assigned tool identifier.
    /// - Throws: ``ScpError/Tool(msg:code:)`` if registration fails.
    ///   ``ScpError/Context(msg:code:)`` if the context is not active.
    ///
    /// ## Provenance
    ///
    /// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
    /// - Story SCP-221
    func registerTool(
        _ definition: ToolDefinition,
        registerFn: ToolBridge.RegisterFn = ToolBridge.defaultRegister
    ) async throws -> String {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        return try await registerFn(handle, definition)
    }

    /// Verifies a tool against its registered test vectors.
    ///
    /// Delegates to the UniFFI ``toolVerify`` bridge function.
    ///
    /// - Parameters:
    ///   - tool: The name of the tool to verify.
    ///   - verifyFn: Bridge function override for testing.
    /// - Returns: A ``ToolVerificationResult`` describing the outcome.
    /// - Throws: ``ScpError/Tool(msg:code:)`` if the tool is not found
    ///   or verification fails. ``ScpError/Context(msg:code:)`` if the
    ///   context is not active.
    ///
    /// ## Provenance
    ///
    /// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
    /// - Story SCP-221
    func verifyTool(
        _ tool: String,
        verifyFn: ToolBridge.VerifyFn = ToolBridge.defaultVerify
    ) async throws -> ToolVerificationResult {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        return try await verifyFn(handle, tool)
    }

    /// Invokes a tool registered in a different context (cross-context).
    ///
    /// Delegates to the UniFFI ``toolInvokeCrossContext`` bridge function.
    /// Requires bidirectional consent: the source context must allow outbound
    /// tool calls and the target context must allow inbound tool calls.
    /// Chain depth is enforced (max 3 hops per spec section 6.2).
    ///
    /// - Parameters:
    ///   - tool: The tool ID to invoke in the target context.
    ///   - input: The tool input as serialized JSON data.
    ///   - identity: The ``Identity`` of the invoking agent.
    ///   - targetContext: The ``Context`` containing the target tool.
    ///   - chainDepth: Current chain depth (0 for direct invocation).
    ///   - invokeCrossContextFn: Bridge function override for testing.
    /// - Returns: A ``ToolInvocationResult`` containing the tool's output
    ///   and provenance metadata.
    /// - Throws: ``ScpError/Tool(msg:code:)`` if the tool is not found,
    ///   chain depth exceeds the limit, or consent is denied.
    ///   ``ScpError/Context(msg:code:)`` if either context is not active.
    ///
    /// ## Provenance
    ///
    /// - Spec section 6.2 (Cross-Context Tool Interfaces)
    /// - Story #322
    func invokeToolCrossContext(
        _ tool: String,
        input: Data,
        identity: Identity,
        targetContext: Context,
        ucanToken: String,
        chainDepth: UInt8 = 0,
        proofTokens: [String]? = nil,
        invokerDid: String? = nil,
        invokeCrossContextFn: ToolBridge.InvokeCrossContextFn = ToolBridge.defaultInvokeCrossContext
    ) async throws -> ToolInvocationResult {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Source context is not active",
                code: "SCP-CTX-2001"
            )
        }
        guard let inputJson = String(data: input, encoding: .utf8) else {
            throw ScpError.Tool(
                msg: "Tool input is not valid UTF-8",
                code: "SCP-TOOL-6001"
            )
        }
        let targetHandle = await targetContext.handle
        let outputJson = try await invokeCrossContextFn(
            handle, targetHandle, tool, inputJson, identity, ucanToken, chainDepth, proofTokens
        )
        return ToolInvocationResult(
            output: Data(outputJson.utf8),
            invokerDid: invokerDid ?? identity.did(),
            contextId: contextId,
            timestamp: UInt64(Date().timeIntervalSince1970 * 1000)
        )
    }

    /// Creates a stateful tool session for repeated invocations.
    ///
    /// Delegates to the UniFFI ``toolSessionCreate`` bridge function.
    /// Sessions have an optional TTL and a per-caller cap (default 1000, ADR-043).
    ///
    /// - Parameters:
    ///   - toolId: The tool ID to create a session for.
    ///   - sourceContextId: The context ID of the calling context.
    ///   - ttlSeconds: Time-to-live for the session in seconds, or `nil` for
    ///     a session that persists for the lifetime of the context (spec section 6.2.1).
    ///   - sessionCreateFn: Bridge function override for testing.
    /// - Returns: A ``ToolSessionResult`` containing the session ID.
    /// - Throws: ``ScpError/Tool(msg:code:)`` if session creation fails.
    ///   ``ScpError/Context(msg:code:)`` if the context is not active.
    ///
    /// ## Provenance
    ///
    /// - Spec section 6.2.1 (Stateful Tool Sessions)
    /// - Story #322
    func createToolSession(
        toolId: String,
        sourceContextId: String,
        ttlSeconds: UInt64? = nil,
        sessionCreateFn: ToolBridge.SessionCreateFn = ToolBridge.defaultSessionCreate
    ) async throws -> ToolSessionResult {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        let sessionId = try await sessionCreateFn(
            handle, toolId, sourceContextId, ttlSeconds
        )
        return ToolSessionResult(sessionId: sessionId)
    }

    /// Invokes a tool within an active session.
    ///
    /// Delegates to the UniFFI ``toolSessionInvoke`` bridge function.
    /// Each invocation increments the session call count and checks
    /// TTL expiry.
    ///
    /// - Parameters:
    ///   - sessionId: The session ID from ``createToolSession``.
    ///   - input: The tool input as serialized JSON data.
    ///   - identity: The ``Identity`` of the invoking agent.
    ///   - sessionInvokeFn: Bridge function override for testing.
    /// - Returns: A ``ToolInvocationResult`` containing the tool's output.
    /// - Throws: ``ScpError/Tool(msg:code:)`` if the session is expired
    ///   or not found. ``ScpError/Context(msg:code:)`` if the context
    ///   is not active.
    ///
    /// ## Provenance
    ///
    /// - Spec section 6.2.1 (Stateful Tool Sessions)
    /// - Story #322
    func invokeToolSession(
        sessionId: String,
        input: Data,
        identity: Identity,
        ucanToken: String,
        proofTokens: [String]? = nil,
        invokerDid: String? = nil,
        sessionInvokeFn: ToolBridge.SessionInvokeFn = ToolBridge.defaultSessionInvoke
    ) async throws -> ToolInvocationResult {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        guard let inputJson = String(data: input, encoding: .utf8) else {
            throw ScpError.Tool(
                msg: "Tool input is not valid UTF-8",
                code: "SCP-TOOL-6001"
            )
        }
        let outputJson = try await sessionInvokeFn(
            handle, sessionId, inputJson, identity, ucanToken, proofTokens
        )
        return ToolInvocationResult(
            output: Data(outputJson.utf8),
            invokerDid: invokerDid ?? identity.did(),
            contextId: contextId,
            timestamp: UInt64(Date().timeIntervalSince1970 * 1000)
        )
    }

    /// Closes a stateful tool session.
    ///
    /// Delegates to the UniFFI ``toolSessionClose`` bridge function.
    /// The session is removed and can no longer be invoked.
    ///
    /// - Parameters:
    ///   - sessionId: The session ID to close.
    ///   - sessionCloseFn: Bridge function override for testing.
    /// - Throws: ``ScpError/Tool(msg:code:)`` if the session is not
    ///   found. ``ScpError/Context(msg:code:)`` if the context is
    ///   not active.
    ///
    /// ## Provenance
    ///
    /// - Spec section 6.2.1 (Stateful Tool Sessions)
    /// - Story #322
    func closeToolSession(
        sessionId: String,
        sessionCloseFn: ToolBridge.SessionCloseFn = ToolBridge.defaultSessionClose
    ) async throws {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        try await sessionCloseFn(handle, sessionId)
    }

    // MARK: - Bidirectional Consent Protocol (§6.2.0.1)

    /// Exposes a tool interface for cross-context sharing (step 1).
    ///
    /// The caller (admin of the source context) proposes sharing a specific
    /// tool with a target context.
    ///
    /// - Parameters:
    ///   - toolId: The ID of the tool to expose.
    ///   - targetContextId: The target context to expose the tool to.
    ///   - rateLimitJson: Optional per-interface rate limit as a JSON string.
    ///   - interfaceExposeFn: Bridge function override for testing.
    /// - Returns: The ``ToolInterface`` as a JSON string.
    /// - Throws: ``ScpError/Tool(msg:code:)`` if the caller is not an admin
    ///   or the tool is not found.
    func exposeToolInterface(
        toolId: String,
        targetContextId: String,
        rateLimitJson: String? = nil,
        interfaceExposeFn: ToolBridge.InterfaceExposeFn = ToolBridge.defaultInterfaceExpose
    ) async throws -> String {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        return try await interfaceExposeFn(handle, toolId, targetContextId, rateLimitJson)
    }

    /// Accepts a cross-context tool interface (step 4).
    ///
    /// Sets `approved_by_target = true` on the interface.
    ///
    /// - Parameters:
    ///   - interfaceJson: The ``ToolInterface`` JSON string to accept.
    ///   - interfaceAcceptFn: Bridge function override for testing.
    /// - Returns: The updated ``ToolInterface`` as a JSON string.
    /// - Throws: ``ScpError/Tool(msg:code:)`` if the caller is not an admin
    ///   or context mismatch.
    func acceptToolInterface(
        interfaceJson: String,
        interfaceAcceptFn: ToolBridge.InterfaceAcceptFn = ToolBridge.defaultInterfaceAccept
    ) async throws -> String {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        return try await interfaceAcceptFn(handle, interfaceJson)
    }

    /// Revokes a cross-context tool interface (step 5).
    ///
    /// Either context may revoke unilaterally.
    ///
    /// - Parameters:
    ///   - interfaceIdHex: The 32-byte interface/offer ID as a hex string.
    ///   - interfaceRevokeFn: Bridge function override for testing.
    /// - Returns: The ``InterfaceRevoked`` event as a JSON string.
    /// - Throws: ``ScpError/Validation(msg:code:)`` if the hex ID is invalid.
    func revokeToolInterface(
        interfaceIdHex: String,
        interfaceRevokeFn: ToolBridge.InterfaceRevokeFn = ToolBridge.defaultInterfaceRevoke
    ) async throws -> String {
        guard state == .active else {
            throw ScpError.Context(
                msg: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        return try await interfaceRevokeFn(handle, interfaceIdHex)
    }
}
