import Foundation

// ToolDefinition and ToolVerificationResult are now defined by UniFFI in ScpBindings.swift.
//
// UniFFI ToolDefinition fields: name, description, inputSchemaJson, outputSchemaJson,
//     operatorDid, testVectorsJson, implementationHash
// UniFFI ToolVerificationResult fields: toolId, passed, failures
//
// ToolInvocationResult is a pure Swift type (not in UniFFI) and is kept here.

// MARK: - ToolInvocationResult

/// The result of invoking a tool within an SCP context.
///
/// Contains the tool's output payload and provenance metadata recording which
/// agent invoked the tool, in which context, and when.
///
/// This type is a pure Swift convenience type not generated by UniFFI.
///
/// See `.docs/sketch.md` section 4 "Tools (within a context)".
public nonisolated struct ToolInvocationResult: Sendable {
    /// The serialized output from the tool invocation (JSON).
    public let output: Data

    /// The DID of the agent that invoked the tool.
    public let invokerDid: String

    /// The context ID in which the tool was invoked.
    public let contextId: String

    /// Unix timestamp (milliseconds since epoch) of the invocation.
    public let timestamp: UInt64

    /// Memberwise initializer.
    public init(
        output: Data,
        invokerDid: String,
        contextId: String,
        timestamp: UInt64
    ) {
        self.output = output
        self.invokerDid = invokerDid
        self.contextId = contextId
        self.timestamp = timestamp
    }
}

// MARK: - ToolSessionResult

/// The result of creating a stateful tool session.
///
/// Contains the session ID and metadata needed to invoke the tool within
/// the session.
///
/// See spec section 6.2.1 (Stateful Tool Sessions).
public nonisolated struct ToolSessionResult: Sendable {
    /// The unique session ID (UUID).
    public let sessionId: String

    /// Memberwise initializer.
    public init(sessionId: String) {
        self.sessionId = sessionId
    }
}

// MARK: - ToolBridge

/// Namespace for UniFFI bridge function references used by tool operations.
/// Each typealias maps 1:1 to a UniFFI-generated async function. Closures are
/// injected for testability; defaults call through to ScpBindings.
///
/// See ADR-026 for the flat delegation pattern and ADR-011 for tool spec.
internal enum ToolBridge {
    /// Invoke a tool. Maps to ``toolInvoke`` in ScpBindings.
    internal typealias InvokeFn = @Sendable (
        _ handle: ContextHandle,
        _ toolId: String,
        _ inputJson: String,
        _ identity: Identity
    ) async throws -> String

    /// Register a tool. Maps to ``toolRegister`` in ScpBindings.
    internal typealias RegisterFn = @Sendable (
        _ handle: ContextHandle,
        _ definition: ToolDefinition
    ) async throws -> String

    /// Verify a tool. Maps to ``toolVerify`` in ScpBindings.
    internal typealias VerifyFn = @Sendable (
        _ handle: ContextHandle,
        _ toolId: String
    ) async throws -> ToolVerificationResult

    /// Invoke a tool across context boundaries (spec section 6.2).
    internal typealias InvokeCrossContextFn = @Sendable (
        _ sourceHandle: ContextHandle,
        _ targetHandle: ContextHandle,
        _ toolId: String,
        _ inputJson: String,
        _ identity: Identity,
        _ chainDepth: UInt8
    ) async throws -> String

    /// Create a stateful tool session (spec section 6.2.1).
    internal typealias SessionCreateFn = @Sendable (
        _ handle: ContextHandle,
        _ toolId: String,
        _ sourceContextId: String,
        _ ttlSeconds: UInt64
    ) async throws -> String

    /// Invoke a tool within an active session.
    internal typealias SessionInvokeFn = @Sendable (
        _ handle: ContextHandle,
        _ sessionId: String,
        _ inputJson: String,
        _ identity: Identity
    ) async throws -> String

    /// Close a stateful tool session.
    internal typealias SessionCloseFn = @Sendable (
        _ handle: ContextHandle,
        _ sessionId: String
    ) async throws -> Void

    /// Default invoke function that delegates to the UniFFI-generated binding.
    internal static let defaultInvoke: InvokeFn = { handle, toolId, inputJson, identity in
        try await toolInvoke(handle: handle, toolId: toolId, inputJson: inputJson, identity: identity)
    }

    /// Default register function that delegates to the UniFFI-generated binding.
    internal static let defaultRegister: RegisterFn = { handle, definition in
        try await toolRegister(handle: handle, definition: definition)
    }

    /// Default verify function that delegates to the UniFFI-generated binding.
    internal static let defaultVerify: VerifyFn = { handle, toolId in
        try await toolVerify(handle: handle, toolId: toolId)
    }

    /// Default cross-context invoke function — delegates to UniFFI.
    internal static let defaultInvokeCrossContext: InvokeCrossContextFn = {
        sourceHandle, targetHandle, toolId, inputJson, identity, chainDepth in
        try await toolInvokeCrossContext(
            sourceHandle: sourceHandle,
            targetHandle: targetHandle,
            toolId: toolId,
            inputJson: inputJson,
            identity: identity,
            chainDepth: chainDepth
        )
    }

    /// Default session create function — delegates to UniFFI.
    internal static let defaultSessionCreate: SessionCreateFn = {
        handle, toolId, sourceContextId, ttlSeconds in
        try await toolSessionCreate(
            handle: handle,
            toolId: toolId,
            sourceContextId: sourceContextId,
            ttlSeconds: ttlSeconds
        )
    }

    /// Default session invoke function — delegates to UniFFI.
    internal static let defaultSessionInvoke: SessionInvokeFn = {
        handle, sessionId, inputJson, identity in
        try await toolSessionInvoke(
            handle: handle,
            sessionId: sessionId,
            inputJson: inputJson,
            identity: identity
        )
    }

    /// Default session close function — delegates to UniFFI.
    internal static let defaultSessionClose: SessionCloseFn = { handle, sessionId in
        try await toolSessionClose(handle: handle, sessionId: sessionId)
    }
}

// MARK: - Context Tool Extensions

/// Tool invocation and management extensions for ``Context``.
extension Context {

    /// Invokes a registered tool in this context.
    ///
    /// Delegates to the UniFFI ``toolInvoke`` bridge function. The input Data
    /// is converted to a UTF-8 JSON string for the bridge call, and the output
    /// JSON string is wrapped in a ``ToolInvocationResult`` with provenance.
    ///
    /// - Parameters:
    ///   - tool: The name of the tool to invoke.
    ///   - input: The tool input as serialized JSON data.
    ///   - invokeFn: Bridge function override for testing.
    /// - Returns: A ``ToolInvocationResult`` containing the tool's output and
    ///   provenance metadata.
    /// - Throws: ``ScpError/Tool(message:code:)`` if the tool is not found,
    ///   the input fails schema validation, or the invocation is unauthorized.
    ///   ``ScpError/Context(message:code:)`` if the context is not active.
    ///
    /// ## Provenance
    ///
    /// - ADR-011 (Event Log) in `.docs/adrs/phase-2.md`
    /// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
    /// - Story SCP-221
    public func invokeTool(
        _ tool: String,
        input: Data,
        invokeFn: ToolBridge.InvokeFn = ToolBridge.defaultInvoke
    ) async throws -> ToolInvocationResult {
        guard state == .active else {
            throw ScpError.Context(
                message: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        guard let contextHandle = handle as? ContextHandle else {
            throw ScpError.Context(
                message: "Context handle is not a UniFFI ContextHandle",
                code: "SCP-CTX-2002"
            )
        }
        let inputJson = String(data: input, encoding: .utf8) ?? "{}"
        let identity = Identity(noPointer: .init())
        let outputJson = try await invokeFn(contextHandle, tool, inputJson, identity)
        return ToolInvocationResult(
            output: Data(outputJson.utf8),
            invokerDid: "",
            contextId: contextId,
            timestamp: UInt64(Date().timeIntervalSince1970 * 1_000)
        )
    }

    /// Registers a tool in this context.
    ///
    /// Delegates to the UniFFI ``toolRegister`` bridge function.
    ///
    /// - Parameters:
    ///   - definition: The ``ToolDefinition`` describing the tool.
    ///   - registerFn: Bridge function override for testing.
    /// - Returns: The assigned tool identifier.
    /// - Throws: ``ScpError/Tool(message:code:)`` if registration fails.
    ///   ``ScpError/Context(message:code:)`` if the context is not active.
    ///
    /// ## Provenance
    ///
    /// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
    /// - Story SCP-221
    public func registerTool(
        _ definition: ToolDefinition,
        registerFn: ToolBridge.RegisterFn = ToolBridge.defaultRegister
    ) async throws -> String {
        guard state == .active else {
            throw ScpError.Context(
                message: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        guard let contextHandle = handle as? ContextHandle else {
            throw ScpError.Context(
                message: "Context handle is not a UniFFI ContextHandle",
                code: "SCP-CTX-2002"
            )
        }
        return try await registerFn(contextHandle, definition)
    }

    /// Verifies a tool against its registered test vectors.
    ///
    /// Delegates to the UniFFI ``toolVerify`` bridge function.
    ///
    /// - Parameters:
    ///   - tool: The name of the tool to verify.
    ///   - verifyFn: Bridge function override for testing.
    /// - Returns: A ``ToolVerificationResult`` describing the outcome.
    /// - Throws: ``ScpError/Tool(message:code:)`` if the tool is not found
    ///   or verification fails. ``ScpError/Context(message:code:)`` if the
    ///   context is not active.
    ///
    /// ## Provenance
    ///
    /// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
    /// - Story SCP-221
    public func verifyTool(
        _ tool: String,
        verifyFn: ToolBridge.VerifyFn = ToolBridge.defaultVerify
    ) async throws -> ToolVerificationResult {
        guard state == .active else {
            throw ScpError.Context(
                message: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        guard let contextHandle = handle as? ContextHandle else {
            throw ScpError.Context(
                message: "Context handle is not a UniFFI ContextHandle",
                code: "SCP-CTX-2002"
            )
        }
        return try await verifyFn(contextHandle, tool)
    }

    /// Invokes a tool registered in a different context (cross-context).
    ///
    /// Delegates to the UniFFI ``toolInvokeCrossContext`` bridge function.
    /// Requires bidirectional consent: the source context must allow outbound
    /// tool calls and the target context must allow inbound tool calls.
    /// Chain depth is enforced (max 3 hops per spec section 6.2).
    ///
    /// - Parameters:
    ///   - tool: The tool ID to invoke in the target context.
    ///   - input: The tool input as serialized JSON data.
    ///   - targetContext: The ``Context`` containing the target tool.
    ///   - chainDepth: Current chain depth (0 for direct invocation).
    ///   - invokeCrossContextFn: Bridge function override for testing.
    /// - Returns: A ``ToolInvocationResult`` containing the tool's output
    ///   and provenance metadata.
    /// - Throws: ``ScpError/Tool(message:code:)`` if the tool is not found,
    ///   chain depth exceeds the limit, or consent is denied.
    ///   ``ScpError/Context(message:code:)`` if either context is not active.
    ///
    /// ## Provenance
    ///
    /// - Spec section 6.2 (Cross-Context Tool Interfaces)
    /// - Story #322
    public func invokeToolCrossContext(
        _ tool: String,
        input: Data,
        targetContext: Context,
        chainDepth: UInt8 = 0,
        invokeCrossContextFn: ToolBridge.InvokeCrossContextFn = ToolBridge.defaultInvokeCrossContext
    ) async throws -> ToolInvocationResult {
        guard state == .active else {
            throw ScpError.Context(
                message: "Source context is not active",
                code: "SCP-CTX-2001"
            )
        }
        guard let sourceHandle = handle as? ContextHandle else {
            throw ScpError.Context(
                message: "Source context handle is not a UniFFI ContextHandle",
                code: "SCP-CTX-2002"
            )
        }
        guard let targetHandle = targetContext.handle as? ContextHandle else {
            throw ScpError.Context(
                message: "Target context handle is not a UniFFI ContextHandle",
                code: "SCP-CTX-2002"
            )
        }
        let inputJson = String(data: input, encoding: .utf8) ?? "{}"
        let identity = Identity(noPointer: .init())
        let outputJson = try await invokeCrossContextFn(
            sourceHandle, targetHandle, tool, inputJson, identity, chainDepth
        )
        return ToolInvocationResult(
            output: Data(outputJson.utf8),
            invokerDid: "",
            contextId: contextId,
            timestamp: UInt64(Date().timeIntervalSince1970 * 1_000)
        )
    }

    /// Creates a stateful tool session for repeated invocations.
    ///
    /// Delegates to the UniFFI ``toolSessionCreate`` bridge function.
    /// Sessions have a TTL and a per-caller cap (5 concurrent).
    ///
    /// - Parameters:
    ///   - toolId: The tool ID to create a session for.
    ///   - sourceContextId: The context ID of the calling context.
    ///   - ttlSeconds: Time-to-live for the session in seconds.
    ///   - sessionCreateFn: Bridge function override for testing.
    /// - Returns: A ``ToolSessionResult`` containing the session ID.
    /// - Throws: ``ScpError/Tool(message:code:)`` if session creation fails.
    ///   ``ScpError/Context(message:code:)`` if the context is not active.
    ///
    /// ## Provenance
    ///
    /// - Spec section 6.2.1 (Stateful Tool Sessions)
    /// - Story #322
    public func createToolSession(
        toolId: String,
        sourceContextId: String,
        ttlSeconds: UInt64,
        sessionCreateFn: ToolBridge.SessionCreateFn = ToolBridge.defaultSessionCreate
    ) async throws -> ToolSessionResult {
        guard state == .active else {
            throw ScpError.Context(
                message: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        guard let contextHandle = handle as? ContextHandle else {
            throw ScpError.Context(
                message: "Context handle is not a UniFFI ContextHandle",
                code: "SCP-CTX-2002"
            )
        }
        let sessionId = try await sessionCreateFn(
            contextHandle, toolId, sourceContextId, ttlSeconds
        )
        return ToolSessionResult(sessionId: sessionId)
    }

    /// Invokes a tool within an active session.
    ///
    /// Delegates to the UniFFI ``toolSessionInvoke`` bridge function.
    /// Each invocation increments the session call count and checks
    /// TTL expiry.
    ///
    /// - Parameters:
    ///   - sessionId: The session ID from ``createToolSession``.
    ///   - input: The tool input as serialized JSON data.
    ///   - sessionInvokeFn: Bridge function override for testing.
    /// - Returns: A ``ToolInvocationResult`` containing the tool's output.
    /// - Throws: ``ScpError/Tool(message:code:)`` if the session is expired
    ///   or not found. ``ScpError/Context(message:code:)`` if the context
    ///   is not active.
    ///
    /// ## Provenance
    ///
    /// - Spec section 6.2.1 (Stateful Tool Sessions)
    /// - Story #322
    public func invokeToolSession(
        sessionId: String,
        input: Data,
        sessionInvokeFn: ToolBridge.SessionInvokeFn = ToolBridge.defaultSessionInvoke
    ) async throws -> ToolInvocationResult {
        guard state == .active else {
            throw ScpError.Context(
                message: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        guard let contextHandle = handle as? ContextHandle else {
            throw ScpError.Context(
                message: "Context handle is not a UniFFI ContextHandle",
                code: "SCP-CTX-2002"
            )
        }
        let inputJson = String(data: input, encoding: .utf8) ?? "{}"
        let identity = Identity(noPointer: .init())
        let outputJson = try await sessionInvokeFn(
            contextHandle, sessionId, inputJson, identity
        )
        return ToolInvocationResult(
            output: Data(outputJson.utf8),
            invokerDid: "",
            contextId: contextId,
            timestamp: UInt64(Date().timeIntervalSince1970 * 1_000)
        )
    }

    /// Closes a stateful tool session.
    ///
    /// Delegates to the UniFFI ``toolSessionClose`` bridge function.
    /// The session is removed and can no longer be invoked.
    ///
    /// - Parameters:
    ///   - sessionId: The session ID to close.
    ///   - sessionCloseFn: Bridge function override for testing.
    /// - Throws: ``ScpError/Tool(message:code:)`` if the session is not
    ///   found. ``ScpError/Context(message:code:)`` if the context is
    ///   not active.
    ///
    /// ## Provenance
    ///
    /// - Spec section 6.2.1 (Stateful Tool Sessions)
    /// - Story #322
    public func closeToolSession(
        sessionId: String,
        sessionCloseFn: ToolBridge.SessionCloseFn = ToolBridge.defaultSessionClose
    ) async throws {
        guard state == .active else {
            throw ScpError.Context(
                message: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        guard let contextHandle = handle as? ContextHandle else {
            throw ScpError.Context(
                message: "Context handle is not a UniFFI ContextHandle",
                code: "SCP-CTX-2002"
            )
        }
        try await sessionCloseFn(contextHandle, sessionId)
    }
}
