import Foundation

// ToolDefinition and ToolVerificationResult are now defined by UniFFI in ScpBindings.swift.
//
// UniFFI ToolDefinition fields: name, description, inputSchemaJson, outputSchemaJson,
//     operatorDid, testVectorsJson, implementationHash
// UniFFI ToolVerificationResult fields: toolId, passed, failures
//
// ToolInvocationResult is a pure Swift type (not in UniFFI) and is kept here.

// MARK: - ToolInvocationResult

/// The result of invoking a tool within an SCP context.
///
/// Contains the tool's output payload and provenance metadata recording which
/// agent invoked the tool, in which context, and when.
///
/// This type is a pure Swift convenience type not generated by UniFFI.
///
/// See `.docs/sketch.md` section 4 "Tools (within a context)".
public nonisolated struct ToolInvocationResult: Sendable {
    /// The serialized output from the tool invocation (JSON).
    public let output: Data

    /// The DID of the agent that invoked the tool.
    public let invokerDid: String

    /// The context ID in which the tool was invoked.
    public let contextId: String

    /// Unix timestamp (milliseconds since epoch) of the invocation.
    public let timestamp: UInt64

    /// Memberwise initializer.
    public init(
        output: Data,
        invokerDid: String,
        contextId: String,
        timestamp: UInt64
    ) {
        self.output = output
        self.invokerDid = invokerDid
        self.contextId = contextId
        self.timestamp = timestamp
    }
}

// MARK: - ToolBridge

/// Namespace for UniFFI bridge function references used by tool operations.
/// Each typealias maps 1:1 to a UniFFI-generated async function. Closures are
/// injected for testability; defaults call through to ScpBindings.
///
/// See ADR-026 for the flat delegation pattern and ADR-011 for tool spec.
internal enum ToolBridge {
    /// Invoke a tool. Maps to ``toolInvoke`` in ScpBindings.
    internal typealias InvokeFn = @Sendable (
        _ handle: ContextHandle,
        _ toolId: String,
        _ inputJson: String,
        _ identity: Identity
    ) async throws -> String

    /// Register a tool. Maps to ``toolRegister`` in ScpBindings.
    internal typealias RegisterFn = @Sendable (
        _ handle: ContextHandle,
        _ definition: ToolDefinition
    ) async throws -> String

    /// Verify a tool. Maps to ``toolVerify`` in ScpBindings.
    internal typealias VerifyFn = @Sendable (
        _ handle: ContextHandle,
        _ toolId: String
    ) async throws -> ToolVerificationResult

    /// Default invoke function that delegates to the UniFFI-generated binding.
    internal static let defaultInvoke: InvokeFn = { handle, toolId, inputJson, identity in
        try await toolInvoke(handle: handle, toolId: toolId, inputJson: inputJson, identity: identity)
    }

    /// Default register function that delegates to the UniFFI-generated binding.
    internal static let defaultRegister: RegisterFn = { handle, definition in
        try await toolRegister(handle: handle, definition: definition)
    }

    /// Default verify function that delegates to the UniFFI-generated binding.
    internal static let defaultVerify: VerifyFn = { handle, toolId in
        try await toolVerify(handle: handle, toolId: toolId)
    }
}

// MARK: - Context Tool Extensions

/// Tool invocation and management extensions for ``Context``.
extension Context {

    /// Invokes a registered tool in this context.
    ///
    /// Delegates to the UniFFI ``toolInvoke`` bridge function. The input Data
    /// is converted to a UTF-8 JSON string for the bridge call, and the output
    /// JSON string is wrapped in a ``ToolInvocationResult`` with provenance.
    ///
    /// - Parameters:
    ///   - tool: The name of the tool to invoke.
    ///   - input: The tool input as serialized JSON data.
    ///   - invokeFn: Bridge function override for testing.
    /// - Returns: A ``ToolInvocationResult`` containing the tool's output and
    ///   provenance metadata.
    /// - Throws: ``ScpError/Tool(message:code:)`` if the tool is not found,
    ///   the input fails schema validation, or the invocation is unauthorized.
    ///   ``ScpError/Context(message:code:)`` if the context is not active.
    ///
    /// ## Provenance
    ///
    /// - ADR-011 (Event Log) in `.docs/adrs/phase-2.md`
    /// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
    /// - Story SCP-221
    public func invokeTool(
        _ tool: String,
        input: Data,
        invokeFn: ToolBridge.InvokeFn = ToolBridge.defaultInvoke
    ) async throws -> ToolInvocationResult {
        guard state == .active else {
            throw ScpError.Context(
                message: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        guard let contextHandle = handle as? ContextHandle else {
            throw ScpError.Context(
                message: "Context handle is not a UniFFI ContextHandle",
                code: "SCP-CTX-2002"
            )
        }
        let inputJson = String(data: input, encoding: .utf8) ?? "{}"
        let identity = Identity(noPointer: .init())
        let outputJson = try await invokeFn(contextHandle, tool, inputJson, identity)
        return ToolInvocationResult(
            output: Data(outputJson.utf8),
            invokerDid: "",
            contextId: contextId,
            timestamp: UInt64(Date().timeIntervalSince1970 * 1_000)
        )
    }

    /// Registers a tool in this context.
    ///
    /// Delegates to the UniFFI ``toolRegister`` bridge function.
    ///
    /// - Parameters:
    ///   - definition: The ``ToolDefinition`` describing the tool.
    ///   - registerFn: Bridge function override for testing.
    /// - Returns: The assigned tool identifier.
    /// - Throws: ``ScpError/Tool(message:code:)`` if registration fails.
    ///   ``ScpError/Context(message:code:)`` if the context is not active.
    ///
    /// ## Provenance
    ///
    /// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
    /// - Story SCP-221
    public func registerTool(
        _ definition: ToolDefinition,
        registerFn: ToolBridge.RegisterFn = ToolBridge.defaultRegister
    ) async throws -> String {
        guard state == .active else {
            throw ScpError.Context(
                message: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        guard let contextHandle = handle as? ContextHandle else {
            throw ScpError.Context(
                message: "Context handle is not a UniFFI ContextHandle",
                code: "SCP-CTX-2002"
            )
        }
        return try await registerFn(contextHandle, definition)
    }

    /// Verifies a tool against its registered test vectors.
    ///
    /// Delegates to the UniFFI ``toolVerify`` bridge function.
    ///
    /// - Parameters:
    ///   - tool: The name of the tool to verify.
    ///   - verifyFn: Bridge function override for testing.
    /// - Returns: A ``ToolVerificationResult`` describing the outcome.
    /// - Throws: ``ScpError/Tool(message:code:)`` if the tool is not found
    ///   or verification fails. ``ScpError/Context(message:code:)`` if the
    ///   context is not active.
    ///
    /// ## Provenance
    ///
    /// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
    /// - Story SCP-221
    public func verifyTool(
        _ tool: String,
        verifyFn: ToolBridge.VerifyFn = ToolBridge.defaultVerify
    ) async throws -> ToolVerificationResult {
        guard state == .active else {
            throw ScpError.Context(
                message: "Context is not active",
                code: "SCP-CTX-2001"
            )
        }
        guard let contextHandle = handle as? ContextHandle else {
            throw ScpError.Context(
                message: "Context handle is not a UniFFI ContextHandle",
                code: "SCP-CTX-2002"
            )
        }
        return try await verifyFn(contextHandle, tool)
    }
}
