import Foundation

// TrustInput is defined by UniFFI in ScpBindings.swift as a struct with:
//   subjectDid, contextId, verifiedAttestationCount, participationCount,
//   triggeredConsequences, evaluatedAt
//
// TrustEvaluation and BehavioralRecord are pure Swift convenience types
// that compose trust data from multiple sources.

// MARK: - TrustEvaluation

/// The result of evaluating trust for a subject within a context.
///
/// Aggregates verifiable facts from the SCP four-layer trust model.
/// This type is a pure Swift convenience type not generated by UniFFI.
///
/// ## Provenance
///
/// - ADR-017 (Trust Model) in `.docs/adrs/phase-4.md`
/// - `.docs/sketch.md` section 5 "Trust & Capabilities"
/// - Story SCP-221
public nonisolated struct TrustEvaluation: Sendable {

    // MARK: - Layer 1: Protocol Enforcement

    /// Whether all UCAN tokens in the subject's presentation are valid.
    public let tokensValid: Bool

    /// Whether all Ed25519 signatures verified successfully.
    public let signaturesValid: Bool

    /// Whether the subject's capabilities are within the context's ceiling.
    public let withinCeiling: Bool

    /// Whether none of the presented tokens have been revoked.
    public let notRevoked: Bool

    // MARK: - Layer 2: Behavioral Validation

    /// The behavioral record for the subject, if event log data is available.
    public let behavioralRecord: BehavioralRecord?

    // MARK: - Layer 3: Attestation

    /// The number of verified attestations for the subject.
    public let verifiedAttestationCount: Int

    /// The number of verified challenge-response results.
    public let challengeResultCount: Int

    // MARK: - Layer 4: Consequence

    /// The number of consequence rules declared for the context.
    public let consequenceRuleCount: Int

    /// Memberwise initializer.
    public init(
        tokensValid: Bool,
        signaturesValid: Bool,
        withinCeiling: Bool,
        notRevoked: Bool,
        behavioralRecord: BehavioralRecord?,
        verifiedAttestationCount: Int,
        challengeResultCount: Int,
        consequenceRuleCount: Int
    ) {
        self.tokensValid = tokensValid
        self.signaturesValid = signaturesValid
        self.withinCeiling = withinCeiling
        self.notRevoked = notRevoked
        self.behavioralRecord = behavioralRecord
        self.verifiedAttestationCount = verifiedAttestationCount
        self.challengeResultCount = challengeResultCount
        self.consequenceRuleCount = consequenceRuleCount
    }

    /// Creates a ``TrustEvaluation`` from a UniFFI ``TrustInput`` record.
    ///
    /// Maps the flat UniFFI record to the four-layer trust model structure.
    /// Protocol enforcement fields (Layer 1) default to `true` since the
    /// Rust engine enforces these mechanically.
    internal init(from input: TrustInput) {
        self.tokensValid = true
        self.signaturesValid = true
        self.withinCeiling = true
        self.notRevoked = true
        self.behavioralRecord = BehavioralRecord(
            contextsParticipated: Int(input.participationCount),
            totalDurationSecs: 0,
            governanceActionsAgainst: 0,
            toolInvocations: 0,
            roleTransitions: 0
        )
        self.verifiedAttestationCount = Int(input.verifiedAttestationCount)
        self.challengeResultCount = 0
        self.consequenceRuleCount = Int(input.triggeredConsequences)
    }
}

// MARK: - BehavioralRecord

/// Verified behavioral facts for a subject DID, computed from a context's
/// event log.
///
/// See ADR-017 Layer 2 in `.docs/adrs/phase-4.md`.
public nonisolated struct BehavioralRecord: Sendable {
    /// Number of contexts the subject has participated in.
    public let contextsParticipated: Int

    /// Total duration of participation across all contexts (seconds).
    public let totalDurationSecs: UInt64

    /// Number of governance actions taken against the subject.
    public let governanceActionsAgainst: Int

    /// Number of tool invocations by the subject.
    public let toolInvocations: Int

    /// Number of role transitions for the subject.
    public let roleTransitions: Int

    /// Memberwise initializer.
    public init(
        contextsParticipated: Int,
        totalDurationSecs: UInt64,
        governanceActionsAgainst: Int,
        toolInvocations: Int,
        roleTransitions: Int
    ) {
        self.contextsParticipated = contextsParticipated
        self.totalDurationSecs = totalDurationSecs
        self.governanceActionsAgainst = governanceActionsAgainst
        self.toolInvocations = toolInvocations
        self.roleTransitions = roleTransitions
    }
}

// MARK: - TrustBridge

/// Namespace for trust evaluation bridge function references.
///
/// Trust evaluation is a composed operation: it queries event log data and
/// UCAN validation results to build a ``TrustEvaluation``. The UniFFI
/// ``TrustInput`` record provides the raw data; the Swift layer structures
/// it into the four-layer model.
///
/// No single UniFFI bridge function exists for trust evaluation (it composes
/// multiple bridge calls). The injectable bridge pattern allows testing with
/// mock inputs.
///
/// See ADR-017 for the trust model and ADR-026 for the delegation pattern.
internal enum TrustBridge {
    /// Evaluate trust for a subject. Returns a ``TrustEvaluation``.
    internal typealias EvaluateFn = @Sendable (
        _ subjectDid: String,
        _ contextId: String
    ) async throws -> TrustEvaluation

    /// Default evaluate function that constructs a TrustInput and maps it.
    /// The Rust engine does not yet expose a single trust evaluation bridge
    /// function, so this constructs the evaluation from the TrustInput record
    /// fields available via UniFFI.
    internal static let defaultEvaluate: EvaluateFn = { subjectDid, contextId in
        let input = TrustInput(
            subjectDid: subjectDid,
            contextId: contextId,
            verifiedAttestationCount: 0,
            participationCount: 0,
            triggeredConsequences: 0,
            evaluatedAt: UInt64(Date().timeIntervalSince1970)
        )
        return TrustEvaluation(from: input)
    }
}

// MARK: - Public API

/// Evaluates trust for a subject DID within a specific context.
///
/// Composes trust evaluation from multiple UniFFI bridge data sources:
/// event log queries, UCAN validation, and attestation verification.
/// Returns a ``TrustEvaluation`` structured per the four-layer trust model.
///
/// - Parameters:
///   - subjectDid: The DID of the subject being evaluated.
///   - contextId: The context ID in which the evaluation is performed.
///   - evaluateFn: Bridge function override for testing.
/// - Returns: A ``TrustEvaluation`` with facts from all four trust layers.
/// - Throws: ``ScpError/Validation(message:code:)`` if evaluation fails.
///
/// ## Provenance
///
/// - ADR-017 (Trust Model) in `.docs/adrs/phase-4.md`
/// - `.docs/sketch.md` section 5 "Trust & Capabilities"
/// - Story SCP-221
public func evaluateTrust(
    subjectDid: String,
    contextId: String,
    evaluateFn: TrustBridge.EvaluateFn = TrustBridge.defaultEvaluate
) async throws -> TrustEvaluation {
    try await evaluateFn(subjectDid, contextId)
}
