import Foundation

// TrustInput is defined by UniFFI in ScpBindings.swift as a struct with:
//   subjectDid, contextId, verifiedAttestationCount, participationCount,
//   triggeredConsequences, evaluatedAt
//
// TrustScoreResult is defined by UniFFI in ScpBindings.swift as a struct with:
//   messageCount, governanceCount, compositeScore
//
// AttestationVerificationResult is defined by UniFFI in ScpBindings.swift as a struct with:
//   valid, chainDepth, errorMessage
//
// ChallengeResult is defined by UniFFI in ScpBindings.swift as a struct with:
//   challengeId, challengeJson
//
// TrustEvaluation and BehavioralRecord are pure Swift convenience types
// that compose trust data from multiple sources.

// MARK: - TrustEvaluation

/// The result of evaluating trust for a subject within a context.
///
/// Aggregates verifiable facts from the SCP four-layer trust model.
/// This type is a pure Swift convenience type not generated by UniFFI.
///
/// ## Provenance
///
/// - ADR-017 (Trust Model) in `.docs/adrs/phase-4.md`
/// - `.docs/sketch.md` section 5 "Trust & Capabilities"
/// - Story SCP-221, #331
public nonisolated struct TrustEvaluation: Sendable {
    // MARK: - Layer 1: Protocol Enforcement

    /// Whether all UCAN tokens in the subject's presentation are valid.
    public let tokensValid: Bool

    /// Whether all Ed25519 signatures verified successfully.
    public let signaturesValid: Bool

    /// Whether the subject's capabilities are within the context's ceiling.
    public let withinCeiling: Bool

    /// Whether none of the presented tokens have been revoked.
    public let notRevoked: Bool

    // MARK: - Layer 2: Behavioral Validation

    /// The behavioral record for the subject, if event log data is available.
    public let behavioralRecord: BehavioralRecord?

    // MARK: - Layer 3: Attestation

    /// The number of verified attestations for the subject.
    public let verifiedAttestationCount: Int

    /// The number of verified challenge-response results.
    public let challengeResultCount: Int

    // MARK: - Layer 4: Consequence

    /// The number of consequence rules declared for the context.
    public let consequenceRuleCount: Int

    /// Memberwise initializer.
    public init(
        tokensValid: Bool,
        signaturesValid: Bool,
        withinCeiling: Bool,
        notRevoked: Bool,
        behavioralRecord: BehavioralRecord?,
        verifiedAttestationCount: Int,
        challengeResultCount: Int,
        consequenceRuleCount: Int
    ) {
        self.tokensValid = tokensValid
        self.signaturesValid = signaturesValid
        self.withinCeiling = withinCeiling
        self.notRevoked = notRevoked
        self.behavioralRecord = behavioralRecord
        self.verifiedAttestationCount = verifiedAttestationCount
        self.challengeResultCount = challengeResultCount
        self.consequenceRuleCount = consequenceRuleCount
    }

    /// Creates a ``TrustEvaluation`` from a UniFFI ``TrustInput`` record.
    ///
    /// Maps the flat UniFFI record to the four-layer trust model structure.
    /// Protocol enforcement fields (Layer 1) default to `true` since the
    /// Rust engine enforces these mechanically.
    init(from input: TrustInput) {
        tokensValid = true
        signaturesValid = true
        withinCeiling = true
        notRevoked = true
        behavioralRecord = BehavioralRecord(
            contextsParticipated: Int(input.participationCount),
            // TrustInput provides participation count and consequence count only.
            // Duration, tool invocations, and role transitions require event log
            // queries not exposed in the current UniFFI bridge.
            totalDurationSecs: 0,
            governanceActionsAgainst: Int(input.triggeredConsequences),
            toolInvocations: 0,
            roleTransitions: 0
        )
        verifiedAttestationCount = Int(input.verifiedAttestationCount)
        challengeResultCount = 0
        consequenceRuleCount = Int(input.triggeredConsequences)
    }

    /// Creates a ``TrustEvaluation`` from a UniFFI ``TrustScoreResult``.
    ///
    /// Maps the participation-based trust score to the four-layer model.
    /// Protocol enforcement fields (Layer 1) default to `true` since the
    /// Rust engine enforces these mechanically.
    init(from score: TrustScoreResult) {
        tokensValid = true
        signaturesValid = true
        withinCeiling = true
        notRevoked = true
        behavioralRecord = BehavioralRecord(
            // TrustScoreResult provides message_count and governance_count only.
            // Context participation count requires cross-context event log queries
            // not exposed in the current UniFFI bridge.
            contextsParticipated: 0,
            totalDurationSecs: 0,
            governanceActionsAgainst: Int(score.governanceCount),
            toolInvocations: 0,
            roleTransitions: 0
        )
        verifiedAttestationCount = 0
        challengeResultCount = 0
        consequenceRuleCount = 0
    }
}

// MARK: - BehavioralRecord

/// Verified behavioral facts for a subject DID, computed from a context's
/// event log.
///
/// See ADR-017 Layer 2 in `.docs/adrs/phase-4.md`.
public nonisolated struct BehavioralRecord: Sendable {
    /// Number of contexts the subject has participated in.
    public let contextsParticipated: Int

    /// Total duration of participation across all contexts (seconds).
    public let totalDurationSecs: UInt64

    /// Number of governance actions taken against the subject.
    public let governanceActionsAgainst: Int

    /// Number of tool invocations by the subject.
    public let toolInvocations: Int

    /// Number of role transitions for the subject.
    public let roleTransitions: Int

    /// Memberwise initializer.
    public init(
        contextsParticipated: Int,
        totalDurationSecs: UInt64,
        governanceActionsAgainst: Int,
        toolInvocations: Int,
        roleTransitions: Int
    ) {
        self.contextsParticipated = contextsParticipated
        self.totalDurationSecs = totalDurationSecs
        self.governanceActionsAgainst = governanceActionsAgainst
        self.toolInvocations = toolInvocations
        self.roleTransitions = roleTransitions
    }
}

// MARK: - TrustBridge

/// Namespace for trust evaluation bridge function references.
///
/// Trust evaluation composes multiple UniFFI bridge calls to build a
/// ``TrustEvaluation``. The injectable bridge pattern allows testing with
/// mock inputs.
///
/// See ADR-017 for the trust model and ADR-026 for the delegation pattern.
public enum TrustBridge {
    /// Evaluate trust for a subject. Returns a ``TrustEvaluation``.
    public typealias EvaluateFn = @Sendable (
        _ subjectDid: String,
        _ contextId: String
    ) async throws -> TrustEvaluation

    /// Query participation-based trust score for a DID in a context.
    public typealias QueryScoreFn = @Sendable (
        _ did: String,
        _ contextId: String
    ) throws -> TrustScoreResult

    /// Verify an attestation's Ed25519 signature, evidence, expiry, and
    /// revocation status.
    public typealias VerifyAttestationFn = @Sendable (
        _ attestationJson: String
    ) throws -> AttestationVerificationResult

    /// Create a challenge request for capability verification.
    public typealias CreateChallengeFn = @Sendable (
        _ targetDid: String
    ) throws -> ChallengeResult

    /// Verify a challenge response against its original challenge request.
    public typealias VerifyResponseFn = @Sendable (
        _ challengeJson: String,
        _ responseJson: String
    ) throws -> Bool

    /// Default evaluate function that delegates to the UniFFI
    /// ``trustQueryScore`` bridge function.
    public static let defaultEvaluate: EvaluateFn = { subjectDid, contextId in
        let score = try trustQueryScore(did: subjectDid, contextId: contextId)
        return TrustEvaluation(from: score)
    }

    /// Default query score function — delegates to UniFFI ``trustQueryScore``.
    public static let defaultQueryScore: QueryScoreFn = { did, contextId in
        try trustQueryScore(did: did, contextId: contextId)
    }

    /// Default verify attestation function — delegates to UniFFI
    /// ``trustVerifyAttestation``.
    public static let defaultVerifyAttestation: VerifyAttestationFn = { attestationJson in
        try trustVerifyAttestation(attestationJson: attestationJson)
    }

    /// Default create challenge function — delegates to UniFFI
    /// ``trustCreateChallenge``.
    public static let defaultCreateChallenge: CreateChallengeFn = { targetDid in
        try trustCreateChallenge(targetDid: targetDid)
    }

    /// Default verify response function — delegates to UniFFI
    /// ``trustVerifyResponse``.
    public static let defaultVerifyResponse: VerifyResponseFn = { challengeJson, responseJson in
        try trustVerifyResponse(challengeJson: challengeJson, responseJson: responseJson)
    }
}

// MARK: - Public API

/// Evaluates trust for a subject DID within a specific context.
///
/// Composes trust evaluation from multiple UniFFI bridge data sources:
/// event log queries, UCAN validation, and attestation verification.
/// Returns a ``TrustEvaluation`` structured per the four-layer trust model.
///
/// - Parameters:
///   - subjectDid: The DID of the subject being evaluated.
///   - contextId: The context ID in which the evaluation is performed.
///   - evaluateFn: Bridge function override for testing.
/// - Returns: A ``TrustEvaluation`` with facts from all four trust layers.
/// - Throws: ``ScpError`` if evaluation fails.
///
/// ## Provenance
///
/// - ADR-017 (Trust Model) in `.docs/adrs/phase-4.md`
/// - `.docs/sketch.md` section 5 "Trust & Capabilities"
/// - Story SCP-221, #331
public func evaluateTrust(
    subjectDid: String,
    contextId: String,
    evaluateFn: TrustBridge.EvaluateFn = TrustBridge.defaultEvaluate
) async throws -> TrustEvaluation {
    try await evaluateFn(subjectDid, contextId)
}

/// Queries participation-based trust score for a DID within a context.
///
/// Returns a ``TrustScoreResult`` containing message count, governance
/// action count, and a normalized composite score (0.0-1.0). The score
/// is participation-based, not a judgment — agents apply their own
/// criteria to these inputs.
///
/// Delegates to the UniFFI ``trustQueryScore`` bridge function.
///
/// - Parameters:
///   - did: The DID of the subject being scored.
///   - contextId: The context ID in which the score is queried.
///   - queryScoreFn: Bridge function override for testing.
/// - Returns: A ``TrustScoreResult`` with participation metrics.
/// - Throws: ``ScpError`` if the query fails.
///
/// ## Provenance
///
/// - ADR-017 Layer 2 in `.docs/adrs/phase-4.md`
/// - Story #331
public func queryTrustScore(
    did: String,
    contextId: String,
    queryScoreFn: TrustBridge.QueryScoreFn = TrustBridge.defaultQueryScore
) throws -> TrustScoreResult {
    try queryScoreFn(did, contextId)
}

/// Verifies an attestation's Ed25519 signature, evidence, expiry, and
/// revocation status.
///
/// Returns an ``AttestationVerificationResult`` indicating whether the
/// attestation is valid, the chain depth, and an error message if invalid.
///
/// Delegates to the UniFFI ``trustVerifyAttestation`` bridge function.
///
/// - Parameters:
///   - attestationJson: The attestation as a serialized JSON string.
///   - verifyAttestationFn: Bridge function override for testing.
/// - Returns: An ``AttestationVerificationResult``.
/// - Throws: ``ScpError`` if verification fails (e.g., invalid JSON).
///
/// ## Provenance
///
/// - ADR-017 Layer 3 in `.docs/adrs/phase-4.md`
/// - Story #331
public func verifyAttestation(
    attestationJson: String,
    verifyAttestationFn: TrustBridge.VerifyAttestationFn = TrustBridge.defaultVerifyAttestation
) throws -> AttestationVerificationResult {
    try verifyAttestationFn(attestationJson)
}

/// Creates a challenge request for capability verification.
///
/// Generates an ephemeral Ed25519 keypair, constructs a challenge request
/// targeting the specified DID, and returns the challenge ID and serialized
/// challenge JSON.
///
/// Delegates to the UniFFI ``trustCreateChallenge`` bridge function.
///
/// - Parameters:
///   - targetDid: The DID of the entity being challenged.
///   - createChallengeFn: Bridge function override for testing.
/// - Returns: A ``ChallengeResult`` with the challenge ID and JSON payload.
/// - Throws: ``ScpError`` if challenge creation fails.
///
/// ## Provenance
///
/// - ADR-017 Layer 3 (Challenge-Response) in `.docs/adrs/phase-4.md`
/// - Story #331
public func createChallenge(
    targetDid: String,
    createChallengeFn: TrustBridge.CreateChallengeFn = TrustBridge.defaultCreateChallenge
) throws -> ChallengeResult {
    try createChallengeFn(targetDid)
}

/// Verifies a challenge response against its original challenge request.
///
/// Checks that the response correctly answers the challenge, including
/// signature verification and challenge ID matching.
///
/// Delegates to the UniFFI ``trustVerifyResponse`` bridge function.
///
/// - Parameters:
///   - challengeJson: The original challenge request as serialized JSON.
///   - responseJson: The response to verify as serialized JSON.
///   - verifyResponseFn: Bridge function override for testing.
/// - Returns: `true` if the response is valid, `false` otherwise.
/// - Throws: ``ScpError`` if verification fails (e.g., invalid JSON).
///
/// ## Provenance
///
/// - ADR-017 Layer 3 (Challenge-Response) in `.docs/adrs/phase-4.md`
/// - Story #331
public func verifyChallengeResponse(
    challengeJson: String,
    responseJson: String,
    verifyResponseFn: TrustBridge.VerifyResponseFn = TrustBridge.defaultVerifyResponse
) throws -> Bool {
    try verifyResponseFn(challengeJson, responseJson)
}

// MARK: - Trust Aggregation

/// Aggregated trust input result.
///
/// Contains the JSON-decoded output of the trust aggregation pipeline.
/// Each field corresponds to one of the four trust layers.
///
/// ## Provenance
///
/// - ADR-017 acceptance criterion 9
/// - Spec section 7.3
public nonisolated struct AggregatedTrustInput: Sendable {
    /// Verified attestations (Layer 3), as raw JSON-decoded objects.
    public let verifiedAttestations: [[String: Any]]

    /// Participation record (Layer 2), as a raw JSON-decoded object.
    public let participationRecord: [String: Any]

    /// Challenge-response results (Layer 3), as raw JSON-decoded objects.
    public let challengeResults: [[String: Any]]

    /// Consequence rules (Layer 4), as raw JSON-decoded objects.
    public let consequenceStructure: [[String: Any]]

    /// Threshold counts per attestation type: [met, required].
    public let thresholdCounts: [String: [Int]]
}

/// Aggregates all trust engine layers into a single input for
/// agent-level evaluation.
///
/// Combines participation records, attestation verification, challenge
/// results, consequence structure, and threshold counts. The returned
/// object contains verifiable facts -- agents apply their own criteria.
///
/// Delegates to the UniFFI `aggregateTrustInput` bridge function and
/// parses the JSON result into a typed ``AggregatedTrustInput``.
///
/// - Parameters:
///   - contextId: The context to aggregate trust inputs for.
///   - subjectDid: The DID of the subject to evaluate.
///   - eventsJson: JSON array of event log entries.
///   - merkleRootJson: JSON array of 32 bytes (Merkle root).
///   - consequenceRulesJson: JSON array of consequence rules.
///   - thresholdRequirementsJson: JSON object of threshold requirements.
///   - attestorSetsJson: JSON object of attestor sets.
///   - cachedAttestationsJson: JSON array of cached attestations.
///   - challengeResultsJson: JSON array of challenge results.
/// - Returns: An ``AggregatedTrustInput`` with all trust layers.
/// - Throws: ``ScpError`` if inputs are malformed or aggregation fails.
///
/// ## Provenance
///
/// - ADR-017 acceptance criterion 9
/// - Spec section 7.3
public func aggregateTrust(
    contextId: String,
    subjectDid: String,
    eventsJson: String,
    merkleRootJson: String,
    consequenceRulesJson: String = "[]",
    thresholdRequirementsJson: String = "{}",
    attestorSetsJson: String = "{}",
    cachedAttestationsJson: String = "[]",
    challengeResultsJson: String = "[]"
) throws -> AggregatedTrustInput {
    let resultJson = try aggregateTrustInput(
        contextId: contextId,
        subjectDid: subjectDid,
        eventsJson: eventsJson,
        merkleRootJson: merkleRootJson,
        consequenceRulesJson: consequenceRulesJson,
        thresholdRequirementsJson: thresholdRequirementsJson,
        attestorSetsJson: attestorSetsJson,
        cachedAttestationsJson: cachedAttestationsJson,
        challengeResultsJson: challengeResultsJson
    )

    guard let data = resultJson.data(using: .utf8),
          let json = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
        throw ScpError.Validation(
            msg: "failed to parse aggregation result JSON",
            code: "SCP-VALID-7060"
        )
    }

    return AggregatedTrustInput(
        verifiedAttestations: json["verified_attestations"] as? [[String: Any]] ?? [],
        participationRecord: json["participation_record"] as? [String: Any] ?? [:],
        challengeResults: json["challenge_results"] as? [[String: Any]] ?? [],
        consequenceStructure: json["consequence_structure"] as? [[String: Any]] ?? [],
        thresholdCounts: json["threshold_counts"] as? [String: [Int]] ?? [:]
    )
}

// MARK: - Participation Types

/// A verifiable participation fact type.
///
/// Participation facts represent quantifiable behavioral signals that can
/// be observed from a context's event log. They are inputs to the trust
/// model's behavioral validation layer (Layer 2).
///
/// ## Provenance
///
/// - ADR-017 Layer 2 (Behavioral Validation)
/// - Spec section 23.7 (Participation Requirements)
public enum ParticipationFact: String, Sendable, CaseIterable {
    /// Number of messages sent by the participant.
    case messagesSent = "messages_sent"

    /// Number of tools invoked by the participant.
    case toolsInvoked = "tools_invoked"

    /// Number of governance actions taken by the participant.
    case governanceActions = "governance_actions"

    /// Number of contexts the participant has joined.
    case contextsParticipated = "contexts_participated"

    /// Number of attestations the participant has verified.
    case attestationsVerified = "attestations_verified"
}

/// A minimum threshold for a specific participation fact.
///
/// Used in ``RequireParticipation`` to define the minimum observed value
/// a participant must have for a given fact type.
///
/// ## Provenance
///
/// - ADR-017 Layer 2 (Behavioral Validation)
/// - Spec section 23.7 (Participation Requirements)
public nonisolated struct ParticipationThreshold: Sendable {
    /// The participation fact to check.
    public let fact: ParticipationFact

    /// The minimum value required.
    public let minimum: UInt64

    /// Memberwise initializer.
    public init(fact: ParticipationFact, minimum: UInt64) {
        self.fact = fact
        self.minimum = minimum
    }
}

/// A participant's observed values for each participation fact.
///
/// Maps ``ParticipationFact`` cases to their observed counts. Missing
/// keys are treated as zero when checked against thresholds.
///
/// ## Provenance
///
/// - ADR-017 Layer 2 (Behavioral Validation)
/// - Spec section 23.7 (Participation Requirements)
public typealias ParticipationProfile = [ParticipationFact: UInt64]

/// A set of participation thresholds for admission gating.
///
/// Used as admission criteria or trust-gating requirements. When
/// ``requireAll`` is `true` (the default), all thresholds must be
/// satisfied (AND/conjunction). When `false`, any single threshold
/// passing is sufficient (OR/disjunction).
///
/// ## Provenance
///
/// - ADR-017 Layer 2 (Behavioral Validation)
/// - Spec section 23.7 (Participation Requirements)
public nonisolated struct RequireParticipation: Sendable {
    /// The thresholds to check.
    public let thresholds: [ParticipationThreshold]

    /// If `true`, **all** thresholds must be met (AND logic).
    /// If `false`, **any** single threshold is sufficient (OR logic).
    public let requireAll: Bool

    /// Memberwise initializer.
    ///
    /// - Parameters:
    ///   - thresholds: The participation thresholds to check.
    ///   - requireAll: Whether all thresholds must be met (`true`, default)
    ///     or any single threshold is sufficient (`false`).
    public init(thresholds: [ParticipationThreshold], requireAll: Bool = true) {
        self.thresholds = thresholds
        self.requireAll = requireAll
    }
}

// MARK: - Participation Verification

/// Verifies that a participation profile meets the required thresholds.
///
/// When ``RequireParticipation/requireAll`` is `true` (default), returns
/// `true` only if **every** threshold is met (AND). When `false`, returns
/// `true` if **any** threshold is met (OR). Missing profile entries are
/// treated as zero.
///
/// This is a pure Swift function with no bridge dependency.
///
/// - Parameters:
///   - requirement: The participation thresholds to check.
///   - profile: The observed participation values.
/// - Returns: `true` if the requirement is satisfied, `false` otherwise.
///
/// ## Provenance
///
/// - ADR-017 Layer 2 (Behavioral Validation)
/// - Spec section 23.7 (Participation Requirements)
public func verifyParticipationRequirements(
    requirement: RequireParticipation,
    profile: ParticipationProfile
) -> Bool {
    if requirement.thresholds.isEmpty {
        return true
    }

    let results = requirement.thresholds.map { threshold -> Bool in
        let observed = profile[threshold.fact] ?? 0
        return observed >= threshold.minimum
    }

    return requirement.requireAll
        ? results.allSatisfy { $0 }
        : results.contains { $0 }
}
