import Foundation

// UcanToken is now defined by UniFFI in ScpBindings.swift as an open class
// with methods: issuer(), audience(), expiresAt(), tokenId(), capabilities(), tokenData().
//
// The hand-written UcanToken struct has been removed.

// MARK: - UcanCapability

/// A single capability grant within a UCAN token.
///
/// Each capability specifies a resource URI and an action. Resource URIs
/// follow the SCP capability URI format: `scp:ctx:{context_id}/{capability}`.
/// Wildcards are supported: `scp:ctx:*/messages:write` matches any context.
///
/// This type is a pure Swift convenience type not generated by UniFFI.
///
/// See ADR-016 acceptance criterion 4.
public nonisolated struct UcanCapability: Sendable {
    /// Resource URI (e.g., `"scp:ctx:abc123/messages:write"`).
    public let resource: String

    /// Action (e.g., `"invoke"`, `"read"`, `"write"`).
    public let action: String

    /// Memberwise initializer.
    public init(resource: String, action: String) {
        self.resource = resource
        self.action = action
    }
}

// MARK: - UcanValidationResult

/// The result of validating a UCAN token.
///
/// Contains the validation outcome and, if valid, the extracted token.
/// This type is a pure Swift convenience type not generated by UniFFI.
public nonisolated struct UcanValidationResult: Sendable {
    /// Whether the token passed all validation checks.
    public let isValid: Bool

    /// The validated token, if validation succeeded. `nil` if validation failed.
    public let token: UcanToken?

    /// A human-readable reason if validation failed. `nil` if valid.
    public let failureReason: String?

    /// Memberwise initializer.
    public init(isValid: Bool, token: UcanToken?, failureReason: String?) {
        self.isValid = isValid
        self.token = token
        self.failureReason = failureReason
    }
}

// MARK: - UcanBridge

/// Namespace for UniFFI bridge function references used by UCAN operations.
/// Each typealias maps 1:1 to a UniFFI-generated async function. Closures are
/// injected for testability; defaults call through to ScpBindings.
///
/// See ADR-026 for the flat delegation pattern and ADR-016 for UCAN spec.
internal enum UcanBridge {
    /// Validate a UCAN token. Maps to ``ucanValidate`` in ScpBindings.
    internal typealias ValidateFn = @Sendable (
        _ handle: ContextHandle,
        _ token: String,
        _ capability: String,
        _ presentingAgentDid: String?,
        _ proofTokens: [String]?
    ) async throws -> Void

    /// Mint a UCAN token. Maps to ``ucanMint`` in ScpBindings.
    internal typealias MintFn = @Sendable (
        _ handle: ContextHandle,
        _ memberDid: String,
        _ capabilities: [String]
    ) async throws -> UcanToken

    /// Revoke a UCAN token. Maps to ``ucanRevoke`` in ScpBindings.
    internal typealias RevokeFn = @Sendable (
        _ handle: ContextHandle,
        _ token: String
    ) async throws -> Void

    /// Default validate function that delegates to the UniFFI-generated binding.
    internal static let defaultValidate: ValidateFn = { handle, token, capability, presentingAgentDid, proofTokens in
        try await ucanValidate(handle: handle, token: token, capability: capability, presentingAgentDid: presentingAgentDid, proofTokens: proofTokens)
    }

    /// Default mint function that delegates to the UniFFI-generated binding.
    internal static let defaultMint: MintFn = { handle, memberDid, capabilities in
        try await ucanMint(handle: handle, memberDid: memberDid, capabilities: capabilities)
    }

    /// Default revoke function that delegates to the UniFFI-generated binding.
    internal static let defaultRevoke: RevokeFn = { handle, token in
        try await ucanRevoke(handle: handle, token: token)
    }
}

// MARK: - UCAN Public API

/// Validates a UCAN token against a required capability.
///
/// Delegates to the UniFFI ``ucanValidate`` bridge function. The UniFFI
/// function performs the full 11-step validation pipeline specified in ADR-016.
///
/// - Parameters:
///   - handle: The ``ContextHandle`` for the context.
///   - token: The encoded UCAN token string.
///   - capability: The required capability string to validate against.
///   - presentingAgentDid: Optional DID of the agent presenting the token.
///   - proofTokens: Optional proof delegation chain tokens.
///   - validateFn: Bridge function override for testing.
/// - Throws: ``ScpError/Permission(message:code:)`` if validation fails.
///
/// ## Provenance
///
/// - ADR-016 (UCAN) in `.docs/adrs/phase-3.md`
/// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
/// - Story SCP-221
public func validateUcanToken(
    handle: ContextHandle,
    token: String,
    capability: String,
    presentingAgentDid: String? = nil,
    proofTokens: [String]? = nil,
    validateFn: UcanBridge.ValidateFn = UcanBridge.defaultValidate
) async throws {
    try await validateFn(handle, token, capability, presentingAgentDid, proofTokens)
}

/// Mints a new UCAN token with the specified capabilities.
///
/// Delegates to the UniFFI ``ucanMint`` bridge function.
///
/// - Parameters:
///   - handle: The ``ContextHandle`` for the context.
///   - memberDid: The DID of the member to mint the token for.
///   - capabilities: An array of capability strings.
///   - mintFn: Bridge function override for testing.
/// - Returns: The minted ``UcanToken``.
/// - Throws: ``ScpError/Permission(message:code:)`` if minting fails.
///
/// ## Provenance
///
/// - ADR-016 (UCAN) in `.docs/adrs/phase-3.md`
/// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
/// - Story SCP-221
public func mintUcanToken(
    handle: ContextHandle,
    memberDid: String,
    capabilities: [String],
    mintFn: UcanBridge.MintFn = UcanBridge.defaultMint
) async throws -> UcanToken {
    try await mintFn(handle, memberDid, capabilities)
}

/// Revokes a UCAN token.
///
/// Delegates to the UniFFI ``ucanRevoke`` bridge function.
///
/// - Parameters:
///   - handle: The ``ContextHandle`` for the context.
///   - token: The full encoded JWT string of the token to revoke.
///   - revokeFn: Bridge function override for testing.
/// - Throws: ``ScpError/Permission(message:code:)`` if revocation fails.
///
/// ## Provenance
///
/// - ADR-016 (UCAN) in `.docs/adrs/phase-3.md`
/// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
/// - Story SCP-221
public func revokeUcanToken(
    handle: ContextHandle,
    token: String,
    revokeFn: UcanBridge.RevokeFn = UcanBridge.defaultRevoke
) async throws {
    try await revokeFn(handle, token)
}

// MARK: - Legacy API (backward compatibility)

/// Validates a UCAN token against the full 11-step validation pipeline.
///
/// Legacy wrapper that creates a ``ContextHandle`` placeholder and delegates
/// to ``validateUcanToken(handle:token:capability:validateFn:)``. Prefer the
/// handle-based API for production use.
///
/// ## Provenance
///
/// - ADR-016 (UCAN) in `.docs/adrs/phase-3.md`
/// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
/// - Story SCP-221
public func validate(
    encoded: String,
    contextId: String,
    presenterDid: String,
    validateFn: UcanBridge.ValidateFn = UcanBridge.defaultValidate
) async throws -> UcanValidationResult {
    let handle = ContextHandle(noPointer: .init())
    do {
        try await validateFn(handle, encoded, presenterDid, nil, nil)
        return UcanValidationResult(isValid: true, token: nil, failureReason: nil)
    } catch {
        return UcanValidationResult(isValid: false, token: nil, failureReason: "\(error)")
    }
}

/// Mints a new UCAN token with the specified capabilities.
///
/// Legacy wrapper that creates a ``ContextHandle`` placeholder and delegates
/// to ``mintUcanToken(handle:memberDid:capabilities:mintFn:)``. Prefer the
/// handle-based API for production use.
///
/// ## Provenance
///
/// - ADR-016 (UCAN) in `.docs/adrs/phase-3.md`
/// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
/// - Story SCP-221
public func mint(
    issuerDid: String,
    audienceDid: String,
    capabilities: [UcanCapability],
    expirySecs: UInt64 = 3_600,
    proofs: [String] = [],
    mintFn: UcanBridge.MintFn = UcanBridge.defaultMint
) async throws -> UcanToken {
    let handle = ContextHandle(noPointer: .init())
    let capStrings = capabilities.map { "\($0.resource):\($0.action)" }
    return try await mintFn(handle, audienceDid, capStrings)
}

/// Revokes a UCAN token.
///
/// Legacy wrapper that creates a ``ContextHandle`` placeholder and delegates
/// to ``revokeUcanToken(handle:token:revokeFn:)``. Prefer the
/// handle-based API for production use.
///
/// ## Provenance
///
/// - ADR-016 (UCAN) in `.docs/adrs/phase-3.md`
/// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
/// - Story SCP-221
public func revoke(
    encoded: String,
    revokerDid: String,
    revokeFn: UcanBridge.RevokeFn = UcanBridge.defaultRevoke
) async throws {
    let handle = ContextHandle(noPointer: .init())
    try await revokeFn(handle, encoded)
}
