import Foundation

// UcanToken is now defined by UniFFI in ScpBindings.swift as an open class
// with methods: issuer(), audience(), expiresAt(), tokenId(), capabilities(), tokenData().
//
// The hand-written UcanToken struct has been removed.

// MARK: - UcanCapability

/// A single capability grant within a UCAN token.
///
/// Each capability specifies a resource URI and an action. Resource URIs
/// follow the SCP capability URI format: `scp:ctx:{context_id}/{capability}`.
/// Wildcards are supported: `scp:ctx:*/messages:write` matches any context.
///
/// This type is a pure Swift convenience type not generated by UniFFI.
///
/// See ADR-016 acceptance criterion 4.
public nonisolated struct UcanCapability: Sendable {
    /// Resource URI (e.g., `"scp:ctx:abc123/messages:write"`).
    public let resource: String

    /// Action (e.g., `"invoke"`, `"read"`, `"write"`).
    public let action: String

    /// Memberwise initializer.
    public init(resource: String, action: String) {
        self.resource = resource
        self.action = action
    }
}

// MARK: - UcanValidationResult

/// The result of validating a UCAN token.
///
/// Contains the validation outcome and, if valid, the extracted token.
/// This type is a pure Swift convenience type not generated by UniFFI.
public nonisolated struct UcanValidationResult: Sendable {
    /// Whether the token passed all validation checks.
    public let isValid: Bool

    /// The validated token, if validation succeeded. `nil` if validation failed.
    public let token: UcanToken?

    /// A human-readable reason if validation failed. `nil` if valid.
    public let failureReason: String?

    /// Memberwise initializer.
    public init(isValid: Bool, token: UcanToken?, failureReason: String?) {
        self.isValid = isValid
        self.token = token
        self.failureReason = failureReason
    }
}

// MARK: - UniFFI Bridge Stubs

/// Validate a UCAN token via the UniFFI bridge.
///
/// Placeholder stub for the UniFFI-generated `ucan_validate` function.
/// Performs the full 11-step validation pipeline specified in ADR-016.
internal func scpUcanValidate(
    encoded: String,
    contextId: String,
    presenterDid: String,
    completion: @Sendable @escaping (Result<UcanValidationResult, ScpError>) -> Void
) {
    // Placeholder: replaced by UniFFI-generated binding (SCP-103).
    completion(.failure(.Permission(
        message: "UniFFI bridge not yet available — build ScpFFI.xcframework (SCP-103)",
        code: "SCP-UCAN-001"
    )))
}

/// Mint a new UCAN token via the UniFFI bridge.
///
/// Placeholder stub for the UniFFI-generated `ucan_mint` function.
internal func scpUcanMint(
    issuerDid: String,
    audienceDid: String,
    capabilities: [UcanCapability],
    expirySecs: UInt64,
    proofs: [String],
    completion: @Sendable @escaping (Result<UcanToken, ScpError>) -> Void
) {
    // Placeholder: replaced by UniFFI-generated binding (SCP-103).
    completion(.failure(.Permission(
        message: "UniFFI bridge not yet available — build ScpFFI.xcframework (SCP-103)",
        code: "SCP-UCAN-002"
    )))
}

/// Revoke a UCAN token via the UniFFI bridge.
///
/// Placeholder stub for the UniFFI-generated `ucan_revoke` function.
internal func scpUcanRevoke(
    encoded: String,
    revokerDid: String,
    completion: @Sendable @escaping (Result<Void, ScpError>) -> Void
) {
    // Placeholder: replaced by UniFFI-generated binding (SCP-103).
    completion(.failure(.Permission(
        message: "UniFFI bridge not yet available — build ScpFFI.xcframework (SCP-103)",
        code: "SCP-UCAN-003"
    )))
}

// MARK: - UCAN Public API

/// Validates a UCAN token against the full 11-step validation pipeline.
///
/// This function bridges the asynchronous UniFFI `ucan_validate` call to
/// Swift concurrency via `CheckedContinuation`.
///
/// ## Provenance
///
/// - ADR-016 (UCAN) in `.docs/adrs/phase-3.md`
/// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
/// - Story SCP-101
public func validate(
    encoded: String,
    contextId: String,
    presenterDid: String
) async throws -> UcanValidationResult {
    try await withCheckedThrowingContinuation {
        (continuation: CheckedContinuation<UcanValidationResult, Error>) in
        scpUcanValidate(
            encoded: encoded,
            contextId: contextId,
            presenterDid: presenterDid
        ) { result in
            switch result {
            case .success(let validationResult):
                continuation.resume(returning: validationResult)
            case .failure(let error):
                continuation.resume(throwing: error)
            }
        }
    }
}

/// Mints a new UCAN token with the specified capabilities.
///
/// ## Provenance
///
/// - ADR-016 (UCAN) in `.docs/adrs/phase-3.md`
/// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
/// - Story SCP-101
public func mint(
    issuerDid: String,
    audienceDid: String,
    capabilities: [UcanCapability],
    expirySecs: UInt64 = 3_600,
    proofs: [String] = []
) async throws -> UcanToken {
    try await withCheckedThrowingContinuation {
        (continuation: CheckedContinuation<UcanToken, Error>) in
        scpUcanMint(
            issuerDid: issuerDid,
            audienceDid: audienceDid,
            capabilities: capabilities,
            expirySecs: expirySecs,
            proofs: proofs
        ) { result in
            switch result {
            case .success(let token):
                continuation.resume(returning: token)
            case .failure(let error):
                continuation.resume(throwing: error)
            }
        }
    }
}

/// Revokes a UCAN token.
///
/// ## Provenance
///
/// - ADR-016 (UCAN) in `.docs/adrs/phase-3.md`
/// - ADR-026 (Swift SDK) in `.docs/adrs/phase-5.md`
/// - Story SCP-101
public func revoke(encoded: String, revokerDid: String) async throws {
    try await withCheckedThrowingContinuation {
        (continuation: CheckedContinuation<Void, Error>) in
        scpUcanRevoke(encoded: encoded, revokerDid: revokerDid) { result in
            switch result {
            case .success:
                continuation.resume()
            case .failure(let error):
                continuation.resume(throwing: error)
            }
        }
    }
}
