import Foundation

// UcanToken is now defined by UniFFI in ScpBindings.swift as an open class
// with methods: issuer(), audience(), expiresAt(), tokenId(), capabilities(), tokenData().
//
// The hand-written UcanToken struct has been removed.

// MARK: - UcanCapability

/// A single capability grant within a UCAN token.
///
/// Each capability specifies a resource URI and an action. Resource URIs
/// follow the SCP capability URI format: `scp:ctx:{context_id}/{capability}`.
/// Wildcards are supported: `scp:ctx:*/messages:write` matches any context.
///
/// This type is a pure Swift convenience type not generated by UniFFI.
///
/// See ADR-016 acceptance criterion 4.
public nonisolated struct UcanCapability: Sendable {
    /// Resource URI (e.g., `"scp:ctx:abc123/messages:write"`).
    public let resource: String

    /// Action (e.g., `"invoke"`, `"read"`, `"write"`).
    public let action: String

    /// Memberwise initializer.
    public init(resource: String, action: String) {
        self.resource = resource
        self.action = action
    }
}

// MARK: - UcanValidationResult

/// The result of validating a UCAN token.
///
/// Contains the validation outcome and, if valid, the extracted token.
/// This type is a pure Swift convenience type not generated by UniFFI.
public nonisolated struct UcanValidationResult: Sendable {
    /// Whether the token passed all validation checks.
    public let isValid: Bool

    /// The validated token, if validation succeeded. `nil` if validation failed.
    public let token: UcanToken?

    /// A human-readable reason if validation failed. `nil` if valid.
    public let failureReason: String?

    /// Memberwise initializer.
    public init(isValid: Bool, token: UcanToken?, failureReason: String?) {
        self.isValid = isValid
        self.token = token
        self.failureReason = failureReason
    }
}

// MARK: - SCP UCAN convenience

public extension SCP {
    /// Convenience wrapper that catches validation errors and returns a
    /// ``UcanValidationResult`` instead of throwing.
    ///
    /// - Parameters:
    ///   - handle: The ``ContextHandle`` for the context.
    ///   - encoded: The encoded UCAN token string.
    ///   - capability: The required capability string to validate against.
    ///   - presenterDid: Optional DID of the agent presenting the token.
    ///   - proofTokens: Optional proof delegation chain tokens.
    /// - Returns: A ``UcanValidationResult`` indicating success or failure.
    func validateUcanWithResult(
        handle: ContextHandle,
        encoded: String,
        capability: String,
        presenterDid: String? = nil,
        proofTokens: [String]? = nil
    ) async -> UcanValidationResult {
        do {
            try await ucanValidate(
                handle: handle,
                token: encoded,
                capability: capability,
                presentingAgentDid: presenterDid,
                proofTokens: proofTokens
            )
            return UcanValidationResult(isValid: true, token: nil, failureReason: nil)
        } catch {
            return UcanValidationResult(isValid: false, token: nil, failureReason: "\(error)")
        }
    }

    /// Convenience wrapper over ``SCP/ucanMint`` that takes a typed
    /// ``UcanCapability`` array instead of resource:action strings.
    func mintUcan(
        handle: ContextHandle,
        audienceDid: String,
        capabilities: [UcanCapability],
        proofs: [String] = []
    ) async throws -> UcanToken {
        let capStrings = capabilities.map { "\($0.resource):\($0.action)" }
        return try await ucanMint(
            handle: handle,
            memberDid: audienceDid,
            capabilities: capStrings,
            proofs: proofs.isEmpty ? nil : proofs
        )
    }
}
