//! Key custody migration protocol (spec §3.2.1).
//!
//! "The identity layer abstracts custody. The user authenticates however they
//! choose; under the hood it resolves to a protocol-level DID. Migration
//! between custody methods is possible without changing identity." — §3.2
//!
//! This module defines the wire types for custody migration requests and
//! implements the 5-step custody migration state machine. Migration changes
//! the custody backend — an encrypted key file on disk and the keystore the
//! operating system runs are the two a caller names — without altering the
//! user's DID. The active signing key
//! (`#active`) is rotated to a new key generated by the target custody
//! provider; the identity key (`#0`) and DID remain stable.
//!
//! # Migration Steps (spec §3.2.1)
//!
//! 1. **Initiate** — The target custody provider generates a new Ed25519
//!    keypair. The new public key is captured in a [`CustodyMigrationRequest`].
//! 2. **Authorize** — The current `#active` and `#0` keys sign the migration
//!    request to prove consent and continuity.
//! 3. **Rotate** — The DID document is updated to replace the `#active`
//!    verification method with the new public key. This update is signed by
//!    the identity key (`#0`) per ADR-003 §4a and published to DHT.
//! 4. **Reissue** — Existing UCAN tokens signed by the old active key are
//!    revoked and reissued under the new active key. Attestations signed by
//!    the old key are re-signed (spec §3.2.1 step 4).
//! 5. **Destroy** — After verifying DID document propagation, the old active
//!    key material is destroyed in the previous custody provider.
//!
//! See spec §3.2.1 (Key Custody Migration Protocol) and §9.12 (Key Rotation).

use serde::{Deserialize, Serialize};

use scp_did::DID;

use scp_clock::Clock;

// Re-use CustodyType from scp-platform to avoid duplication.
// CustodyType is already defined in scp_platform::traits but scp-core doesn't
// depend on scp-platform. We define the migration-level custody type enum here
// to keep scp-core self-contained.

// ---------------------------------------------------------------------------
// CustodyMigrationTarget
// ---------------------------------------------------------------------------

/// The custody backend a migration moves the `#active` key into (spec §3.2).
///
/// A caller naming a custody backend names one of these two. The vocabulary
/// carries no in-memory value: an in-memory custody keeps no key across a
/// restart, so migrating an identity into one destroys the identity's `#active`
/// key, and a caller has no reason to ask for that.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CustodyMigrationTarget {
    /// A key file on disk, encrypted under a passphrase.
    EncryptedFile,
    /// The keystore the operating system runs (Apple Keychain, Android
    /// Keystore, Windows credential manager).
    OsKeystore,
}

// ---------------------------------------------------------------------------
// CustodyMigrationRequest
// ---------------------------------------------------------------------------

/// A request to migrate key custody from one provider to another (spec §3.2).
///
/// The request captures the new active public key generated by the target
/// custody provider, the target custody type, and the request timestamp.
/// The request must be signed by the current active key to prove consent.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CustodyMigrationRequest {
    /// Ed25519 public key bytes (32 bytes) generated by the target custody
    /// provider. This will become the new `#active` verification method.
    #[serde(with = "serde_bytes")]
    pub new_active_pubkey: Vec<u8>,
    /// The custody type being migrated to.
    pub target_custody_type: CustodyMigrationTarget,
    /// Unix timestamp (milliseconds) when the migration was requested.
    pub requested_at: u64,
}

// ---------------------------------------------------------------------------
// CustodyMigrationStep
// ---------------------------------------------------------------------------

/// The current step in the custody migration protocol.
///
/// Migration is a 5-step process. Each step must complete before the next
/// can begin. If any step fails, the migration is rolled back to the
/// previous custody state.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CustodyMigrationStep {
    /// Step 1: Migration requested, new key generated by target provider.
    Requested,
    /// Step 2: Current active key has signed the migration request.
    Authorized,
    /// Step 3: DID document updated with new `#active` verification method.
    Rotated,
    /// Step 4: UCAN tokens reissued under the new active key.
    Reissued,
    /// Step 5: Old key material destroyed in previous custody provider.
    Completed,
}

// ---------------------------------------------------------------------------
// CustodyMigrationStatus
// ---------------------------------------------------------------------------

/// Status of an in-progress or completed custody migration.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CustodyMigrationStatus {
    /// The migration request that initiated this migration.
    pub request: CustodyMigrationRequest,
    /// The current step in the migration protocol.
    pub current_step: CustodyMigrationStep,
    /// Unix timestamp (milliseconds) when the current step was reached.
    pub step_reached_at: u64,
    /// If the migration failed, a description of the failure.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
}

// ---------------------------------------------------------------------------
// CustodyMigrationError — orchestrator-level error
// ---------------------------------------------------------------------------

/// Errors produced by the custody migration orchestrator.
///
/// Step 1 (key generation) and step 2 (authorization) failures are fatal —
/// the orchestrator cannot proceed without valid key material and consent.
/// Steps 3–5 failures are recorded in `CustodyMigrationResult::failure_reason`.
#[derive(Debug, thiserror::Error)]
pub enum CustodyMigrationError {
    /// Step 1 failed: new key generation in target custody provider.
    #[error("key generation failed (step 1): {0}")]
    KeyGenerationFailed(String),

    /// Step 2 failed: authorization by current keys.
    #[error("authorization failed (step 2): {0}")]
    AuthorizationFailed(String),

    /// Step 3 failed: DID document rotation.
    #[error("DID document rotation failed (step 3): {0}")]
    RotationFailed(String),

    /// Step 4 failed: UCAN revocation and reissuance.
    #[error("UCAN reissuance failed (step 4): {0}")]
    ReissuanceFailed(String),

    /// Step 5 failed: old key destruction.
    ///
    /// This is non-fatal per spec §3.2.1: "The migration is still complete —
    /// the DID document references the new key. The old key is orphaned but
    /// harmless."
    #[error("old key destruction failed (step 5): {0}")]
    DestructionFailed(String),

    /// The new active public key is invalid (wrong length).
    #[error("invalid new active public key: expected 32 bytes, got {0}")]
    InvalidPublicKey(usize),
}

// ---------------------------------------------------------------------------
// CustodyMigrationResult — outcome of the full migration
// ---------------------------------------------------------------------------

/// Outcome of executing the custody migration protocol.
///
/// Contains the final status of each step. The DID is unchanged (custody
/// migration preserves the DID string by design — only `#active` rotates).
///
/// See spec §3.2.1.
#[allow(clippy::struct_excessive_bools)]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CustodyMigrationResult {
    /// The DID that underwent custody migration (unchanged).
    pub did: DID,

    /// The target custody type that was migrated to.
    pub target: CustodyMigrationTarget,

    /// Whether step 1 (key generation) completed.
    pub key_generated: bool,

    /// Whether step 2 (authorization) completed.
    pub authorized: bool,

    /// Whether step 3 (DID document rotation) completed.
    pub did_document_rotated: bool,

    /// Whether step 4 (UCAN reissuance + attestation re-sign) completed.
    pub ucans_reissued: bool,

    /// Whether step 5 (old key destruction) completed.
    ///
    /// `false` is non-fatal per spec §3.2.1 — the old key is orphaned but
    /// harmless since UCAN tokens signed by it are revoked and the DID
    /// document references the new key.
    pub old_key_destroyed: bool,

    /// Contexts where MLS Update proposals were issued successfully.
    pub updated_contexts: Vec<String>,

    /// Contexts where MLS Update failed.
    pub failed_contexts: Vec<String>,

    /// Unix timestamp (milliseconds) when migration was initiated.
    pub initiated_at: u64,

    /// Unix timestamp (milliseconds) when migration completed.
    pub completed_at: u64,

    /// If the migration failed at any step, the reason.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
}

// ---------------------------------------------------------------------------
// CustodyMigrationBackend — trait for platform-specific migration operations
// ---------------------------------------------------------------------------

/// Backend trait for platform-specific custody migration operations.
///
/// The orchestrator defines step ordering and rollback semantics; the backend
/// provides the concrete key generation, DID document update, UCAN
/// revocation, MLS update, attestation re-sign, and key destruction
/// operations.
///
/// SDK integration layers implement this trait to wire the orchestrator into
/// the actual custody provider, DID document publisher, and UCAN store.
///
/// See spec §3.2.1.
pub trait CustodyMigrationBackend {
    /// Step 1: Generate a new Ed25519 keypair in the target custody provider.
    ///
    /// Returns the 32-byte public key of the newly generated keypair.
    ///
    /// # Errors
    ///
    /// Returns a description string if key generation fails.
    fn generate_key(&self, target: CustodyMigrationTarget) -> Result<Vec<u8>, String>;

    /// Step 2: Authorize the migration by signing the request with the
    /// current `#active` and `#0` keys.
    ///
    /// The backend verifies that the request was initiated by the identity
    /// owner (device-local authentication) and signs the request.
    ///
    /// # Errors
    ///
    /// Returns a description string if authorization fails.
    fn authorize(&self, request: &CustodyMigrationRequest) -> Result<(), String>;

    /// Step 3: Update the DID document with the new `#active` verification
    /// method, sign with `#0`, and publish to both resolution layers.
    ///
    /// Also issues MLS Update proposals in the given context IDs.
    ///
    /// Returns a tuple of (`succeeded_context_ids`, `failed_context_ids`).
    ///
    /// # Errors
    ///
    /// Returns a description string if the DID document update itself fails.
    /// Per-context MLS Update failures are returned in the failed list, not
    /// as errors.
    fn rotate_did_document(
        &self,
        did: &DID,
        request: &CustodyMigrationRequest,
        context_ids: &[String],
    ) -> Result<(Vec<String>, Vec<String>), String>;

    /// Step 4: Revoke all UCAN tokens signed by the old `#active` key and
    /// reissue them under the new key. Also re-sign attestations.
    ///
    /// # Errors
    ///
    /// Returns a description string if revocation or reissuance fails.
    fn reissue_credentials(
        &self,
        did: &DID,
        request: &CustodyMigrationRequest,
    ) -> Result<(), String>;

    /// Step 5: Destroy the old `#active` key material in the source custody
    /// provider.
    ///
    /// This step verifies DID document propagation before destruction:
    /// the updated document must be resolvable from at least one relay and
    /// DHT node.
    ///
    /// # Errors
    ///
    /// Returns a description string if destruction fails. This is non-fatal
    /// per spec §3.2.1.
    fn destroy_old_key(&self, did: &DID) -> Result<(), String>;
}

// ---------------------------------------------------------------------------
// CustodyMigrationOrchestrator
// ---------------------------------------------------------------------------

/// Orchestrates the 5-step custody migration protocol (§3.2.1).
///
/// The orchestrator coordinates key generation, authorization, DID document
/// rotation, UCAN reissuance, attestation re-signing, and old key destruction
/// in dependency order. Each step must complete before the next begins.
///
/// Step operations are delegated to a [`CustodyMigrationBackend`]
/// implementation, which provides platform-specific custody, DID, and UCAN
/// operations.
///
/// # Failure semantics (per spec §3.2.1)
///
/// - Step 1 or 2 failure: No state change. Abort cleanly.
/// - Step 3 failure (partial publication): Safe — peers with old document
///   continue to work. The `RepublishManager` converges on retry.
/// - Step 4 failure: The SDK queues failed operations for retry.
/// - Step 5 failure: Non-fatal — old key is orphaned but harmless.
///
/// # Usage
///
/// ```rust,ignore
/// let backend = MyMigrationBackend::new(/* ... */);
/// let orchestrator = CustodyMigrationOrchestrator::new(
///     did.clone(),
///     CustodyMigrationTarget::OsKeystore,
///     vec!["ctx-1".into(), "ctx-2".into()],
/// );
/// let result = orchestrator.execute(&backend, &clock).await?;
/// ```
///
/// See spec §3.2.1 (Key Custody Migration Protocol).
pub struct CustodyMigrationOrchestrator {
    /// The DID performing custody migration.
    did: DID,

    /// The target custody type to migrate to.
    target: CustodyMigrationTarget,

    /// Active context IDs where MLS Update proposals should be issued.
    context_ids: Vec<String>,
}

impl CustodyMigrationOrchestrator {
    /// Creates a new orchestrator for the given DID and target custody type.
    ///
    /// # Arguments
    ///
    /// * `did` — The DID performing custody migration.
    /// * `target` — The target custody type to migrate to.
    /// * `context_ids` — All context IDs where this DID is an active member.
    #[must_use]
    pub const fn new(did: DID, target: CustodyMigrationTarget, context_ids: Vec<String>) -> Self {
        Self {
            did,
            target,
            context_ids,
        }
    }

    /// Executes the full 5-step custody migration protocol.
    ///
    /// Steps execute in strict dependency order: 1→2→3→4→5.
    ///
    /// If steps 1 or 2 fail, the migration aborts with no state change and
    /// returns the corresponding [`CustodyMigrationError`].
    ///
    /// If step 3 fails at the DID document level, the migration aborts.
    /// Per-context MLS Update failures within step 3 are recorded in
    /// `CustodyMigrationResult::failed_contexts` but do not abort the
    /// migration.
    ///
    /// If step 4 fails, the error is recorded but the migration result is
    /// still returned (the DID document already points to the new key).
    ///
    /// If step 5 fails, the error is recorded but the migration is considered
    /// successful — the old key is orphaned but harmless per spec §3.2.1.
    ///
    /// # Errors
    ///
    /// Returns [`CustodyMigrationError`] for fatal failures in steps 1–3.
    /// Steps 4–5 failures are recorded in the result, not as errors.
    #[allow(clippy::unused_async)] // async by design: SDK integration layer adds await points
    #[allow(clippy::future_not_send)] // backend trait object is not Sync by design
    pub async fn execute(
        &self,
        backend: &dyn CustodyMigrationBackend,
        clock: &dyn Clock,
    ) -> Result<CustodyMigrationResult, CustodyMigrationError> {
        let initiated_at = clock.now_millis();

        // Step 1: Generate new key in target custody provider.
        let new_pubkey = backend
            .generate_key(self.target)
            .map_err(CustodyMigrationError::KeyGenerationFailed)?;

        // Validate key length.
        if new_pubkey.len() != 32 {
            return Err(CustodyMigrationError::InvalidPublicKey(new_pubkey.len()));
        }

        let request = CustodyMigrationRequest {
            new_active_pubkey: new_pubkey,
            target_custody_type: self.target,
            requested_at: initiated_at,
        };

        // Step 2: Authorize the migration.
        backend
            .authorize(&request)
            .map_err(CustodyMigrationError::AuthorizationFailed)?;

        // Step 3: Rotate the DID document and issue MLS Update proposals.
        let (updated_contexts, failed_contexts) = backend
            .rotate_did_document(&self.did, &request, &self.context_ids)
            .map_err(CustodyMigrationError::RotationFailed)?;

        // Step 4: Revoke old UCANs and reissue under new key, re-sign
        // attestations. Failure here is recorded but does not abort — the
        // DID document already points to the new key.
        let mut failure_reason: Option<String> = None;
        let ucans_reissued = match backend.reissue_credentials(&self.did, &request) {
            Ok(()) => true,
            Err(reason) => {
                failure_reason = Some(format!("UCAN reissuance failed (step 4): {reason}"));
                false
            }
        };

        // Step 5: Destroy old key material. Non-fatal per spec §3.2.1.
        let old_key_destroyed = match backend.destroy_old_key(&self.did) {
            Ok(()) => true,
            Err(reason) => {
                let step5_msg = format!("old key destruction failed (step 5, non-fatal): {reason}");
                failure_reason = Some(match failure_reason {
                    Some(existing) => format!("{existing}; {step5_msg}"),
                    None => step5_msg,
                });
                false
            }
        };

        let completed_at = clock.now_millis();

        Ok(CustodyMigrationResult {
            did: self.did.clone(),
            target: self.target,
            key_generated: true,
            authorized: true,
            did_document_rotated: true,
            ucans_reissued,
            old_key_destroyed,
            updated_contexts,
            failed_contexts,
            initiated_at,
            completed_at,
            failure_reason,
        })
    }

    /// Returns the DID this orchestrator is migrating.
    #[must_use]
    pub const fn did(&self) -> &DID {
        &self.did
    }

    /// Returns the target custody type.
    #[must_use]
    pub const fn target(&self) -> CustodyMigrationTarget {
        self.target
    }

    /// Returns the context IDs included in migration.
    #[must_use]
    pub fn context_ids(&self) -> &[String] {
        &self.context_ids
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    fn did(s: &str) -> DID {
        DID::from(s)
    }

    // -----------------------------------------------------------------------
    // Mock backend for testing
    // -----------------------------------------------------------------------

    /// A mock `CustodyMigrationBackend` that succeeds for all operations by
    /// default. Individual steps can be configured to fail.
    struct MockMigrationBackend {
        /// If set, `generate_key` returns this error.
        generate_key_error: Option<String>,
        /// The public key to return from `generate_key`.
        generated_pubkey: Vec<u8>,
        /// If set, `authorize` returns this error.
        authorize_error: Option<String>,
        /// If set, `rotate_did_document` returns this error.
        rotate_error: Option<String>,
        /// Contexts that fail during MLS Update in step 3.
        mls_failed_contexts: Vec<String>,
        /// If set, `reissue_credentials` returns this error.
        reissue_error: Option<String>,
        /// If set, `destroy_old_key` returns this error.
        destroy_error: Option<String>,
    }

    impl MockMigrationBackend {
        fn new() -> Self {
            Self {
                generate_key_error: None,
                generated_pubkey: vec![0xAA; 32],
                authorize_error: None,
                rotate_error: None,
                mls_failed_contexts: Vec::new(),
                reissue_error: None,
                destroy_error: None,
            }
        }
    }

    impl CustodyMigrationBackend for MockMigrationBackend {
        fn generate_key(&self, _target: CustodyMigrationTarget) -> Result<Vec<u8>, String> {
            if let Some(ref err) = self.generate_key_error {
                return Err(err.clone());
            }
            Ok(self.generated_pubkey.clone())
        }

        fn authorize(&self, _request: &CustodyMigrationRequest) -> Result<(), String> {
            if let Some(ref err) = self.authorize_error {
                return Err(err.clone());
            }
            Ok(())
        }

        fn rotate_did_document(
            &self,
            _did: &DID,
            _request: &CustodyMigrationRequest,
            context_ids: &[String],
        ) -> Result<(Vec<String>, Vec<String>), String> {
            if let Some(ref err) = self.rotate_error {
                return Err(err.clone());
            }
            let mut succeeded = Vec::new();
            let mut failed = Vec::new();
            for ctx in context_ids {
                if self.mls_failed_contexts.contains(ctx) {
                    failed.push(ctx.clone());
                } else {
                    succeeded.push(ctx.clone());
                }
            }
            Ok((succeeded, failed))
        }

        fn reissue_credentials(
            &self,
            _did: &DID,
            _request: &CustodyMigrationRequest,
        ) -> Result<(), String> {
            if let Some(ref err) = self.reissue_error {
                return Err(err.clone());
            }
            Ok(())
        }

        fn destroy_old_key(&self, _did: &DID) -> Result<(), String> {
            if let Some(ref err) = self.destroy_error {
                return Err(err.clone());
            }
            Ok(())
        }
    }

    // -----------------------------------------------------------------------
    // CustodyMigrationRequest tests
    // -----------------------------------------------------------------------

    #[test]
    fn custody_migration_request_construction() {
        let req = CustodyMigrationRequest {
            new_active_pubkey: vec![0xAA; 32],
            target_custody_type: CustodyMigrationTarget::OsKeystore,
            requested_at: 1_700_000_000_000,
        };

        assert_eq!(req.new_active_pubkey.len(), 32);
        assert_eq!(req.target_custody_type, CustodyMigrationTarget::OsKeystore);
        assert_eq!(req.requested_at, 1_700_000_000_000);
    }

    #[test]
    fn custody_migration_request_serialization_roundtrip() {
        let req = CustodyMigrationRequest {
            new_active_pubkey: vec![0xBB; 32],
            target_custody_type: CustodyMigrationTarget::OsKeystore,
            requested_at: 1_700_100_000_000,
        };

        let json = serde_json::to_string(&req).unwrap();
        let deserialized: CustodyMigrationRequest = serde_json::from_str(&json).unwrap();
        assert_eq!(req, deserialized);
    }

    #[test]
    fn custody_migration_target_variants_are_distinct() {
        assert_ne!(
            CustodyMigrationTarget::EncryptedFile,
            CustodyMigrationTarget::OsKeystore
        );
        assert_eq!(
            CustodyMigrationTarget::OsKeystore,
            CustodyMigrationTarget::OsKeystore
        );
    }

    #[test]
    fn custody_migration_step_ordering() {
        let steps = [
            CustodyMigrationStep::Requested,
            CustodyMigrationStep::Authorized,
            CustodyMigrationStep::Rotated,
            CustodyMigrationStep::Reissued,
            CustodyMigrationStep::Completed,
        ];
        for (i, a) in steps.iter().enumerate() {
            for (j, b) in steps.iter().enumerate() {
                if i == j {
                    assert_eq!(a, b);
                } else {
                    assert_ne!(a, b);
                }
            }
        }
    }

    #[test]
    fn custody_migration_status_construction_and_roundtrip() {
        let status = CustodyMigrationStatus {
            request: CustodyMigrationRequest {
                new_active_pubkey: vec![0xCC; 32],
                target_custody_type: CustodyMigrationTarget::EncryptedFile,
                requested_at: 1_700_200_000_000,
            },
            current_step: CustodyMigrationStep::Rotated,
            step_reached_at: 1_700_200_100_000,
            failure_reason: None,
        };

        let json = serde_json::to_string(&status).unwrap();
        let deserialized: CustodyMigrationStatus = serde_json::from_str(&json).unwrap();
        assert_eq!(status, deserialized);
    }

    #[test]
    fn custody_migration_status_with_failure() {
        let status = CustodyMigrationStatus {
            request: CustodyMigrationRequest {
                new_active_pubkey: vec![0xDD; 32],
                target_custody_type: CustodyMigrationTarget::OsKeystore,
                requested_at: 1_700_300_000_000,
            },
            current_step: CustodyMigrationStep::Authorized,
            step_reached_at: 1_700_300_050_000,
            failure_reason: Some("DID document update rejected by relay".to_owned()),
        };

        let json = serde_json::to_string(&status).unwrap();
        assert!(json.contains("DID document update rejected"));
        let deserialized: CustodyMigrationStatus = serde_json::from_str(&json).unwrap();
        assert_eq!(status, deserialized);
    }

    #[test]
    fn custody_migration_target_serialization_roundtrip() {
        let targets = [
            (CustodyMigrationTarget::EncryptedFile, "\"encrypted_file\""),
            (CustodyMigrationTarget::OsKeystore, "\"os_keystore\""),
        ];

        for (target, wire) in targets {
            let json = serde_json::to_string(&target).unwrap();
            assert_eq!(json, wire);
            let deserialized: CustodyMigrationTarget = serde_json::from_str(&json).unwrap();
            assert_eq!(target, deserialized);
        }
    }

    #[test]
    fn custody_migration_target_rejects_the_retired_wire_strings() {
        for retired in [
            "\"platform_managed\"",
            "\"hardware\"",
            "\"software\"",
            "\"in_memory\"",
        ] {
            assert!(
                serde_json::from_str::<CustodyMigrationTarget>(retired).is_err(),
                "the request-side vocabulary must no longer parse {retired}"
            );
        }
    }

    #[test]
    fn custody_migration_step_serialization_roundtrip() {
        let steps = [
            CustodyMigrationStep::Requested,
            CustodyMigrationStep::Authorized,
            CustodyMigrationStep::Rotated,
            CustodyMigrationStep::Reissued,
            CustodyMigrationStep::Completed,
        ];

        for step in &steps {
            let json = serde_json::to_string(step).unwrap();
            let deserialized: CustodyMigrationStep = serde_json::from_str(&json).unwrap();
            assert_eq!(step, &deserialized);
        }
    }

    // -----------------------------------------------------------------------
    // CustodyMigrationResult tests
    // -----------------------------------------------------------------------

    #[test]
    fn custody_migration_result_serialization_roundtrip() {
        let result = CustodyMigrationResult {
            did: did("did:dht:alice"),
            target: CustodyMigrationTarget::OsKeystore,
            key_generated: true,
            authorized: true,
            did_document_rotated: true,
            ucans_reissued: true,
            old_key_destroyed: true,
            updated_contexts: vec!["ctx-1".to_owned()],
            failed_contexts: vec![],
            initiated_at: 1000,
            completed_at: 2000,
            failure_reason: None,
        };

        let json = serde_json::to_string(&result).unwrap();
        let parsed: CustodyMigrationResult = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.did, result.did);
        assert_eq!(parsed.target, result.target);
        assert_eq!(parsed.updated_contexts, result.updated_contexts);
    }

    #[test]
    fn custody_migration_result_msgpack_roundtrip() {
        let result = CustodyMigrationResult {
            did: did("did:dht:bob"),
            target: CustodyMigrationTarget::EncryptedFile,
            key_generated: true,
            authorized: true,
            did_document_rotated: true,
            ucans_reissued: false,
            old_key_destroyed: false,
            updated_contexts: vec!["ctx-1".to_owned()],
            failed_contexts: vec!["ctx-2".to_owned()],
            initiated_at: 1000,
            completed_at: 2000,
            failure_reason: Some("UCAN reissuance failed (step 4): store error; old key destruction failed (step 5, non-fatal): HSM error".to_owned()),
        };

        let bytes = rmp_serde::to_vec(&result).unwrap();
        let parsed: CustodyMigrationResult = rmp_serde::from_slice(&bytes).unwrap();
        assert_eq!(parsed.target, CustodyMigrationTarget::EncryptedFile);
        assert_eq!(parsed.updated_contexts, vec!["ctx-1"]);
        assert_eq!(parsed.failed_contexts, vec!["ctx-2"]);
        assert!(parsed.failure_reason.is_some());
    }

    // -----------------------------------------------------------------------
    // CustodyMigrationOrchestrator — accessors
    // -----------------------------------------------------------------------

    #[test]
    fn orchestrator_accessors() {
        let orch = CustodyMigrationOrchestrator::new(
            did("did:dht:alice"),
            CustodyMigrationTarget::OsKeystore,
            vec!["ctx-1".to_owned(), "ctx-2".to_owned()],
        );
        assert_eq!(*orch.did(), did("did:dht:alice"));
        assert_eq!(orch.target(), CustodyMigrationTarget::OsKeystore);
        assert_eq!(orch.context_ids().len(), 2);
    }

    // -----------------------------------------------------------------------
    // CustodyMigrationOrchestrator — execute tests
    // -----------------------------------------------------------------------

    #[tokio::test]
    async fn migration_all_steps_succeed() {
        let orch = CustodyMigrationOrchestrator::new(
            did("did:dht:alice"),
            CustodyMigrationTarget::OsKeystore,
            vec!["ctx-1".to_owned(), "ctx-2".to_owned()],
        );

        let backend = MockMigrationBackend::new();

        let result = orch
            .execute(&backend, &scp_clock::SystemClock)
            .await
            .unwrap();

        assert_eq!(result.did, did("did:dht:alice"));
        assert_eq!(result.target, CustodyMigrationTarget::OsKeystore);
        assert!(result.key_generated);
        assert!(result.authorized);
        assert!(result.did_document_rotated);
        assert!(result.ucans_reissued);
        assert!(result.old_key_destroyed);
        assert_eq!(result.updated_contexts.len(), 2);
        assert!(result.failed_contexts.is_empty());
        assert!(result.failure_reason.is_none());
        assert!(result.completed_at >= result.initiated_at);
    }

    #[tokio::test]
    async fn migration_no_contexts() {
        let orch = CustodyMigrationOrchestrator::new(
            did("did:dht:alice"),
            CustodyMigrationTarget::EncryptedFile,
            vec![],
        );

        let backend = MockMigrationBackend::new();
        let result = orch
            .execute(&backend, &scp_clock::SystemClock)
            .await
            .unwrap();

        assert!(result.updated_contexts.is_empty());
        assert!(result.failed_contexts.is_empty());
        assert!(result.ucans_reissued);
        assert!(result.old_key_destroyed);
    }

    #[tokio::test]
    async fn migration_step1_fails_key_generation() {
        let orch = CustodyMigrationOrchestrator::new(
            did("did:dht:alice"),
            CustodyMigrationTarget::OsKeystore,
            vec!["ctx-1".to_owned()],
        );

        let backend = MockMigrationBackend {
            generate_key_error: Some("HSM initialization failed".to_owned()),
            ..MockMigrationBackend::new()
        };

        let err = orch
            .execute(&backend, &scp_clock::SystemClock)
            .await
            .unwrap_err();
        assert!(matches!(err, CustodyMigrationError::KeyGenerationFailed(_)));
        assert!(err.to_string().contains("HSM initialization failed"));
    }

    #[tokio::test]
    async fn migration_step1_fails_invalid_key_length() {
        let orch = CustodyMigrationOrchestrator::new(
            did("did:dht:alice"),
            CustodyMigrationTarget::OsKeystore,
            vec![],
        );

        let backend = MockMigrationBackend {
            generated_pubkey: vec![0xAA; 16], // Wrong length
            ..MockMigrationBackend::new()
        };

        let err = orch
            .execute(&backend, &scp_clock::SystemClock)
            .await
            .unwrap_err();
        assert!(matches!(err, CustodyMigrationError::InvalidPublicKey(16)));
    }

    #[tokio::test]
    async fn migration_step2_fails_authorization() {
        let orch = CustodyMigrationOrchestrator::new(
            did("did:dht:alice"),
            CustodyMigrationTarget::OsKeystore,
            vec!["ctx-1".to_owned()],
        );

        let backend = MockMigrationBackend {
            authorize_error: Some("biometric verification failed".to_owned()),
            ..MockMigrationBackend::new()
        };

        let err = orch
            .execute(&backend, &scp_clock::SystemClock)
            .await
            .unwrap_err();
        assert!(matches!(err, CustodyMigrationError::AuthorizationFailed(_)));
        assert!(err.to_string().contains("biometric verification failed"));
    }

    #[tokio::test]
    async fn migration_step3_fails_did_document_rotation() {
        let orch = CustodyMigrationOrchestrator::new(
            did("did:dht:alice"),
            CustodyMigrationTarget::OsKeystore,
            vec!["ctx-1".to_owned()],
        );

        let backend = MockMigrationBackend {
            rotate_error: Some("DHT publication failed".to_owned()),
            ..MockMigrationBackend::new()
        };

        let err = orch
            .execute(&backend, &scp_clock::SystemClock)
            .await
            .unwrap_err();
        assert!(matches!(err, CustodyMigrationError::RotationFailed(_)));
    }

    #[tokio::test]
    async fn migration_step3_partial_mls_failures() {
        let orch = CustodyMigrationOrchestrator::new(
            did("did:dht:alice"),
            CustodyMigrationTarget::OsKeystore,
            vec!["ctx-1".to_owned(), "ctx-2".to_owned(), "ctx-3".to_owned()],
        );

        let backend = MockMigrationBackend {
            mls_failed_contexts: vec!["ctx-2".to_owned()],
            ..MockMigrationBackend::new()
        };

        let result = orch
            .execute(&backend, &scp_clock::SystemClock)
            .await
            .unwrap();

        assert_eq!(result.updated_contexts, vec!["ctx-1", "ctx-3"]);
        assert_eq!(result.failed_contexts, vec!["ctx-2"]);
        assert!(result.did_document_rotated);
        // Step 3 partial MLS failure does not prevent steps 4 and 5.
        assert!(result.ucans_reissued);
        assert!(result.old_key_destroyed);
    }

    #[tokio::test]
    async fn migration_step4_fails_ucan_reissuance() {
        let orch = CustodyMigrationOrchestrator::new(
            did("did:dht:alice"),
            CustodyMigrationTarget::EncryptedFile,
            vec!["ctx-1".to_owned()],
        );

        let backend = MockMigrationBackend {
            reissue_error: Some("UCAN store error".to_owned()),
            ..MockMigrationBackend::new()
        };

        // Step 4 failure is non-fatal — result is returned, not error.
        let result = orch
            .execute(&backend, &scp_clock::SystemClock)
            .await
            .unwrap();
        assert!(!result.ucans_reissued);
        assert!(result.did_document_rotated);
        assert!(result.old_key_destroyed);
        assert!(result.failure_reason.is_some());
        let reason = result.failure_reason.as_ref().unwrap();
        assert!(
            reason.contains("UCAN reissuance failed (step 4): UCAN store error"),
            "expected backend error in failure_reason, got: {reason}"
        );
    }

    #[tokio::test]
    async fn migration_step5_fails_key_destruction() {
        let orch = CustodyMigrationOrchestrator::new(
            did("did:dht:alice"),
            CustodyMigrationTarget::OsKeystore,
            vec!["ctx-1".to_owned()],
        );

        let backend = MockMigrationBackend {
            destroy_error: Some("HSM does not support explicit deletion".to_owned()),
            ..MockMigrationBackend::new()
        };

        // Step 5 failure is non-fatal per spec §3.2.1.
        let result = orch
            .execute(&backend, &scp_clock::SystemClock)
            .await
            .unwrap();
        assert!(!result.old_key_destroyed);
        assert!(result.ucans_reissued);
        assert!(result.did_document_rotated);
        assert!(result.failure_reason.is_some());
        let reason = result.failure_reason.as_ref().unwrap();
        assert!(
            reason.contains("old key destruction failed (step 5, non-fatal): HSM does not support explicit deletion"),
            "expected backend error in failure_reason, got: {reason}"
        );
    }

    #[tokio::test]
    async fn migration_steps4_and_5_both_fail() {
        let orch = CustodyMigrationOrchestrator::new(
            did("did:dht:alice"),
            CustodyMigrationTarget::OsKeystore,
            vec![],
        );

        let backend = MockMigrationBackend {
            reissue_error: Some("UCAN error".to_owned()),
            destroy_error: Some("HSM error".to_owned()),
            ..MockMigrationBackend::new()
        };

        let result = orch
            .execute(&backend, &scp_clock::SystemClock)
            .await
            .unwrap();
        assert!(!result.ucans_reissued);
        assert!(!result.old_key_destroyed);
        assert!(result.failure_reason.is_some());
        let reason = result.failure_reason.as_ref().unwrap();
        assert!(
            reason.contains("UCAN reissuance failed (step 4): UCAN error"),
            "expected step 4 backend error in failure_reason, got: {reason}"
        );
        assert!(
            reason.contains("old key destruction failed (step 5, non-fatal): HSM error"),
            "expected step 5 backend error in failure_reason, got: {reason}"
        );
    }

    #[tokio::test]
    async fn migration_all_custody_targets() {
        for target in [
            CustodyMigrationTarget::EncryptedFile,
            CustodyMigrationTarget::OsKeystore,
        ] {
            let orch = CustodyMigrationOrchestrator::new(
                did("did:dht:alice"),
                target,
                vec!["ctx-1".to_owned()],
            );

            let backend = MockMigrationBackend::new();
            let result = orch
                .execute(&backend, &scp_clock::SystemClock)
                .await
                .unwrap();

            assert_eq!(result.target, target);
            assert!(result.key_generated);
            assert!(result.authorized);
            assert!(result.did_document_rotated);
        }
    }

    // -----------------------------------------------------------------------
    // CustodyMigrationError tests
    // -----------------------------------------------------------------------

    #[test]
    fn custody_migration_error_display() {
        let errors = [
            (
                CustodyMigrationError::KeyGenerationFailed("HSM error".to_owned()),
                "key generation failed (step 1): HSM error",
            ),
            (
                CustodyMigrationError::AuthorizationFailed("denied".to_owned()),
                "authorization failed (step 2): denied",
            ),
            (
                CustodyMigrationError::RotationFailed("DHT down".to_owned()),
                "DID document rotation failed (step 3): DHT down",
            ),
            (
                CustodyMigrationError::ReissuanceFailed("store error".to_owned()),
                "UCAN reissuance failed (step 4): store error",
            ),
            (
                CustodyMigrationError::DestructionFailed("no support".to_owned()),
                "old key destruction failed (step 5): no support",
            ),
            (
                CustodyMigrationError::InvalidPublicKey(16),
                "invalid new active public key: expected 32 bytes, got 16",
            ),
        ];

        for (err, expected) in &errors {
            assert_eq!(err.to_string(), *expected);
        }
    }
}
