//! SQLCipher storage adapter for Android.
//!
//! The Kotlin class `AndroidStorage` in
//! `bindings/kotlin/scp-kt-android/.../AndroidStorage.kt` implements the
//! Kotlin `StorageProvider` interface in `Types.kt`, not [`Storage`]
//! (ADR-021); the [`super`] module docs list where the two differ. No code
//! injects the Kotlin adapter into the Rust engine yet. This module documents
//! the Rust-side contract and re-exports the trait type for Android builds.
//!
//! # Encryption Architecture (ADR-027)
//!
//! SQLCipher provides transparent full-database encryption. The encryption key
//! is a 32-byte AES-256 key generated by Android Keystore (TEE-backed). The
//! Keystore key never leaves the TEE; it encrypts a fixed label via AES-GCM to
//! produce a deterministic passphrase for SQLCipher. This gives the database a
//! hardware-rooted chain of trust.
//!
//! See ADR-027 in `.docs/adrs/phase-6.md` for the full design rationale.

pub use crate::traits::Storage;
