//! SQLCipher [`Storage`] adapter for Android.
//!
//! The Android storage adapter is implemented in Kotlin at
//! `bindings/kotlin/scp-sdk-kotlin-android/.../AndroidStorage.kt` and injected
//! into the Rust engine via the UniFFI callback interface (ADR-021). This module
//! documents the Rust-side contract and re-exports the trait types that the
//! Kotlin adapter implements.
//!
//! # Encryption Architecture (ADR-027)
//!
//! SQLCipher provides transparent full-database encryption. The encryption key
//! is a 32-byte AES-256 key generated by Android Keystore (TEE-backed). The
//! Keystore key never leaves the TEE; it encrypts a fixed label via AES-GCM to
//! produce a deterministic passphrase for SQLCipher. This gives the database a
//! hardware-rooted chain of trust.
//!
//! See ADR-027 in `.docs/adrs/phase-6.md` for the full design rationale.

pub use crate::traits::Storage;
