"""Type stubs for the ``_scp_core`` PyO3 extension module.

This file provides Python type annotations for all classes, functions, and
exceptions exposed by the Rust bridge layer (``crates/scp-ffi/src/``). It
enables IDE autocompletion (VS Code, PyCharm) and static analysis via
mypy/pyright.

DO NOT HAND-EDIT the function/method parameter lists. The positional
parameter names, order, and arity of every exported function are generated
from the authoritative PyO3 signatures by ``scripts/generate-pyi.py`` and
enforced in CI by ``scripts/check-pyi-generated.sh`` (which fails on any
drift). To change a signature, edit the Rust ``#[pyfunction]`` /
``#[pymethods]`` export, then run ``python3.12 scripts/generate-pyi.py`` and
commit the regenerated stub. Prose (docstrings, section comments, value
classes, property blocks) is preserved verbatim and may be edited by hand.

Generated from the Rust source in ``crates/scp-ffi/src/``. See ADR-013
in ``.docs/adrs/phase-3.md`` for the full bridge specification.

Phase 4 PR 4 (#1549 façade deletion) consolidated the per-operation
``py_*`` free functions into methods on :class:`SCP`. The remaining
free functions below are pure helpers or lifecycle hooks that do not
depend on a bridge instance. The rest of the stub surface lives on
:class:`SCP`.
"""

from __future__ import annotations

from asyncio import Future
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from scp_sdk.scp import McpAllowlistState

# ---------------------------------------------------------------------------
# Exception hierarchy
# ---------------------------------------------------------------------------
# Mirrors the exception classes created via pyo3::create_exception! in
# crates/scp-ffi/src/error.rs.
#
# Hierarchy:
#   Exception
#   +-- ScpError
#       +-- IdentityError
#       +-- ContextError
#       +-- CryptoError
#       +-- TransportError
#       +-- UcanError
#       +-- ValidationError
#       +-- StorageError
#       +-- AttestationError
#       +-- McpError
#       +-- GovernanceError
#       +-- EconomyError

class ScpError(Exception):
    """Base exception for all SCP protocol errors."""

    ...

class IdentityError(ScpError):
    """An identity operation failed (DID creation, resolution, key rotation)."""

    ...

class ContextError(ScpError):
    """A context lifecycle operation failed (create, join, leave, close, send)."""

    ...

class CryptoError(ScpError):
    """A cryptographic operation failed (MLS, sender keys, encryption, decryption)."""

    ...

class TransportError(ScpError):
    """A transport operation failed (connection, send, subscription)."""

    ...

class UcanError(ScpError):
    """A UCAN operation failed (validation, minting, revocation)."""

    ...

class ValidationError(ScpError):
    """Input validation failed (malformed data, schema mismatch, constraint violation)."""

    ...

class StorageError(ScpError):
    """A persistent-storage operation failed (SCP-STORAGE range, 8000-8999)."""

    ...

class AttestationError(ScpError):
    """A device or identity attestation operation failed (SCP-ATTEST range, 9000-9999)."""

    ...

class McpError(ScpError):
    """An MCP protocol or tool-invocation operation failed (SCP-MCP range, 10000-10999)."""

    ...

class GovernanceError(ScpError):
    """A context governance proposal or voting operation failed (SCP-GOV range, 11000-11999)."""

    ...

class EconomyError(ScpError):
    """A payment, budget, or economic-policy operation failed (SCP-ECON range, 12000-12999)."""

    ...

# Cross-context outlet-invocation saga (§6.2.4 / ADR-049 §3a) terminal errors.
# Each carries the structured terminal datum as a positional ``args`` entry
# (``args = (message, code, datum)``), read structurally — never re-parsed
# from the message text.

class SagaAbortedError(ScpError):
    """A §6.2.4 saga aborted at a Prepare phase.

    ``args = (message, code, retry_after_ms)``: ``retry_after_ms`` is an
    ``int`` of milliseconds or ``None`` (never ``0``).
    """

    ...

class SagaNeedsRepairError(ScpError):
    """A §6.2.4 saga exhausted its Commit retries and may have diverged.

    ``args = (message, code, saga_id)``: ``saga_id`` is the durable
    operator-repair handle.
    """

    ...

class SagaBusyError(ScpError):
    """A §6.2.4 saga's participant context set overlapped an in-flight saga.

    ``args = (message, code, contended_context)``: ``contended_context`` is
    the shared context id.
    """

    ...

# ---------------------------------------------------------------------------
# Bridge value types (crates/scp-ffi/src/{identity,context,ucan,...}.rs)
# ---------------------------------------------------------------------------

class SagaResult:
    """The committed terminal of a §6.2.4 cross-context outlet-invocation saga.

    Returned by :meth:`SCP.outlet_invoke_cross_context_saga` on a ``Committed``
    terminal; every non-committed terminal raises a typed saga exception.
    """

    @property
    def saga_id(self) -> str: ...
    @property
    def receipt(self) -> bytes | None: ...
    @property
    def output(self) -> bytes | None: ...
    def __repr__(self) -> str: ...

class PyIdentity:
    """An SCP identity handle.

    Stores the DID string and custody type as safe, cloneable metadata.
    Internal key material is not exposed to Python.
    """

    @property
    def did(self) -> str: ...
    @property
    def custody(self) -> str: ...
    @property
    def has_agent_key(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class PyDIDDocument:
    """A DID Document exposed to Python."""

    @property
    def id(self) -> str: ...
    @property
    def verification_methods(self) -> list[dict[str, Any]]: ...
    @property
    def services(self) -> list[dict[str, Any]]: ...
    @property
    def also_known_as(self) -> list[str]: ...
    @property
    def authentication(self) -> list[str]: ...
    @property
    def assertion_methods(self) -> list[str]: ...

class PyContextHandle:
    """An opaque context handle returned by ``SCP.context_create``."""

    @property
    def context_id(self) -> str: ...
    @property
    def state(self) -> str: ...

class PyContextParams:
    """Context creation parameters."""

    ...

class PyMessage:
    """An incoming protocol message."""

    @property
    def sender_did(self) -> str: ...
    @property
    def payload(self) -> bytes: ...
    @property
    def timestamp(self) -> float: ...
    @property
    def context_id(self) -> str: ...

class PyMessageReceiver:
    """Async iterator over incoming :class:`PyMessage` events."""

    def __aiter__(self) -> PyMessageReceiver: ...
    def __anext__(self) -> Future[PyMessage]: ...

class PySealedInvitation:
    """A sealed, signed invitation bundle (ADR-049 Phase 2J; FFI-02 Option A).

    The input to ``SCP.context_join_from_welcome``; produced on the creator side
    by ``SCP.invite_member``. The SDK wraps this as
    :class:`scp_sdk.SealedInvitation`.
    """

    def __init__(
        self, context_id: str, creator_did: str, enc: bytes, ciphertext: bytes
    ) -> None: ...
    @property
    def context_id(self) -> str: ...
    @property
    def creator_did(self) -> str: ...
    @property
    def enc(self) -> bytes: ...
    @property
    def ciphertext(self) -> bytes: ...

class PyInviteMemberOutcome:
    """The outcome of ``SCP.invite_member``.

    Carries the sealed ``bundle`` (a :class:`PySealedInvitation`, directly usable
    as the ``sealed`` argument to ``context_join_from_welcome``) plus
    ``delivered``. ``invite_member`` supports only ``SingleAdmin`` contexts today;
    a voting-governed context raises instead. The SDK projects this into the
    :class:`scp_sdk.Sealed` outcome.
    """

    @property
    def bundle(self) -> PySealedInvitation: ...
    @property
    def delivered(self) -> bool: ...

class UcanToken:
    """A UCAN token returned by the bridge."""

    @property
    def token_id(self) -> str: ...
    @property
    def issuer(self) -> str: ...
    @property
    def audience(self) -> str: ...
    @property
    def capabilities(self) -> list[str]: ...
    @property
    def expires_at(self) -> float | None: ...
    @property
    def proofs(self) -> list[str]: ...
    @property
    def encoded(self) -> str: ...

class TransportStatus:
    """Current transport connection status."""

    @property
    def connected(self) -> bool: ...
    @property
    def relay_url(self) -> str | None: ...
    @property
    def latency_ms(self) -> float | None: ...

class Event:
    """A single event log entry."""

    @property
    def event_type(self) -> str: ...
    @property
    def actor_did(self) -> str: ...
    @property
    def timestamp(self) -> float: ...
    @property
    def payload(self) -> Any: ...
    @property
    def sequence(self) -> int: ...

class Proof:
    """Inclusion or absence proof."""

    @property
    def verified(self) -> bool: ...
    @property
    def proof_type(self) -> str: ...
    @property
    def details(self) -> dict[str, Any]: ...

class SignedCheckpoint:
    """A signed Merkle checkpoint."""

    @property
    def context_id(self) -> str: ...
    @property
    def sender_did(self) -> str: ...
    @property
    def event_count(self) -> int: ...
    @property
    def merkle_root(self) -> str: ...
    @property
    def epoch(self) -> int: ...
    @property
    def timestamp(self) -> int: ...
    @property
    def signature(self) -> str: ...

class OutletVerificationResult:
    """Result of an outlet verification run."""

    @property
    def passed(self) -> bool: ...
    @property
    def details(self) -> dict[str, Any]: ...

class RelayHandle:
    """Handle to a running relay server (``SCP.relay_start_*``)."""

    @property
    def relay_url(self) -> str: ...
    @property
    def relay_port(self) -> int: ...
    @property
    def is_shutdown(self) -> bool: ...
    def shutdown(self) -> None: ...

class NodeHandle:
    """Handle to a running application node (``SCP.node_start_*``)."""

    @property
    def relay_url(self) -> str: ...
    @property
    def relay_port(self) -> int: ...
    @property
    def did(self) -> str: ...
    @property
    def is_shutdown(self) -> bool: ...
    def serve(self, bind_addr: str | None = None) -> str: ...
    def http_url(self) -> str | None: ...
    def shutdown(self) -> None: ...
    def enable_site_projection(self, *args: Any, **kwargs: Any) -> None: ...
    def commit_deploy(self, context_id: str, deploy_id: str) -> int: ...
    def rollback_deploy(self, context_id: str, deploy_id: str) -> None: ...
    def disable_site_projection(self, context_id: str) -> None: ...

# ---------------------------------------------------------------------------
# SCP class (Phase 4 PR 4 — #1549 façade consolidation, ADR-048)
# ---------------------------------------------------------------------------
#
# The SCP class owns a BridgeInstance and exposes every per-operation
# method that the bridge supports. Methods accept opaque handle types
# (PyIdentity, PyContextHandle, etc.) and JSON payloads; return types are
# typed as ``Any`` in this stub because the real return types vary by
# method and PyO3 surfaces them through ``#[pyclass]`` instances. See
# ``crates/scp-ffi/src/scp.rs`` for the authoritative signature.

class SCP:
    """Caller-owned SCP bridge instance (ADR-048 multi-instance).

    Storage selection is mandatory (spec §17.6): construct via
    ``SCP(config)`` / :meth:`with_storage` with an explicit storage-config
    dict. Bare ``SCP()`` raises ``TypeError`` — there is no default backend.
    Phase 4 PR 4 (#1549) removed the process-global ``default_instance``
    factory; every caller now owns an explicit bridge instance.
    """

    def __new__(cls, config: dict[str, Any]) -> SCP: ...
    @staticmethod
    def with_storage(config: dict[str, Any]) -> SCP: ...
    @property
    def instance_id(self) -> int: ...
    def suspend(self) -> None: ...
    def resume(self) -> None: ...
    def shutdown(self, timeout_millis: int) -> None: ...

    # -- access keys --
    def access_key_generate(self, context_id: Any, member_did: Any, caller_did: Any) -> Any: ...
    def access_key_restore(self, context_id: Any, member_did: Any, caller_did: Any) -> Any: ...
    def access_key_revoke(self, context_id: Any, member_did: Any, caller_did: Any) -> Any: ...

    # -- governance --
    def add_checkpoint_cosignature(
        self, handle: Any, checkpoint_json: Any, signer_did: Any, signature_hex: Any
    ) -> Any: ...
    def apply_pending_ceiling_modification(self, handle: Any, current_timestamp: Any) -> Any: ...
    def create_governance_checkpoint(
        self,
        handle: Any,
        checkpoint_seq: Any,
        merkle_root_hex: Any,
        event_count: Any,
        last_event_hash_hex: Any,
        state_snapshot_hash_hex: Any,
        creator_did: Any,
        creator_signature_hex: Any,
    ) -> Any: ...
    def finalize_close(self, handle: Any) -> Any: ...
    def governance_approve(self, handle: Any, identity_did: Any, proposal_id_hex: Any) -> Any: ...
    def governance_execute(self, handle: Any, proposal_id_hex: Any) -> Any: ...
    def governance_get_proposal(self, handle: Any, proposal_id_hex: Any) -> Any: ...
    def governance_list_proposals(self, handle: Any) -> Any: ...
    def governance_propose(self, handle: Any, identity_did: Any, action_json: Any) -> Any: ...
    def governance_reject(self, handle: Any, identity_did: Any, proposal_id_hex: Any) -> Any: ...
    def governance_withdraw(self, handle: Any, identity_did: Any, proposal_id_hex: Any) -> Any: ...
    def restore_all_contexts(self) -> Any: ...
    def restore_context(self, context_id: Any) -> Any: ...

    # -- discovery --
    def address_resolve(
        self, owner_did: Any, address: Any, known_contexts_json: Any = ...
    ) -> Any: ...
    def handle_deregister(self, discovery_context_id: Any, handle: Any, did: Any) -> Any: ...
    def handle_lookup(
        self, discovery_context_id: Any, handle: Any, type_filter: Any = ...
    ) -> Any: ...
    def handle_register(
        self,
        discovery_context_id: Any,
        handle: Any,
        target_json: Any,
        registrant_did: Any,
        description: Any = ...,
        tags: Any = ...,
    ) -> Any: ...
    def petname_apply_event(self, owner_did: Any, event_json: Any) -> Any: ...
    def petname_context_count(self, owner_did: Any) -> int: ...
    def petname_did_count(self, owner_did: Any) -> int: ...
    def petname_get_for_context(self, owner_did: Any, context_id: Any) -> Any: ...
    def petname_get_for_did(self, owner_did: Any, target_did: Any) -> Any: ...
    def petname_remove(self, owner_did: Any, target_did: Any) -> Any: ...
    def petname_remove_context(self, owner_did: Any, context_id: Any) -> Any: ...
    def petname_resolve_context(self, owner_did: Any, name: Any) -> Any: ...
    def petname_resolve_did(self, owner_did: Any, name: Any) -> Any: ...
    def petname_set(self, owner_did: Any, target_did: Any, name: Any) -> Any: ...
    def petname_set_context(self, owner_did: Any, context_id: Any, name: Any) -> Any: ...
    def scope_deregister(self, scope_context_id: Any, name: Any, did: Any) -> Any: ...
    def scope_lookup(self, scope_context_id: Any, name: Any) -> Any: ...
    def scope_register(
        self,
        scope_context_id: Any,
        name: Any,
        target_context_id: Any,
        relay_urls: Any,
        registrant_did: Any,
        description: Any = ...,
        tags: Any = ...,
    ) -> Any: ...

    # -- bridge connector / shadow --
    def bridge_create_shadow(
        self, bridge_id: Any, platform_handle: Any, bridge_mode: Any, context_id: Any = ...
    ) -> Any: ...
    def bridge_credential_delete_key(self, bridge_id: Any) -> Any: ...
    def bridge_credential_get_key(self, bridge_id: Any) -> Any: ...
    def bridge_credential_list(self, bridge_id: Any) -> Any: ...
    def bridge_credential_provision(
        self, bridge_id: Any, credential_type: Any, plaintext: Any, bridge_credential_key: Any
    ) -> Any: ...
    def bridge_credential_retrieve(
        self, bridge_id: Any, credential_type: Any, bridge_credential_key: Any
    ) -> Any: ...
    def bridge_credential_revoke(self, bridge_id: Any) -> Any: ...
    def bridge_credential_rotate(
        self, bridge_id: Any, credential_type: Any, new_plaintext: Any, bridge_credential_key: Any
    ) -> Any: ...
    def bridge_credential_store_key(self, bridge_id: Any, key: Any) -> Any: ...

    # -- broadcast --
    def broadcast_admission(self, handle: Any) -> Any: ...
    def broadcast_block_subscriber(
        self, handle: Any, subscriber_did: Any, blocker_did: Any
    ) -> Any: ...
    def broadcast_handle_key_request(
        self, handle: Any, author_did: Any, requester_did: Any, wrapping_pubkey: Any
    ) -> Any: ...
    @staticmethod
    def broadcast_open_key(sealed_json: Any, wrapping_secret: Any) -> Any: ...
    def broadcast_is_subscriber(self, handle: Any, did: Any) -> Any: ...
    def broadcast_publish(self, handle: Any, author_did: Any, payload: Any) -> Any: ...
    def broadcast_publish_asset(
        self,
        handle: Any,
        author_did: Any,
        path: Any,
        content_type: Any,
        body: Any,
        deploy_id: Any = ...,
    ) -> Any: ...
    def broadcast_publish_assets(
        self, handle: Any, author_did: Any, assets: Any, deploy_id: Any = ...
    ) -> Any: ...
    def broadcast_subscribe(
        self, handle: Any, subscriber_did: Any, messages_read_ucan_jwt: Any = None
    ) -> Any: ...
    def broadcast_subscriber_count(self, handle: Any) -> Any: ...
    def broadcast_unblock_subscriber(
        self, handle: Any, subscriber_did: Any, unblocker_did: Any
    ) -> Any: ...
    def broadcast_unsubscribe(
        self, handle: Any, subscriber_did: Any, rotate_keys: Any = ...
    ) -> Any: ...

    # -- context lifecycle --
    def configure_local_transport(self, local_did: Any) -> Any: ...
    def configure_relay_transport(self, relay_url: Any, local_did: Any) -> Any: ...
    def context_close(self, handle: Any, identity_did: Any) -> Any: ...
    def context_create(self, identity_did: Any, params: Any) -> Any: ...
    def context_drain_events(self, handle: Any) -> Any: ...
    def context_export(self, context_id: Any) -> Any: ...
    def context_handle_ttl_expiry(self, handle: Any) -> Any: ...
    def context_import(self, data: Any, importer_did: Any) -> Any: ...
    def context_is_member(self, handle: Any, did: Any) -> Any: ...
    def context_join(self, handle: Any, identity_did: Any, spending_ucan_jwt: Any = ...) -> Any: ...
    def context_join_from_welcome(
        self, owning_did: Any, sealed: PySealedInvitation, reservation_id: Any
    ) -> Any: ...
    def invite_member(
        self,
        context_id: Any,
        creator_did: Any,
        invitee_did: Any,
        invitee_key_package: Any,
        relay_urls: Any,
    ) -> PyInviteMemberOutcome: ...
    def context_leave(self, handle: Any, identity_did: Any) -> Any: ...
    def context_member_count(self, handle: Any) -> Any: ...
    def context_member_dids(self, handle: Any) -> Any: ...
    def context_member_role(self, handle: Any, did: Any) -> Any: ...
    def context_propose_ttl_extension(
        self, handle: Any, member_did: Any, proposed_seconds: Any
    ) -> Any: ...
    def context_receive(self, handle: Any) -> Any: ...
    def context_reconnect(
        self, identity_did: Any, context_ids: Any, last_relay_contacts: Any = ...
    ) -> Any: ...
    def context_reset_ttl_timer(self, handle: Any, new_seconds: Any) -> Any: ...
    # test-only — present only in `testing` builds; raises
    # AttributeError on a production wheel. Seeds a peer's §9.10.4 pseudonym to
    # simulate a delivered announcement in tests.
    def context_seed_peer_pseudonym(self, handle: Any, peer_did: Any, pseudonym: Any) -> Any: ...
    def context_send(
        self, handle: Any, identity_did: Any, payload: Any, spending_ucan_jwt: Any = ...
    ) -> Any: ...
    def evaluate_invitation(
        self,
        params_json: Any,
        inviter_did: Any,
        identity_did: Any,
        policy_json: Any = ...,
        spending_json: Any = ...,
    ) -> Any: ...
    def get_economic_policy(self, handle: Any) -> Any: ...
    def migration_state(self, handle: Any) -> Any: ...
    def reserve_key_package(self, owning_did: Any) -> Any: ...
    def set_economic_policy(self, handle: Any, policy_json: Any) -> Any: ...
    def tombstone_migrated_context(self, handle: Any) -> Any: ...

    # -- economy --
    def economy_antispam_escalated_cost(
        self,
        context_id: Any,
        sender_did: Any,
        now: Any,
        base_cost: Any,
        thresholds_json: Any,
        floor: Any = ...,
        cap: Any = ...,
    ) -> Any: ...
    def economy_antispam_record(self, context_id: Any, sender_did: Any, timestamp: Any) -> Any: ...
    def economy_antispam_velocity(self, context_id: Any, sender_did: Any, now: Any) -> Any: ...
    def economy_budget_grant(self, context_id: Any, did: Any, amount: Any) -> Any: ...
    def economy_budget_record_spend(self, context_id: Any, did: Any, amount: Any) -> Any: ...
    def economy_budget_remaining(self, context_id: Any, did: Any) -> Any: ...
    def economy_verify_payment_receipts(self, receipts_json: Any) -> Any: ...

    # -- event log --
    def event_log_checkpoint(self, context_id: Any, identity_did: Any, epoch: Any) -> Any: ...
    def event_log_checkpoint_by_did(self, context_id: Any, did: Any, epoch: Any) -> Any: ...
    def event_log_query(self, context_id: Any, filter: Any = ...) -> Any: ...
    def event_log_verify(self, context_id: Any, claim: Any) -> Any: ...

    # -- testing / full-stack e2e --
    def fullstack_add_member(self, node: Any, context_id: Any, member_did: Any) -> Any: ...
    def fullstack_create_context(self, node: Any, context_id: Any, ceiling_json: Any) -> Any: ...
    def fullstack_create_node(self, did: Any) -> Any: ...
    def fullstack_decrypt_message(
        self, node: Any, context_id: Any, ciphertext: Any, sender_did: Any
    ) -> Any: ...
    def fullstack_join_from_welcome(self, node: Any, context_id: Any) -> Any: ...
    def fullstack_remove_member(self, node: Any, context_id: Any, member_did: Any) -> Any: ...
    def fullstack_reset_network(self) -> Any: ...
    # test-only — present only in `testing` builds.
    def fullstack_seed_peer_pseudonym(
        self, node: Any, context_id: Any, peer_did: Any, pseudonym: Any
    ) -> Any: ...
    def fullstack_send_message(self, node: Any, context_id: Any, payload: Any) -> Any: ...
    def fullstack_sync_sender_keys(self, node_a: Any, node_b: Any, context_id: Any) -> Any: ...

    # -- identity --
    def create_identity_link_attestation(
        self,
        did: Any,
        platform: Any,
        handle: Any,
        proof: Any,
        verification_method: Any,
        platform_id: Any = ...,
    ) -> Any: ...
    def identity_add_agent_key(self, identity: Any) -> Any: ...
    def identity_attest_device(self, identity_did: Any) -> Any: ...
    def identity_create(self, custody: Any, testing_seed: Any = ...) -> Any: ...
    def identity_create_with_agent_key(self, custody: Any) -> Any: ...
    def identity_create_with_custody(self, provider: Any) -> Any: ...
    def identity_execute_custody_migration(
        self, did: Any, target: Any, context_ids: Any
    ) -> Any: ...
    def identity_execute_recovery(self, did: Any, tier: Any, context_ids: Any) -> Any: ...
    def identity_link_attestations(self, did: Any) -> Any: ...
    def identity_load(self, did: Any) -> Any: ...
    def identity_migrate(self, identity: Any) -> Any: ...
    def identity_remove(self, did: Any) -> None: ...
    def identity_remove_agent_key(self, identity: Any) -> Any: ...
    def identity_remove_if_present(self, did: Any) -> bool: ...
    def identity_resolve(self, did: Any) -> Any: ...
    def identity_rotate_agent_key(self, identity: Any) -> Any: ...
    def identity_rotate_key(self, identity: Any) -> Any: ...
    def remove_identity_link_attestation(self, did: Any, attestation_id: Any) -> Any: ...

    # -- MCP --
    def mcp_configure_stdio_allowlist(self, additional_binaries: list[str] = ...) -> None: ...
    def mcp_disable_stdio_allowlist(self) -> None: ...
    def mcp_get_stdio_allowlist(self) -> McpAllowlistState: ...
    def mcp_register_outlet_handler(
        self, context_id: Any, outlet_name: Any, handler: Any
    ) -> Any: ...
    def mcp_reset_stdio_allowlist(self) -> None: ...
    def py_mcp_client_connect_sse(self, url: Any) -> Any: ...
    def py_mcp_client_connect_stdio(self, command: Any) -> Any: ...
    def py_mcp_client_disconnect(self, handle: Any) -> Any: ...
    def py_mcp_client_info(self, handle: Any) -> Any: ...
    def py_mcp_client_invoke(
        self, handle: Any, outlet_name: Any, input: Any, context_id: Any, identity_did: Any
    ) -> Any: ...
    def py_mcp_client_list_tools(self, handle: Any) -> Any: ...
    def py_mcp_load_contexts(self, identity_did: Any, _relay_url: Any) -> Any: ...
    def py_mcp_serve(
        self, identity_did: Any, context_ids: Any, transport: Any, ucan_token: Any = ...
    ) -> Any: ...
    def py_mcp_server_info(self, handle: Any) -> Any: ...
    def py_mcp_server_stop(self, handle: Any) -> Any: ...
    def py_mcp_server_wait(self, handle: Any) -> Any: ...
    def py_registry_cleanup(self) -> Any: ...
    def py_registry_stats(self) -> Any: ...

    # -- provenance --
    def provenance_attach(
        self,
        source_context_id: Any,
        source_type: Any,
        memory_scope: Any,
        members: Any,
        target_context_id: Any,
        actor_did: Any,
        existing_chain_depth: Any = ...,
    ) -> Any: ...

    # -- server --
    def node_start_in_memory(self, identity_did: Any = ...) -> Any: ...
    def node_start_local(
        self, data_dir: Any, identity_did: Any = ..., passphrase: Any = ...
    ) -> Any: ...
    def relay_start_in_memory(self) -> Any: ...
    def relay_start_local(self, data_dir: Any) -> Any: ...

    # -- scpid --
    def scpid_sign(
        self, did: Any, signing_key_id: Any, challenge_json: Any, signed_at_override: Any = ...
    ) -> Any: ...
    def scpid_verify(self, response_json: Any, challenge_json: Any) -> Any: ...

    # -- outlets --
    def outlet_interface_accept(self, context_id: Any, interface_json: Any) -> Any: ...
    def outlet_interface_expose(
        self, context_id: Any, outlet_id: Any, target_context_id: Any, rate_limit_json: Any = ...
    ) -> Any: ...
    def outlet_interface_revoke(self, context_id: Any, interface_id_hex: Any) -> Any: ...
    def outlet_invoke(
        self,
        context_id: Any,
        outlet_id: Any,
        input: Any,
        identity_did: Any,
        ucan_token: Any,
        proof_tokens: Any = ...,
        spending_ucan: Any = ...,
    ) -> Any: ...
    def outlet_invoke_cross_context(
        self,
        source_context_id: Any,
        target_context_id: Any,
        outlet_id: Any,
        input: Any,
        invoker_did: Any,
        ucan_token: Any,
        chain_depth: Any,
        proof_tokens: Any = ...,
    ) -> Any: ...
    def outlet_invoke_cross_context_saga(
        self,
        caller_context_id: Any,
        target_context_id: Any,
        caller_did: Any,
        outlet_registration_id: Any,
        input: Any,
        asserted_nonce_hex: Any,
        timestamp_ms: Any,
        chain_depth: Any,
        ucan_proof_id: Any = ...,
    ) -> SagaResult: ...
    def outlet_register(self, context_id: Any, registration: Any) -> Any: ...
    def outlet_streaming_saga_open(
        self,
        caller_context_id: Any,
        target_context_id: Any,
        caller_did: Any,
        outlet_registration_id: Any,
        input: Any,
        asserted_nonce_hex: Any,
        timestamp_ms: Any,
        chain_depth: Any,
        ucan_token: Any,
        proof_tokens: Any = ...,
        ucan_proof_id: Any = ...,
        timeout_ms: Any = ...,
        estimated_chunk_count: Any = ...,
    ) -> str: ...
    def outlet_streaming_saga_poll_next(self, saga_id: Any) -> bytes | None: ...
    def outlet_streaming_saga_recover_truncated_close(
        self, saga_id: Any, caller_did: Any
    ) -> None: ...
    def outlet_stream_open(
        self,
        context_id: Any,
        outlet_id: Any,
        input: Any,
        caller_did: Any,
        ucan_token: Any,
        proof_tokens: Any = ...,
        spending_ucan: Any = ...,
        timeout_ms: Any = ...,
        estimated_chunk_count: Any = ...,
    ) -> str: ...
    def outlet_stream_poll_next(self, handle_id: Any) -> bytes | None: ...
    def outlet_stream_grant_credit(self, handle_id: Any, caller_did: Any, grant: Any) -> None: ...
    def outlet_stream_cancel(self, handle_id: Any, caller_did: Any) -> None: ...
    def outlet_stream_terminate(
        self, handle_id: Any, caller_did: Any, slug: Any, message: Any
    ) -> None: ...
    def outlet_stream_verify_chunk_signature(
        self,
        chunk_bytes: Any,
        operator_pk: Any,
        context_id: Any,
        outlet_id: Any,
        caveats_binding: Any,
    ) -> bool: ...
    def outlet_stream_compute_caveats_binding(
        self,
        ucan_cid: Any,
        request_id: Any,
        invoker_did: Any,
        estimated_chunk_count: Any,
        effective_caveats_jcs: Any,
    ) -> bytes: ...
    def outlet_session_close(self, context_id: Any, session_id: Any) -> Any: ...
    def outlet_session_create(
        self, context_id: Any, outlet_id: Any, source_context_id: Any, ttl_seconds: Any = ...
    ) -> Any: ...
    def outlet_session_invoke(
        self,
        context_id: Any,
        session_id: Any,
        input: Any,
        invoker_did: Any,
        ucan_token: Any,
        proof_tokens: Any = ...,
    ) -> Any: ...
    def outlet_verify(self, context_id: Any, outlet_id: Any) -> Any: ...

    # -- transport --
    def transport_adapter_count(self) -> Any: ...
    def transport_add_relay(self, relay_url: Any, source: Any = ...) -> Any: ...
    def transport_assign_relay_set(self, context_id: Any) -> Any: ...
    def transport_connect(self, relay_url: Any, source: Any = ...) -> Any: ...
    def transport_disconnect(self) -> Any: ...
    def transport_reliability(self, adapter_index: Any) -> Any: ...
    def transport_status(self) -> Any: ...

    # -- trust --
    def aggregate_trust_input(
        self,
        context_id: Any,
        subject_did: Any,
        events_json: Any,
        merkle_root_json: Any,
        consequence_rules_json: Any,
        threshold_requirements_json: Any,
        attestor_sets_json: Any,
        cached_attestations_json: Any,
        challenge_results_json: Any,
    ) -> Any: ...
    def trust_query_score(self, did: Any, context_id: Any) -> Any: ...
    def participation_record(
        self, context_id: Any, subject_did: Any, cached_attestations_json: Any = ...
    ) -> Any: ...

    # -- media (instance — event-log-appending, ADR-024 AC 8) --
    def media_activate_session(self, session_json: str) -> dict[str, Any]: ...
    def media_end_session(self, session_json: str, timestamp: int) -> dict[str, Any]: ...

    # -- UCAN --
    def ucan_delegate(
        self,
        context_id: Any,
        delegator_did: Any,
        delegatee_did: Any,
        parent_token: Any,
        capabilities: Any,
    ) -> Any: ...
    def ucan_mint(
        self, context_id: Any, member_did: Any, capabilities: Any, proofs: Any = ...
    ) -> Any: ...
    def ucan_revoke(self, context_id: Any, token: Any, revoker_did: Any) -> Any: ...
    def ucan_validate(
        self,
        context_id: Any,
        token: Any,
        capability: Any,
        presenting_agent_did: Any,
        proof_tokens: Any = ...,
    ) -> Any: ...
    def ucan_evaluate(
        self,
        context_id: Any,
        token: Any,
        capability: Any,
        presenting_agent_did: Any,
        proof_tokens: Any = ...,
    ) -> Any: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Remaining module-level free functions (pure helpers / runtime lifecycle)
# ---------------------------------------------------------------------------

def runtime_is_initialized() -> bool:
    """Return ``True`` if the tokio runtime has been initialized."""
    ...

def version() -> str:
    """Return the bridge version string."""
    ...

def shutdown_runtime(_timeout_millis: int) -> None:
    """Shut down the shared tokio runtime (drain for ``timeout_millis`` ms)."""
    ...

# Phase 4 PR 4 (#1549, ADR-048) deleted the ``scp_suspend`` / ``scp_resume``
# free functions along with the process-wide default bridge they operated
# against. Lifecycle is now driven per-instance via :meth:`SCP.suspend` /
# :meth:`SCP.resume`.

# -- pure helper functions (no bridge state) --

def py_check_scoped_capability(
    granted_capabilities: tuple[str, ...], required_capability: str
) -> bool: ...
def evaluate_invitation(
    *args: Any, **kwargs: Any
) -> str: ...  # placeholder; live surface is SCP.evaluate_invitation
def metadata_record_to_json(
    context_id: str,
    sequence: int,
    signer_did: str,
    timestamp: int,
    structural_json: str,
    operational_json: str,
    signature_hex: str,
) -> str: ...
def metadata_record_from_json(json_str: str) -> str: ...
def template_get_params(template_id: str) -> str: ...
def validate_against_template(params_json: str) -> str | None: ...
def validate_context_params(params_json: str) -> str | None: ...

# -- discovery (pure — resolver-local) --

def discovery_parse_address(address: str) -> Any: ...
def discovery_create_query(
    capabilities: list[str] | None = ...,
    keywords: list[str] | None = ...,
    min_history_secs: int | None = ...,
) -> str: ...
def discovery_normalize_address(address: str) -> str: ...
def context_discover(query: str) -> Any: ...

# -- economy (pure) --

def economy_estimate_cost(
    policy_json: str, action_type: str, metrics: dict[str, int] | None
) -> int: ...
def economy_policy_requires_payment(policy_json: str) -> bool: ...
def economy_auto_accept_blocked(policy_json: str) -> bool: ...
def economy_check_policy_lock(policy_json: str) -> bool: ...
def economy_validate_policy_change(current_policy_json: str, proposed_policy_json: str) -> bool: ...
def economy_evaluate_formula(formula_json: str, metrics: dict[str, int] | None) -> int | None: ...

# -- trust (pure) --

def trust_verify_attestation(*args: Any, **kwargs: Any) -> Any: ...
def trust_create_challenge(*args: Any, **kwargs: Any) -> Any: ...
def trust_verify_response(*args: Any, **kwargs: Any) -> Any: ...
def verify_participation_requirements(
    expected_subject: str, requirements_json: str, profile_json: str
) -> None: ...
def check_capability_requirements(
    context_id: str,
    subject_did: str,
    requirements_json: str,
    agent_capabilities_json: str,
    challenge_verifications_json: str,
) -> None: ...

# -- sync (pure) --

def sync_classify_offline(last_relay_contact: int, now: int) -> str: ...
def sync_get_policy() -> dict[str, Any]: ...
def sync_classify_offline_custom(*args: Any, **kwargs: Any) -> Any: ...

# -- scpid (pure helpers, ADR-048 §1) --

def scpid_challenge(audience: str, ttl_seconds: int) -> str: ...

# -- identity (pure helpers, ADR-048 §1) --

def identity_verify_device_attestation(_did: str, token_base64: str) -> bool: ...
def py_verify_identity_link_attestation(
    attestation_json: str, issuer_public_key_hex: str
) -> bool: ...

# -- provenance (pure helpers, ADR-048 §1) --

def evaluate_provenance_quality(
    source_context: str | None = ...,
    source_type: str = ...,
    context_state: str = ...,
    counterparties: list[str] | None = ...,
) -> int: ...
def provenance_check_chain_depth(chain_depth: int, max_depth: int | None = ...) -> bool: ...
def provenance_pseudonymize_counterparties(provenance_json: str, pseudonym_key_hex: str) -> str: ...
def provenance_redact_counterparties(provenance_json: str) -> str: ...
def provenance_update_source_type(provenance_json: str, new_state: str) -> str: ...

# -- media (pure) --

def media_check_capability(ceiling: list[str], capability: str) -> bool: ...
def media_initiate_session(*args: Any, **kwargs: Any) -> Any: ...
def media_join_session(session_json: str, participant_did: str) -> dict[str, Any]: ...
def media_create_offer(session_id: str, sdp: str, sender_did: str) -> dict[str, str]: ...
def media_create_answer(session_id: str, sdp: str, sender_did: str) -> dict[str, str]: ...
def media_create_ice_candidate(*args: Any, **kwargs: Any) -> Any: ...
def media_create_session_end(session_id: str, sender_did: str) -> dict[str, str]: ...
def media_send_signaling(signaling_json: str) -> dict[str, str]: ...
def media_verify_sender_attribution(signaling_json: str, envelope_sender_did: str) -> bool: ...

# -- bridge connector (pure) --

def bridge_register(*args: Any, **kwargs: Any) -> Any: ...
def bridge_evaluate_trust(*args: Any, **kwargs: Any) -> int: ...
def bridge_claim_shadow(*args: Any, **kwargs: Any) -> Any: ...
def bridge_seal_shadow_envelope(*args: Any, **kwargs: Any) -> Any: ...
def bridge_open_shadow_envelope(*args: Any, **kwargs: Any) -> Any: ...
def bridge_derive_credential_key(*args: Any, **kwargs: Any) -> Any: ...
def bridge_generate_credential_key() -> bytes: ...
def bridge_oauth_generate_pkce() -> dict[str, str]: ...
def bridge_oauth_build_auth_url(*args: Any, **kwargs: Any) -> str: ...
def bridge_oauth_scopes_for_mode(mode: str) -> list[str]: ...

# -- MCP stdio allowlist (methods on SCP, not module-level) --
# The four `py_mcp_*_stdio_allowlist` free functions were deleted in
# Per-instance migration — see `class SCP` above for the method stubs.
