//! Attested `KeyPackage` minting — the signer side of the `0xFF03`
//! `scp_keypackage_attestation` `LeafNode` extension (§9.7.1, §9.5.2;
//! ADR-057 Amendment 2026-08-01).
//!
//! [`keypackage_attestation`](crate::keypackage_attestation) defines the
//! attestation type and its verifier. This module produces one: it generates a
//! `KeyPackage` whose leaf carries an `#active`/`#agent`-signed attestation
//! binding all four of that leaf's public keys to the member's DID.
//!
//! # Why minting takes two calls
//!
//! §9.5.2 binds four keys: the leaf `signature_key`, the `LeafNode`
//! ratchet-tree `encryption_key`, the `KeyPackage` `init_key`, and the
//! `scp_wrapping_key` (`0xFF01`) `wrapping_key`. The attestation over those
//! four rides **inside** the leaf, so the leaf's own self-signature covers it.
//! Two of the four keys — `encryption_key` and `init_key` — are generated by
//! `openmls` inside `KeyPackage::builder().build()`, and `openmls` 0.8.1
//! exposes no public seam that accepts pre-chosen values for them
//! (`KeyPackage::create` and `LeafNode::new_with_key` are both private, and
//! `KeyPackageBundle::new` is `test-utils`-gated). A single call therefore
//! cannot both learn those keys and sign over them.
//!
//! [`prepare_key_package`] resolves that by building a **probe** `KeyPackage`
//! while recording every random draw `openmls` makes, reading the two generated
//! keys off the probe, and returning the unsigned attestation. The caller signs
//! [`PreparedKeyPackage::attestation_signing_hash`] with the identity's
//! `#active`/`#agent` custody key — an operation this crate never performs,
//! because `scp-mls` is wasm-safe and `KeyCustody` lives in the native-only
//! `scp-platform`. [`finish_key_package`] then replays the recorded draw
//! sequence into a second build, which reproduces the same two keys (openmls
//! derives both with `OpenMlsCrypto::derive_hpke_keypair`, a pure function of
//! its input keying material) and adds the signed `0xFF03` extension to the
//! leaf.
//!
//! # The replay is checked, never trusted
//!
//! [`finish_key_package`] compares the finished `KeyPackage`'s actual
//! `init_key`, `encryption_key`, `signature_key`, and `0xFF01` wrapping key
//! against the four values the attestation binds, and returns
//! [`MlsError::AttestationBindingMismatch`] on any difference. A future
//! `openmls` release that draws randomness differently therefore makes minting
//! **fail**, and can never make it emit a `KeyPackage` whose attestation binds
//! keys the leaf does not carry.
//!
//! # No unattested production path
//!
//! This module is the only production route to a `KeyPackage` in `scp-mls`.
//! [`finish_key_package`] takes the 64-byte signature by value, so a
//! `KeyPackage` with no attestation is unrepresentable here rather than merely
//! discouraged. A caller that holds no custody key returns
//! [`MlsError::AttestationSignerUnavailable`] instead of minting an unattested
//! `KeyPackage`.
//!
//! See spec §9.7.1 ("`KeyPackage` leaf key and DID attestation"), §9.5.2
//! (`KeyPackageAttestation`), and §9.18.7 (`0xFF03`).

use std::collections::VecDeque;
use std::sync::{Mutex, PoisonError};

use openmls::prelude::*;
use openmls_basic_credential::SignatureKeyPair;
use openmls_traits::OpenMlsProvider;
use openmls_traits::random::OpenMlsRand;
use scp_clock::Clock;

use crate::InMemoryMlsProvider;
use crate::credential::ScpCredential;
use crate::error::MlsError;
use crate::group::SCP_CIPHERSUITE;
use crate::keypackage_attestation::{
    KeyPackageAttestation, fixed_32, leaf_encryption_key_bytes,
    scp_capabilities_with_keypackage_attestation,
};
use crate::lifetime::key_package_lifetime;
use crate::wrapping_extension::make_wrapping_key_extension;

/// Size of a raw Ed25519 or X25519 public key in bytes.
const PUBLIC_KEY_SIZE: usize = 32;

/// Size of a raw Ed25519 signature in bytes.
const SIGNATURE_SIZE: usize = 64;

/// The randomness provider of [`InMemoryMlsProvider`].
type BaseRand = <InMemoryMlsProvider as OpenMlsProvider>::RandProvider;

/// The crypto provider of [`InMemoryMlsProvider`].
type BaseCrypto = <InMemoryMlsProvider as OpenMlsProvider>::CryptoProvider;

/// The storage provider of [`InMemoryMlsProvider`].
type BaseStorage = <InMemoryMlsProvider as OpenMlsProvider>::StorageProvider;

/// The error type [`BaseRand`] reports.
type BaseRandError = <BaseRand as OpenMlsRand>::Error;

// ---------------------------------------------------------------------------
// Randomness transcript
// ---------------------------------------------------------------------------

/// What a [`TranscriptRand`] does with each draw.
#[derive(Debug)]
enum TranscriptMode {
    /// Draw from the real generator and append each result to the log.
    Record(Vec<Vec<u8>>),
    /// Return the next logged result whose length matches the request.
    Replay(VecDeque<Vec<u8>>),
}

/// An [`OpenMlsRand`] that records the draws of one `KeyPackage` build so a
/// second build can repeat them.
///
/// Recording takes every byte from the real generator ([`BaseRand`]) and keeps
/// a copy, so the entropy of the recorded build is exactly the entropy of an
/// ordinary build. Replaying hands those same bytes back in the order they were
/// drawn. A replay request whose length does not match the next logged draw —
/// which a change in `openmls`'s internal draw sequence would cause — falls
/// through to the real generator, and [`finish_key_package`] then rejects the
/// resulting `KeyPackage` because its keys no longer match the attestation.
#[derive(Debug)]
struct TranscriptRand<'a> {
    /// The real generator every recorded draw comes from, and the fallback for
    /// a replay draw the log cannot satisfy.
    inner: &'a BaseRand,
    /// The recorded or remaining draws.
    mode: Mutex<TranscriptMode>,
}

impl<'a> TranscriptRand<'a> {
    /// Creates a recording transcript over `inner`.
    const fn recording(inner: &'a BaseRand) -> Self {
        Self {
            inner,
            mode: Mutex::new(TranscriptMode::Record(Vec::new())),
        }
    }

    /// Creates a transcript that replays `draws` in order.
    fn replaying(inner: &'a BaseRand, draws: Vec<Vec<u8>>) -> Self {
        Self {
            inner,
            mode: Mutex::new(TranscriptMode::Replay(draws.into())),
        }
    }

    /// Consumes the transcript and returns the draws it recorded.
    fn into_recorded(self) -> Vec<Vec<u8>> {
        match self
            .mode
            .into_inner()
            .unwrap_or_else(PoisonError::into_inner)
        {
            TranscriptMode::Record(log) => log,
            TranscriptMode::Replay(remaining) => remaining.into(),
        }
    }

    /// Returns `len` bytes, recording or replaying them per the mode.
    fn draw(&self, len: usize) -> Result<Vec<u8>, BaseRandError> {
        let mut mode = self.mode.lock().unwrap_or_else(PoisonError::into_inner);
        match &mut *mode {
            TranscriptMode::Record(log) => {
                let bytes = self.inner.random_vec(len)?;
                log.push(bytes.clone());
                Ok(bytes)
            }
            TranscriptMode::Replay(remaining) => {
                if remaining.front().is_some_and(|next| next.len() == len) {
                    // `front` matched, so `pop_front` yields that same element.
                    remaining
                        .pop_front()
                        .map_or_else(|| self.inner.random_vec(len), Ok)
                } else {
                    self.inner.random_vec(len)
                }
            }
        }
    }
}

impl OpenMlsRand for TranscriptRand<'_> {
    type Error = BaseRandError;

    fn random_array<const N: usize>(&self) -> Result<[u8; N], Self::Error> {
        let drawn = self.draw(N)?;
        let mut out = [0u8; N];
        // `draw` returns exactly `N` bytes on both paths: the recording path
        // asks the real generator for `N`, and the replay path only pops an
        // entry whose length is `N`.
        if drawn.len() == N {
            out.copy_from_slice(&drawn);
            Ok(out)
        } else {
            self.inner.random_array::<N>()
        }
    }

    fn random_vec(&self, len: usize) -> Result<Vec<u8>, Self::Error> {
        self.draw(len)
    }
}

/// An [`OpenMlsProvider`] that swaps one [`InMemoryMlsProvider`]'s randomness
/// source for a [`TranscriptRand`], leaving its crypto and storage untouched.
#[derive(Debug)]
struct TranscriptProvider<'a> {
    /// The provider whose crypto and storage this wrapper forwards to.
    inner: &'a InMemoryMlsProvider,
    /// The recording or replaying randomness source `openmls` draws from.
    rand: TranscriptRand<'a>,
}

impl<'a> TranscriptProvider<'a> {
    /// Wraps `inner` with a recording transcript.
    fn recording(inner: &'a InMemoryMlsProvider) -> Self {
        Self {
            inner,
            rand: TranscriptRand::recording(inner.rand()),
        }
    }

    /// Wraps `inner` with a transcript that replays `draws`.
    fn replaying(inner: &'a InMemoryMlsProvider, draws: Vec<Vec<u8>>) -> Self {
        Self {
            inner,
            rand: TranscriptRand::replaying(inner.rand(), draws),
        }
    }

    /// Consumes the wrapper and returns the draws its transcript recorded.
    fn into_recorded(self) -> Vec<Vec<u8>> {
        self.rand.into_recorded()
    }
}

impl<'a> OpenMlsProvider for TranscriptProvider<'a> {
    type CryptoProvider = BaseCrypto;
    type RandProvider = TranscriptRand<'a>;
    type StorageProvider = BaseStorage;

    fn storage(&self) -> &Self::StorageProvider {
        self.inner.storage()
    }

    fn crypto(&self) -> &Self::CryptoProvider {
        self.inner.crypto()
    }

    fn rand(&self) -> &Self::RandProvider {
        &self.rand
    }
}

// ---------------------------------------------------------------------------
// Prepared KeyPackage
// ---------------------------------------------------------------------------

/// A `KeyPackage` whose four attested public keys are fixed and whose
/// attestation is not yet signed.
///
/// [`prepare_key_package`] produces one; [`finish_key_package`] consumes it.
/// Between the two calls the caller signs
/// [`attestation_signing_hash`](Self::attestation_signing_hash) with the DID's
/// `#active`/`#agent` key.
pub struct PreparedKeyPackage {
    /// The credential the finished leaf embeds.
    credential: ScpCredential,
    /// The ephemeral, context-scoped MLS leaf signature keypair (§9.7.1). The
    /// finished `KeyPackage` self-signs its leaf with this key, and the caller
    /// retains it to join the group the leaf is added to.
    signer: SignatureKeyPair,
    /// The member's 32-byte X25519 `scp_wrapping_key` (`0xFF01`) public key.
    wrapping_pubkey: [u8; PUBLIC_KEY_SIZE],
    /// The `Lifetime` both builds stamp, and the window the attestation's
    /// `issued_at`/`expires_at` reproduce (§9.7.1 check 11).
    lifetime: Lifetime,
    /// Every random draw the probe build made, replayed by the second build.
    recorded_draws: Vec<Vec<u8>>,
    /// The attestation over the probe build's four public keys, with an
    /// all-zero signature until [`finish_key_package`] installs the real one.
    attestation: KeyPackageAttestation,
}

impl std::fmt::Debug for PreparedKeyPackage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // The leaf signature keypair and the recorded draws are private key
        // material, so this prints neither.
        f.debug_struct("PreparedKeyPackage")
            .field("did", &self.credential.did)
            .field("signing_key_id", &self.credential.signing_key_id)
            .field("issued_at", &self.attestation.issued_at)
            .field("expires_at", &self.attestation.expires_at)
            .field("signer", &"<redacted>")
            .field("recorded_draws", &"<redacted>")
            .finish_non_exhaustive()
    }
}

impl PreparedKeyPackage {
    /// Returns the 32-byte SHA-256 hash the identity's `#active`/`#agent` key
    /// signs (§9.5.1).
    ///
    /// The signer computes an Ed25519 signature over **these 32 bytes** and
    /// over nothing else — not over the canonical preimage, and not over the
    /// `0xFF03` extension body (§9.5.2).
    #[must_use]
    pub fn attestation_signing_hash(&self) -> [u8; 32] {
        self.attestation.signing_hash()
    }

    /// Returns the unsigned attestation, so a caller can read the four keys
    /// and the validity window it binds.
    #[must_use]
    pub const fn attestation(&self) -> &KeyPackageAttestation {
        &self.attestation
    }
}

// ---------------------------------------------------------------------------
// Mint
// ---------------------------------------------------------------------------

/// Generates the leaf key material for a context-joinable `KeyPackage` and
/// returns the unsigned attestation over it (§9.7.1 leaf-creation site 2).
///
/// The leaf declares support for all three SCP `LeafNode` extension types
/// (`0xFF01` `scp_wrapping_key`, `0xFF02` `scp_context_params`, `0xFF03`
/// `scp_keypackage_attestation`), which RFC 9420 §12.1.8.2 (`valn0502`)
/// requires of any leaf added to an SCP context group, and carries the
/// `0xFF01` wrapping-key extension.
///
/// `wrapping_pubkey` is required rather than optional: §9.5.2 field 5 binds the
/// `0xFF01` value, and §9.7.1 check 6 compares the attestation against it, so a
/// leaf with no wrapping key cannot carry a verifiable attestation.
///
/// # Errors
///
/// Returns [`MlsError::CredentialSerializationFailed`] if `credential` cannot
/// be serialized, and [`MlsError::KeyPackageGenerationFailed`] if the leaf
/// signature keypair or the probe `KeyPackage` cannot be built.
pub fn prepare_key_package(
    credential: &ScpCredential,
    wrapping_pubkey: &[u8; PUBLIC_KEY_SIZE],
    clock: &dyn Clock,
) -> Result<PreparedKeyPackage, MlsError> {
    let signer = SignatureKeyPair::new(SCP_CIPHERSUITE.signature_algorithm())
        .map_err(|e| MlsError::KeyPackageGenerationFailed(format!("signer generation: {e}")))?;

    let lifetime = key_package_lifetime(clock);
    let capabilities = scp_capabilities_with_keypackage_attestation();
    let leaf_extensions = wrapping_key_extensions(wrapping_pubkey)?;

    // The probe build exists only to learn the two HPKE public keys openmls
    // generates. Its provider is dropped at the end of this function, so the
    // private halves it wrote never leave here; `finish_key_package` recreates
    // both keys in the provider it returns.
    let probe_provider = InMemoryMlsProvider::default();
    let transcript = TranscriptProvider::recording(&probe_provider);
    let probe = build_key_package(
        &transcript,
        &signer,
        credential,
        capabilities,
        leaf_extensions,
        lifetime,
    )?;

    let leaf_encryption_key = leaf_encryption_key_bytes(probe.key_package().leaf_node())?;
    let init_key = fixed_32(
        probe.key_package().hpke_init_key().as_slice(),
        "KeyPackage init_key",
    )?;
    let leaf_signature_key = fixed_32(signer.public(), "leaf signature_key")?;

    let attestation = KeyPackageAttestation {
        did: credential.did.clone(),
        leaf_signature_key,
        leaf_encryption_key,
        init_key,
        wrapping_key: *wrapping_pubkey,
        signing_key_id: credential.signing_key_id,
        // §9.7.1 check 11: the attestation's window is exactly the leaf's own
        // `Lifetime`, never a wider self-asserted one.
        issued_at: lifetime.not_before(),
        expires_at: lifetime.not_after(),
        signature: [0u8; SIGNATURE_SIZE],
    };

    Ok(PreparedKeyPackage {
        credential: credential.clone(),
        signer,
        wrapping_pubkey: *wrapping_pubkey,
        lifetime,
        recorded_draws: transcript.into_recorded(),
        attestation,
    })
}

/// Builds the finished `KeyPackage`, whose leaf carries the signed `0xFF03`
/// `scp_keypackage_attestation` extension.
///
/// `attestation_signature` is the Ed25519 signature the identity's
/// `#active`/`#agent` key produced over
/// [`PreparedKeyPackage::attestation_signing_hash`].
///
/// Returns the same triple the join path consumes: the `KeyPackageBundle` whose
/// public half is published, the leaf signature keypair, and the provider
/// holding the leaf's private HPKE keys.
///
/// # Errors
///
/// Returns [`MlsError::CredentialSerializationFailed`] if the credential cannot
/// be serialized, [`MlsError::StorageError`] if the leaf signature keypair
/// cannot be stored, [`MlsError::KeyPackageGenerationFailed`] if the build
/// fails, and [`MlsError::AttestationBindingMismatch`] if any of the four keys
/// the finished leaf carries differs from the key the attestation binds.
pub fn finish_key_package(
    prepared: PreparedKeyPackage,
    attestation_signature: [u8; SIGNATURE_SIZE],
) -> Result<(KeyPackageBundle, SignatureKeyPair, InMemoryMlsProvider), MlsError> {
    let PreparedKeyPackage {
        credential,
        signer,
        wrapping_pubkey,
        lifetime,
        recorded_draws,
        mut attestation,
    } = prepared;

    attestation.signature = attestation_signature;

    let provider = InMemoryMlsProvider::default();
    signer
        .store(provider.storage())
        .map_err(|e| MlsError::StorageError(format!("storing signature key: {e}")))?;

    let leaf_extensions = Extensions::<LeafNode>::from_vec(vec![
        make_wrapping_key_extension(&wrapping_pubkey),
        attestation.make_attestation_extension(),
    ])
    .map_err(|e| MlsError::ExtensionError(format!("attested leaf extension list: {e}")))?;

    let transcript = TranscriptProvider::replaying(&provider, recorded_draws);
    let bundle = build_key_package(
        &transcript,
        &signer,
        &credential,
        scp_capabilities_with_keypackage_attestation(),
        leaf_extensions,
        lifetime,
    )?;

    assert_attestation_binds_leaf(&attestation, &bundle)?;

    Ok((bundle, signer, provider))
}

/// Rejects a finished `KeyPackage` whose leaf does not carry exactly the four
/// public keys its attestation binds (§9.5.2 fields 2–5).
///
/// The replayed build is expected to reproduce the probe build's `init_key` and
/// `encryption_key`, because `openmls` derives both from drawn keying material
/// through `OpenMlsCrypto::derive_hpke_keypair`. This function is what makes
/// that expectation load-bearing nowhere: a `KeyPackage` that fails it is
/// discarded rather than published.
fn assert_attestation_binds_leaf(
    attestation: &KeyPackageAttestation,
    bundle: &KeyPackageBundle,
) -> Result<(), MlsError> {
    let leaf = bundle.key_package().leaf_node();

    let actual_signature_key = fixed_32(leaf.signature_key().as_slice(), "leaf signature_key")?;
    if actual_signature_key != attestation.leaf_signature_key {
        return Err(MlsError::AttestationBindingMismatch(
            "leaf signature_key differs from the attested value".to_owned(),
        ));
    }

    let actual_encryption_key = leaf_encryption_key_bytes(leaf)?;
    if actual_encryption_key != attestation.leaf_encryption_key {
        return Err(MlsError::AttestationBindingMismatch(
            "leaf encryption_key differs from the attested value".to_owned(),
        ));
    }

    let actual_init_key = fixed_32(
        bundle.key_package().hpke_init_key().as_slice(),
        "KeyPackage init_key",
    )?;
    if actual_init_key != attestation.init_key {
        return Err(MlsError::AttestationBindingMismatch(
            "KeyPackage init_key differs from the attested value".to_owned(),
        ));
    }

    // RFC 9420 §10.1 and §9.7.1 check 8: a KeyPackage's two HPKE keys are
    // distinct. Rejecting a degenerate pair here means SCP never publishes one.
    if actual_init_key == actual_encryption_key {
        return Err(MlsError::AttestationBindingMismatch(
            "KeyPackage init_key equals its LeafNode encryption_key (RFC 9420 §10.1)".to_owned(),
        ));
    }

    let actual_wrapping_key = crate::wrapping_extension::extract_wrapping_key(leaf.extensions())?
        .ok_or_else(|| {
        MlsError::AttestationBindingMismatch(
            "leaf carries no scp_wrapping_key (0xFF01) extension".to_owned(),
        )
    })?;
    if actual_wrapping_key != attestation.wrapping_key {
        return Err(MlsError::AttestationBindingMismatch(
            "leaf scp_wrapping_key differs from the attested value".to_owned(),
        ));
    }

    Ok(())
}

/// Builds one `KeyPackage` under [`SCP_CIPHERSUITE`] with the given leaf
/// capabilities, leaf extensions, and `Lifetime`.
///
/// The `Lifetime` comes from the injected [`Clock`] (ADR-057 §Prereq-1), never
/// from openmls's internal clock — under the wasm `js` feature that internal
/// clock reads an attacker-overridable `Date.now()`.
fn build_key_package<P: OpenMlsProvider>(
    provider: &P,
    signer: &SignatureKeyPair,
    credential: &ScpCredential,
    capabilities: Capabilities,
    leaf_extensions: Extensions<LeafNode>,
    lifetime: Lifetime,
) -> Result<KeyPackageBundle, MlsError> {
    let credential_with_key = CredentialWithKey {
        credential: BasicCredential::new(credential.to_bytes()?).into(),
        signature_key: signer.to_public_vec().into(),
    };

    KeyPackage::builder()
        .leaf_node_capabilities(capabilities)
        .leaf_node_extensions(leaf_extensions)
        .key_package_lifetime(lifetime)
        .build(SCP_CIPHERSUITE, provider, signer, credential_with_key)
        .map_err(|e| MlsError::KeyPackageGenerationFailed(e.to_string()))
}

/// Builds the single-entry leaf extension list carrying the `0xFF01`
/// wrapping-key extension, which the probe build uses.
fn wrapping_key_extensions(
    wrapping_pubkey: &[u8; PUBLIC_KEY_SIZE],
) -> Result<Extensions<LeafNode>, MlsError> {
    Extensions::<LeafNode>::single(make_wrapping_key_extension(wrapping_pubkey))
        .map_err(|e| MlsError::ExtensionError(format!("wrapping key extension: {e}")))
}

// ---------------------------------------------------------------------------
// Testing-only one-shot mint
// ---------------------------------------------------------------------------

/// Builds a `KeyPackage` whose leaf carries neither SCP leaf extension.
///
/// The leaf omits both the `0xFF01` `scp_wrapping_key` extension and the
/// `0xFF03` `scp_keypackage_attestation` extension, which is what a
/// non-conformant implementation publishes.
///
/// Every SCP mint path carries both extensions, so no conformant peer produces
/// this shape. A receiver still has to reject it, because a peer chooses what
/// it publishes and a verifier trusts none of it: §9.7.1 rejects the
/// unattested leaf, and ADR-057's sender-key INVARIANT 3 rejects the leaf no
/// peer can HPKE-seal to. This fixture is how a test hands a receiver that
/// input.
///
/// This is an adversarial fixture, not a stand-in for a mint. It is gated on
/// `testing` so no shipped artifact carries it, and nothing in the crate calls
/// it — a caller that wants a real `KeyPackage` takes
/// [`prepare_key_package`]/[`finish_key_package`] or
/// [`mint_key_package_for_testing`], each of which produces both extensions.
///
/// # Errors
///
/// Returns [`MlsError::CredentialSerializationFailed`] if `credential` cannot
/// be serialized, and [`MlsError::KeyPackageGenerationFailed`] if the leaf
/// signature keypair or the `KeyPackage` cannot be built.
#[cfg(any(test, feature = "testing"))]
pub fn mint_non_conformant_key_package_for_testing(
    credential: &ScpCredential,
    clock: &dyn Clock,
) -> Result<(KeyPackageBundle, SignatureKeyPair, InMemoryMlsProvider), MlsError> {
    let signer = SignatureKeyPair::new(SCP_CIPHERSUITE.signature_algorithm())
        .map_err(|e| MlsError::KeyPackageGenerationFailed(format!("signer generation: {e}")))?;
    let provider = InMemoryMlsProvider::default();
    signer
        .store(provider.storage())
        .map_err(|e| MlsError::StorageError(format!("storing leaf signature keypair: {e}")))?;

    let bundle = build_key_package(
        &provider,
        &signer,
        credential,
        // Declares the SCP capabilities without carrying either leaf extension,
        // which is what makes the leaf non-conformant rather than malformed.
        scp_capabilities_with_keypackage_attestation(),
        Extensions::<LeafNode>::empty(),
        key_package_lifetime(clock),
    )?;

    Ok((bundle, signer, provider))
}

/// Mints an attested `KeyPackage` in one call, signing the attestation with a
/// caller-supplied Ed25519 key.
///
/// This exists so a test can produce a real, fully-attested `KeyPackage`
/// without a custody backend. It is compiled out of shipped artifacts, and it
/// is not a stand-in for the production signer: production reaches the identity
/// key through `KeyCustody::sign`, and the two-call
/// [`prepare_key_package`]/[`finish_key_package`] pair is the only route it
/// takes.
///
/// # Errors
///
/// Returns whatever [`prepare_key_package`] or [`finish_key_package`] returns.
#[cfg(any(test, feature = "testing"))]
pub fn mint_key_package_for_testing(
    credential: &ScpCredential,
    wrapping_pubkey: &[u8; PUBLIC_KEY_SIZE],
    clock: &dyn Clock,
    attestation_signing_key: &ed25519_dalek::SigningKey,
) -> Result<(KeyPackageBundle, SignatureKeyPair, InMemoryMlsProvider), MlsError> {
    use ed25519_dalek::Signer as _;

    let prepared = prepare_key_package(credential, wrapping_pubkey, clock)?;
    let signature = attestation_signing_key
        .sign(&prepared.attestation_signing_hash())
        .to_bytes();
    finish_key_package(prepared, signature)
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::doc_markdown,
    clippy::panic
)]
mod tests {
    use super::*;
    use crate::keypackage_attestation::{
        SCP_KEYPACKAGE_ATTESTATION_EXTENSION_TYPE, verify_attestation_with_resolution,
    };
    use ed25519_dalek::{Signer as _, SigningKey};
    use rand::rngs::OsRng;
    use scp_clock::SystemClock;
    use scp_did::SigningKeyId;

    const WRAPPING_KEY: [u8; 32] = [0x11; 32];

    fn credential() -> ScpCredential {
        ScpCredential::new(
            "did:key:z6MkTestKeyPackageAttestationMint".to_owned(),
            None,
            SigningKeyId::Active,
        )
        .expect("test credential")
    }

    #[test]
    fn finished_leaf_carries_the_attestation_extension() {
        let key = SigningKey::generate(&mut OsRng);
        let (bundle, _signer, _provider) =
            mint_key_package_for_testing(&credential(), &WRAPPING_KEY, &SystemClock, &key)
                .expect("mint");

        let extension = bundle
            .key_package()
            .leaf_node()
            .extensions()
            .unknown(SCP_KEYPACKAGE_ATTESTATION_EXTENSION_TYPE);
        assert!(
            extension.is_some(),
            "a minted KeyPackage leaf must carry the 0xFF03 scp_keypackage_attestation extension"
        );
    }

    #[test]
    fn attestation_binds_the_four_keys_the_leaf_actually_carries() {
        let key = SigningKey::generate(&mut OsRng);
        let (bundle, _signer, _provider) =
            mint_key_package_for_testing(&credential(), &WRAPPING_KEY, &SystemClock, &key)
                .expect("mint");

        let leaf = bundle.key_package().leaf_node();
        let attestation = KeyPackageAttestation::extract_attestation(leaf.extensions())
            .expect("parse attestation")
            .expect("attestation present");

        assert_eq!(
            attestation.leaf_signature_key,
            fixed_32(leaf.signature_key().as_slice(), "sig").expect("sig bytes"),
            "the attestation must bind the leaf's actual signature_key (§9.7.1 check 4)"
        );
        assert_eq!(
            attestation.leaf_encryption_key,
            leaf_encryption_key_bytes(leaf).expect("enc bytes"),
            "the attestation must bind the leaf's actual encryption_key (§9.7.1 check 5)"
        );
        assert_eq!(
            attestation.init_key,
            fixed_32(bundle.key_package().hpke_init_key().as_slice(), "init").expect("init bytes"),
            "the attestation must bind the KeyPackage's actual init_key (§9.7.1 check 7)"
        );
        assert_eq!(
            attestation.wrapping_key, WRAPPING_KEY,
            "the attestation must bind the leaf's 0xFF01 wrapping key (§9.7.1 check 6)"
        );
        assert_ne!(
            attestation.init_key, attestation.leaf_encryption_key,
            "RFC 9420 §10.1 requires init_key and encryption_key to differ"
        );
    }

    #[test]
    fn attestation_window_equals_the_leaf_lifetime() {
        let key = SigningKey::generate(&mut OsRng);
        let (bundle, _signer, _provider) =
            mint_key_package_for_testing(&credential(), &WRAPPING_KEY, &SystemClock, &key)
                .expect("mint");

        let lifetime = *bundle.key_package().life_time();
        let attestation = KeyPackageAttestation::extract_attestation(
            bundle.key_package().leaf_node().extensions(),
        )
        .expect("parse attestation")
        .expect("attestation present");

        assert_eq!(
            attestation.issued_at,
            lifetime.not_before(),
            "§9.7.1 check 11 pins issued_at to Lifetime.not_before"
        );
        assert_eq!(
            attestation.expires_at,
            lifetime.not_after(),
            "§9.7.1 check 11 pins expires_at to Lifetime.not_after"
        );
    }

    #[test]
    fn signature_verifies_against_the_signing_key() {
        let key = SigningKey::generate(&mut OsRng);
        let prepared =
            prepare_key_package(&credential(), &WRAPPING_KEY, &SystemClock).expect("prepare");
        let hash = prepared.attestation_signing_hash();
        let signature = key.sign(&hash).to_bytes();
        let (bundle, _signer, _provider) = finish_key_package(prepared, signature).expect("finish");

        let attestation = KeyPackageAttestation::extract_attestation(
            bundle.key_package().leaf_node().extensions(),
        )
        .expect("parse attestation")
        .expect("attestation present");

        key.verifying_key()
            .verify_strict(
                &attestation.signing_hash(),
                &ed25519_dalek::Signature::from_bytes(&attestation.signature),
            )
            .expect("the minted attestation must verify against the signing key");
    }

    #[test]
    fn replay_reproduces_the_probe_keys() {
        // Two finishes of two separate prepares must not collide, and each
        // finish must reproduce its own prepare's keys — the binding check
        // inside `finish_key_package` is what proves the second half.
        let key = SigningKey::generate(&mut OsRng);
        let first = mint_key_package_for_testing(&credential(), &WRAPPING_KEY, &SystemClock, &key)
            .expect("first mint");
        let second = mint_key_package_for_testing(&credential(), &WRAPPING_KEY, &SystemClock, &key)
            .expect("second mint");

        assert_ne!(
            first.0.key_package().hpke_init_key().as_slice(),
            second.0.key_package().hpke_init_key().as_slice(),
            "each mint must draw a fresh init_key"
        );
    }

    #[test]
    fn minted_attestation_passes_the_pure_verifier() {
        use crate::keypackage_attestation::AttestationLeafGroundTruth;
        use scp_did::DidDocument;

        let key = SigningKey::generate(&mut OsRng);
        let credential = credential();
        let (bundle, _signer, _provider) =
            mint_key_package_for_testing(&credential, &WRAPPING_KEY, &SystemClock, &key)
                .expect("mint");

        let leaf = bundle.key_package().leaf_node();
        let attestation = KeyPackageAttestation::extract_attestation(leaf.extensions())
            .expect("parse attestation")
            .expect("attestation present");

        let leaf_signature_key = fixed_32(leaf.signature_key().as_slice(), "sig").expect("sig");
        let leaf_encryption_key = leaf_encryption_key_bytes(leaf).expect("enc");
        let kp_init_key =
            fixed_32(bundle.key_package().hpke_init_key().as_slice(), "init").expect("init");
        let lifetime = *bundle.key_package().life_time();

        let ground_truth = AttestationLeafGroundTruth {
            credential: &credential,
            leaf_signature_key: &leaf_signature_key,
            leaf_encryption_key: &leaf_encryption_key,
            leaf_wrapping_key: &WRAPPING_KEY,
            leaf_lifetime_not_before: lifetime.not_before(),
            leaf_lifetime_not_after: lifetime.not_after(),
            trigger: crate::keypackage_attestation::AttestationTrigger::Add {
                kp_init_key: &kp_init_key,
            },
        };

        let document = DidDocument::new(
            &credential.did,
            &[0x42u8; 32],
            &key.verifying_key().to_bytes(),
            &[0u8; 32],
        );

        let now = SystemClock.now_secs();
        verify_attestation_with_resolution(&attestation, &ground_truth, &document, now, now)
            .expect("a freshly minted attestation must pass §9.7.1 checks 1–13");
    }
}
