#!/usr/bin/env python3.12
"""Fail where a transcluding site's bytes differ from the fragment its directive names.

The check copies `.docs/` into a temporary tree, re-runs the resolver there, and
compares. It fails on eight conditions. The first five are the five the
identity-substrate plan states for the `[mirror]` disposition:

1. a file differs after the expansion, so a site's bytes have drifted from its Owner;
2. a directive names a fragment id no file under `.docs/` defines;
3. two files define one fragment id;
4. a directive's two delimiters do not pair;
5. a site's include body carries a byte the fragment does not;
6. a one-line directive names a fragment whose body spans more than one line;
7. an Owner defines a fragment no include directive names;
8. the tree's include directives differ from the checked-in lock file.

Condition 5 is condition 1 read from the site's side, and the check reports it in
the site's own terms so a writer reads which line drifted rather than which file.
Condition 6 belongs to the one-line marker form, which a Markdown table cell needs
because a cell holds no line break: flattening a multi-line fragment into a cell
would put bytes at the site that the Owner does not carry in that order.
Condition 7 takes the fragment as its subject where the first six take the
directive as theirs. A site that ought to carry a directive and carries prose
instead matches no directive, so the first six conditions read nothing at it; the
Owner's unconsumed fragment is the trace that site leaves, and the failure names
the fragment id, which names the site. A writer that means to stop mirroring a
unit deletes the Owner's marker.

Condition 8 is condition 7's converse, and it is the condition that makes a site
carry a directive. Seventeen of this corpus's fragments have two or more
consumers, so under conditions 1 through 7 alone any one of those consumers can
be replaced by hand-written prose with every condition green: the fragment keeps
a consumer, no site's bytes drift from a directive it no longer carries, no id is
undefined or duplicated, and no delimiter is unpaired. `.docs/doc-include-sites.lock`
carries one line per site — the file, the fragment id, and the count of directives
naming that id in that file — sorted, and this check compares the tree against it,
so removing a directive is a deliberate edit to a tracked file. It also makes the
cheap repair of condition 7 fail: deleting the Owner's marker leaves the site's
directive naming an undefined id, and deleting the directive too leaves the tree
short of a line the lock carries.

`--self-test` plants each of the eight conditions in a scratch tree and asserts that
the checker reports it, and pairs them with two conforming controls, one block and
one inline, so a green real scan means the checker read the tree rather than that
it can no longer fail.

Usage:
    python3.12 scripts/check-doc-includes.py
    python3.12 scripts/check-doc-includes.py --self-test
    python3.12 scripts/check-doc-includes.py --write-lock
"""

from __future__ import annotations

import argparse
import difflib
import shutil
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from doc_includes import collect, expand  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_ROOT = REPO_ROOT / ".docs"
LOCK_NAME = "doc-include-sites.lock"
LOCK_HEADER = (
    "# Every include-directive site under .docs/, one line per file and fragment id.\n"
    "# Format: <path relative to .docs/>\\t<fragment id>\\t<directives naming that id in that file>\n"
    "# Generated by scripts/check-doc-includes.py --write-lock. Editing a line is how a\n"
    "# writer removes or adds a transcluding site; the check fails where the tree and\n"
    "# this file disagree.\n"
)


def site_lines(root: Path, includes: list) -> list[str]:
    """One sorted line per file and fragment id, with the directive count."""
    counts: dict[tuple[str, str], int] = {}
    for include in includes:
        key = (include.path.relative_to(root).as_posix(), include.fragment_id)
        counts[key] = counts.get(key, 0) + 1
    return [f"{path}\t{fragment_id}\t{count}" for (path, fragment_id), count in sorted(counts.items())]


def read_lock(root: Path) -> list[str] | None:
    """The lock file's site lines, or None where the tree carries no lock file."""
    lock = root / LOCK_NAME
    if not lock.is_file():
        return None
    return [
        line
        for line in lock.read_text(encoding="utf-8").split("\n")
        if line.strip() and not line.startswith("#")
    ]


def run_scan(root: Path) -> list[str]:
    """Return every failure the eight conditions produce over the tree at `root`."""
    fragments, includes, failures = collect(root)
    failures = list(failures)

    locked = read_lock(root)
    if locked is None:
        failures.append(
            f"{root / LOCK_NAME}: the lock file is absent, so no site is held to carrying "
            f"a directive; run `--write-lock` to generate it"
        )
    else:
        present = site_lines(root, includes)
        for line in sorted(set(locked) - set(present)):
            failures.append(
                f"{root / LOCK_NAME}: the lock carries `{line}` and the tree does not, so a "
                f"transcluding site lost its directive"
            )
        for line in sorted(set(present) - set(locked)):
            failures.append(
                f"{root / LOCK_NAME}: the tree carries `{line}` and the lock does not, so a "
                f"transcluding site was added without recording it"
            )

    named = {include.fragment_id for include in includes}
    for fragment_id, fragment in fragments.items():
        if fragment_id in named:
            continue
        failures.append(
            f"{fragment.path}:{fragment.open_line}: the Owner defines fragment "
            f"`{fragment_id}` and no include directive names it"
        )

    for include in includes:
        path = include.path
        original = path.read_text(encoding="utf-8")
        resolved, expand_errors = expand(original, fragments, path)
        failures.extend(expand_errors)
        if resolved == original:
            continue
        fragment = fragments.get(include.fragment_id)
        if fragment is None:
            continue
        if include.body != fragment.body:
            diff = "\n".join(
                difflib.unified_diff(
                    fragment.body.split("\n"),
                    include.body.split("\n"),
                    fromfile=f"{fragment.path}:{fragment.open_line} (the Owner's fragment)",
                    tofile=f"{path}:{include.open_line} (the include body)",
                    lineterm="",
                )
            )
            failures.append(
                f"{path}:{include.open_line}: the include body for `{include.fragment_id}` "
                f"differs from the fragment {fragment.path}:{fragment.open_line} defines\n{diff}"
            )

    # Deduplicate while keeping the order the scan found them in.
    seen: set[str] = set()
    ordered: list[str] = []
    for failure in failures:
        if failure in seen:
            continue
        seen.add(failure)
        ordered.append(failure)
    return ordered


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _plant(root: Path, files: dict[str, str], lock: str | None = None) -> None:
    """Write a scratch tree, giving it a lock file that matches unless one is supplied."""
    for relative, text in files.items():
        _write(root / relative, text)
    if lock is None:
        _, includes, _ = collect(root)
        lock = LOCK_HEADER + "".join(f"{line}\n" for line in site_lines(root, includes))
    _write(root / LOCK_NAME, lock)


def self_test() -> int:
    """Plant each of the eight conditions and assert the checker reports it."""
    cases: list[tuple[str, dict[str, str], str]] = [
        (
            "a site's bytes drifted from its Owner",
            {
                "owner.md": (
                    "# Owner\n\n"
                    '<!-- scp:fragment id="probe-one" -->\n'
                    "The relay counts every PUBLISH and every `RENT`.\n"
                    '<!-- scp:end id="probe-one" -->\n'
                ),
                "site.md": (
                    "# Site\n\n"
                    '<!-- scp:include id="probe-one" from="owner.md" -->\n'
                    "The relay counts every PUBLISH.\n"
                    '<!-- scp:end id="probe-one" -->\n'
                ),
            },
            "differs from the fragment",
        ),
        (
            "a directive names a fragment id no file defines",
            {
                "site.md": (
                    '<!-- scp:include id="probe-absent" from="owner.md" -->\n'
                    "Some bytes.\n"
                    '<!-- scp:end id="probe-absent" -->\n'
                ),
            },
            "which no file under `.docs/` defines",
        ),
        (
            "two files define one fragment id",
            {
                "owner-a.md": '<!-- scp:fragment id="probe-two" -->\nA.\n<!-- scp:end id="probe-two" -->\n',
                "owner-b.md": '<!-- scp:fragment id="probe-two" -->\nB.\n<!-- scp:end id="probe-two" -->\n',
            },
            "is defined twice",
        ),
        (
            "a directive's two delimiters do not pair",
            {
                "owner.md": '<!-- scp:fragment id="probe-three" -->\nA.\n<!-- scp:end id="probe-three" -->\n',
                "site.md": '<!-- scp:include id="probe-three" from="owner.md" -->\nA.\n',
            },
            "and no `scp:end` closes it",
        ),
        (
            "a site's include body carries a byte the fragment does not",
            {
                "owner.md": (
                    '<!-- scp:fragment id="probe-four" -->\n'
                    "A relay charges no `scp:wit:` write.\n"
                    '<!-- scp:end id="probe-four" -->\n'
                ),
                "site.md": (
                    '<!-- scp:include id="probe-four" from="owner.md" -->\n'
                    "A relay charges no `scp:wit:` write, and the operator decides.\n"
                    '<!-- scp:end id="probe-four" -->\n'
                ),
            },
            "differs from the fragment",
        ),
        (
            "a table cell's inline include drifted from its Owner",
            {
                "owner.md": (
                    "| term | default |\n|---|---|\n"
                    '| `rate_limit_publish` | <!-- scp:fragment id="probe-five" -->'
                    "6,000 per minute<!-- scp:end id=\"probe-five\" --> |\n"
                ),
                "site.md": (
                    "| term | default |\n|---|---|\n"
                    '| `rate_limit_publish` | <!-- scp:include id="probe-five" from="owner.md" -->'
                    "6,000 a minute<!-- scp:end id=\"probe-five\" --> |\n"
                ),
            },
            "differs from the fragment",
        ),
        (
            "an Owner defines a fragment no include directive names",
            {
                "owner.md": (
                    '<!-- scp:fragment id="probe-seven" -->\n'
                    "A relay counts every PUBLISH.\n"
                    '<!-- scp:end id="probe-seven" -->\n'
                ),
            },
            "no include directive names it",
        ),
        (
            "an inline include names a fragment that spans more than one line",
            {
                "owner.md": (
                    '<!-- scp:fragment id="probe-six" -->\nline a\nline b\n<!-- scp:end id="probe-six" -->\n'
                ),
                "site.md": (
                    '| cell | <!-- scp:include id="probe-six" from="owner.md" -->'
                    "line a<!-- scp:end id=\"probe-six\" --> |\n"
                ),
            },
            "spans more than one line",
        ),
    ]

    # Condition 8 takes the lock as its subject, so its two cases plant a lock that
    # disagrees with the tree rather than a marker that disagrees with a fragment.
    lock_cases: list[tuple[str, dict[str, str], str, str]] = [
        (
            "a directive named by the lock left the tree",
            {
                "owner.md": '<!-- scp:fragment id="probe-eight" -->\nA.\n<!-- scp:end id="probe-eight" -->\n',
                "site-a.md": '<!-- scp:include id="probe-eight" from="owner.md" -->\nA.\n<!-- scp:end id="probe-eight" -->\n',
            },
            LOCK_HEADER + "site-a.md\tprobe-eight\t1\nsite-b.md\tprobe-eight\t1\n",
            "the tree does not, so a transcluding site lost its directive",
        ),
        (
            "a directive the lock does not carry entered the tree",
            {
                "owner.md": '<!-- scp:fragment id="probe-nine" -->\nA.\n<!-- scp:end id="probe-nine" -->\n',
                "site-a.md": '<!-- scp:include id="probe-nine" from="owner.md" -->\nA.\n<!-- scp:end id="probe-nine" -->\n',
            },
            LOCK_HEADER,
            "the lock does not, so a transcluding site was added without recording it",
        ),
    ]

    failed = False
    for name, files, expected in cases:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw) / ".docs"
            _plant(root, files)
            failures = run_scan(root)
            if not any(expected in failure for failure in failures):
                print(f"SELF-TEST FAILED: {name}: no failure carried {expected!r}", file=sys.stderr)
                for failure in failures:
                    print(f"  reported: {failure}", file=sys.stderr)
                failed = True
            else:
                print(f"self-test ok: {name}")

    for name, files, lock, expected in lock_cases:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw) / ".docs"
            _plant(root, files, lock=lock)
            failures = run_scan(root)
            if not any(expected in failure for failure in failures):
                print(f"SELF-TEST FAILED: {name}: no failure carried {expected!r}", file=sys.stderr)
                for failure in failures:
                    print(f"  reported: {failure}", file=sys.stderr)
                failed = True
            else:
                print(f"self-test ok: {name}")

    clean_cases: list[tuple[str, dict[str, str]]] = [
        (
            "a conforming block pair reports nothing",
            {
                "owner.md": '<!-- scp:fragment id="probe-clean" -->\nA.\n<!-- scp:end id="probe-clean" -->\n',
                "site.md": '<!-- scp:include id="probe-clean" from="owner.md" -->\nA.\n<!-- scp:end id="probe-clean" -->\n',
            },
        ),
        (
            "a conforming inline pair in a table row reports nothing",
            {
                "owner.md": '| t | <!-- scp:fragment id="probe-inline-clean" -->A.<!-- scp:end id="probe-inline-clean" --> |\n',
                "site.md": '| t | <!-- scp:include id="probe-inline-clean" from="owner.md" -->A.<!-- scp:end id="probe-inline-clean" --> |\n',
            },
        ),
    ]

    for name, files in clean_cases:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw) / ".docs"
            _plant(root, files)
            failures = run_scan(root)
            if failures:
                print(f"SELF-TEST FAILED: {name}", file=sys.stderr)
                for failure in failures:
                    print(f"  reported: {failure}", file=sys.stderr)
                failed = True
            else:
                print(f"self-test ok: {name}")

    return 1 if failed else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--self-test", action="store_true", help="plant each condition and assert it is caught")
    parser.add_argument("--write-lock", action="store_true", help="regenerate the include-site lock file")
    parser.add_argument("--root", default=str(DOCS_ROOT), help="directory to scan")
    args = parser.parse_args()

    if args.self_test:
        return self_test()

    if args.write_lock:
        source = Path(args.root)
        _, includes, _ = collect(source)
        lines = site_lines(source, includes)
        (source / LOCK_NAME).write_text(
            LOCK_HEADER + "".join(f"{line}\n" for line in lines), encoding="utf-8"
        )
        print(f"wrote {source / LOCK_NAME}: {len(lines)} site lines")
        return 0

    source = Path(args.root)
    with tempfile.TemporaryDirectory() as raw:
        mirror = Path(raw) / source.name
        shutil.copytree(source, mirror)
        failures = run_scan(mirror)
        # The scan reads the copy, so every path it names sits under the temporary
        # tree, which no reader of a CI log can open. Rewrite each one to the file the
        # writer edits before the failure leaves this function.
        failures = [failure.replace(str(mirror), str(source)) for failure in failures]

    if failures:
        for failure in failures:
            print(f"FAIL: {failure}", file=sys.stderr)
        print(f"\n{len(failures)} transclusion failures", file=sys.stderr)
        return 1

    fragments, includes, _ = collect(source)
    print(f"fragments defined: {len(fragments)}")
    print(f"include directives: {len(includes)}")
    print(f"include-site lock lines: {len(site_lines(source, includes))}")
    print("every include body equals the fragment its directive names, and the tree matches the lock")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
