//! Key custody migration protocol types (spec §3.2).
//!
//! "The identity layer abstracts custody. The user authenticates however they
//! choose; under the hood it resolves to a protocol-level DID. Migration
//! between custody methods is possible without changing identity." — §3.2
//!
//! This module defines the wire types for custody migration requests and
//! the protocol's migration lifecycle. Migration changes the custody backend
//! (e.g., from software key storage to hardware-backed Secure Enclave) without
//! altering the user's DID. The active signing key (`#active`) is rotated to
//! a new key generated by the target custody provider; the identity key (`#0`)
//! and DID remain stable.
//!
//! # Migration Steps
//!
//! 1. **Request** — The user initiates a migration, specifying the target
//!    custody type. A new active signing key is generated by the target
//!    custody provider.
//! 2. **Authorize** — The current active key signs the
//!    [`CustodyMigrationRequest`] to prove consent and continuity.
//! 3. **Rotate** — The DID document is updated to replace the `#active`
//!    verification method with the new public key. This update is signed by
//!    the identity key (`#0`) per ADR-003 §4a.
//! 4. **Reissue** — Existing UCAN tokens signed by the old active key are
//!    revoked and reissued under the new active key (spec §9.12).
//! 5. **Destroy** — The old active key material is destroyed in the previous
//!    custody provider.
//!
//! See spec §3.2 (Key Custody) and §9.12 (Key Rotation).

use serde::{Deserialize, Serialize};

// Re-use CustodyType from scp-platform to avoid duplication.
// CustodyType is already defined in scp_platform::traits but scp-core doesn't
// depend on scp-platform. We define the migration-level custody type enum here
// to keep scp-core self-contained.

// ---------------------------------------------------------------------------
// CustodyMigrationTarget
// ---------------------------------------------------------------------------

/// The target custody type for a migration (spec §3.2).
///
/// This mirrors the custody model described in the spec:
/// - Platform-managed (Apple/Google) — delegated to OS keychain/keystore
/// - Hardware security keys — dedicated hardware (YubiKey, etc.)
/// - Self-managed keys — user controls raw key material
/// - Software — encrypted file on disk (e.g., SQLCipher)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CustodyMigrationTarget {
    /// Platform-managed custody (Apple Keychain, Google Keystore).
    PlatformManaged,
    /// Hardware security module (Secure Enclave, HSM, YubiKey).
    Hardware,
    /// Software-based custody (encrypted key file on disk).
    Software,
    /// In-memory custody (testing only).
    InMemory,
}

// ---------------------------------------------------------------------------
// CustodyMigrationRequest
// ---------------------------------------------------------------------------

/// A request to migrate key custody from one provider to another (spec §3.2).
///
/// The request captures the new active public key generated by the target
/// custody provider, the target custody type, and the request timestamp.
/// The request must be signed by the current active key to prove consent.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CustodyMigrationRequest {
    /// Ed25519 public key bytes (32 bytes) generated by the target custody
    /// provider. This will become the new `#active` verification method.
    #[serde(with = "serde_bytes")]
    pub new_active_pubkey: Vec<u8>,
    /// The custody type being migrated to.
    pub target_custody_type: CustodyMigrationTarget,
    /// Unix timestamp (seconds) when the migration was requested.
    pub requested_at: u64,
}

// ---------------------------------------------------------------------------
// CustodyMigrationStep
// ---------------------------------------------------------------------------

/// The current step in the custody migration protocol.
///
/// Migration is a 5-step process. Each step must complete before the next
/// can begin. If any step fails, the migration is rolled back to the
/// previous custody state.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CustodyMigrationStep {
    /// Step 1: Migration requested, new key generated by target provider.
    Requested,
    /// Step 2: Current active key has signed the migration request.
    Authorized,
    /// Step 3: DID document updated with new `#active` verification method.
    Rotated,
    /// Step 4: UCAN tokens reissued under the new active key.
    Reissued,
    /// Step 5: Old key material destroyed in previous custody provider.
    Completed,
}

// ---------------------------------------------------------------------------
// CustodyMigrationStatus
// ---------------------------------------------------------------------------

/// Status of an in-progress or completed custody migration.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CustodyMigrationStatus {
    /// The migration request that initiated this migration.
    pub request: CustodyMigrationRequest,
    /// The current step in the migration protocol.
    pub current_step: CustodyMigrationStep,
    /// Unix timestamp (seconds) when the current step was reached.
    pub step_reached_at: u64,
    /// If the migration failed, a description of the failure.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn custody_migration_request_construction() {
        let req = CustodyMigrationRequest {
            new_active_pubkey: vec![0xAA; 32],
            target_custody_type: CustodyMigrationTarget::Hardware,
            requested_at: 1_700_000_000,
        };

        assert_eq!(req.new_active_pubkey.len(), 32);
        assert_eq!(req.target_custody_type, CustodyMigrationTarget::Hardware);
        assert_eq!(req.requested_at, 1_700_000_000);
    }

    #[test]
    fn custody_migration_request_serialization_roundtrip() {
        let req = CustodyMigrationRequest {
            new_active_pubkey: vec![0xBB; 32],
            target_custody_type: CustodyMigrationTarget::PlatformManaged,
            requested_at: 1_700_100_000,
        };

        let json = serde_json::to_string(&req).unwrap();
        let deserialized: CustodyMigrationRequest = serde_json::from_str(&json).unwrap();
        assert_eq!(req, deserialized);
    }

    #[test]
    fn custody_migration_target_variants_are_distinct() {
        assert_ne!(
            CustodyMigrationTarget::PlatformManaged,
            CustodyMigrationTarget::Hardware
        );
        assert_ne!(
            CustodyMigrationTarget::Hardware,
            CustodyMigrationTarget::Software
        );
        assert_ne!(
            CustodyMigrationTarget::Software,
            CustodyMigrationTarget::InMemory
        );
        assert_eq!(
            CustodyMigrationTarget::Hardware,
            CustodyMigrationTarget::Hardware
        );
    }

    #[test]
    fn custody_migration_step_ordering() {
        // Steps are a state machine, not necessarily orderable, but each must be distinct.
        let steps = [
            CustodyMigrationStep::Requested,
            CustodyMigrationStep::Authorized,
            CustodyMigrationStep::Rotated,
            CustodyMigrationStep::Reissued,
            CustodyMigrationStep::Completed,
        ];
        for (i, a) in steps.iter().enumerate() {
            for (j, b) in steps.iter().enumerate() {
                if i == j {
                    assert_eq!(a, b);
                } else {
                    assert_ne!(a, b);
                }
            }
        }
    }

    #[test]
    fn custody_migration_status_construction_and_roundtrip() {
        let status = CustodyMigrationStatus {
            request: CustodyMigrationRequest {
                new_active_pubkey: vec![0xCC; 32],
                target_custody_type: CustodyMigrationTarget::Software,
                requested_at: 1_700_200_000,
            },
            current_step: CustodyMigrationStep::Rotated,
            step_reached_at: 1_700_200_100,
            failure_reason: None,
        };

        let json = serde_json::to_string(&status).unwrap();
        let deserialized: CustodyMigrationStatus = serde_json::from_str(&json).unwrap();
        assert_eq!(status, deserialized);
    }

    #[test]
    fn custody_migration_status_with_failure() {
        let status = CustodyMigrationStatus {
            request: CustodyMigrationRequest {
                new_active_pubkey: vec![0xDD; 32],
                target_custody_type: CustodyMigrationTarget::Hardware,
                requested_at: 1_700_300_000,
            },
            current_step: CustodyMigrationStep::Authorized,
            step_reached_at: 1_700_300_050,
            failure_reason: Some("DID document update rejected by relay".to_owned()),
        };

        let json = serde_json::to_string(&status).unwrap();
        assert!(json.contains("DID document update rejected"));
        let deserialized: CustodyMigrationStatus = serde_json::from_str(&json).unwrap();
        assert_eq!(status, deserialized);
    }

    #[test]
    fn custody_migration_target_serialization_roundtrip() {
        let targets = [
            CustodyMigrationTarget::PlatformManaged,
            CustodyMigrationTarget::Hardware,
            CustodyMigrationTarget::Software,
            CustodyMigrationTarget::InMemory,
        ];

        for target in &targets {
            let json = serde_json::to_string(target).unwrap();
            let deserialized: CustodyMigrationTarget = serde_json::from_str(&json).unwrap();
            assert_eq!(target, &deserialized);
        }
    }

    #[test]
    fn custody_migration_step_serialization_roundtrip() {
        let steps = [
            CustodyMigrationStep::Requested,
            CustodyMigrationStep::Authorized,
            CustodyMigrationStep::Rotated,
            CustodyMigrationStep::Reissued,
            CustodyMigrationStep::Completed,
        ];

        for step in &steps {
            let json = serde_json::to_string(step).unwrap();
            let deserialized: CustodyMigrationStep = serde_json::from_str(&json).unwrap();
            assert_eq!(step, &deserialized);
        }
    }
}
