"""E2E encrypted messaging tests through a real in-process relay.

These tests exercise the FULL protocol stack:
- Real did:dht identity creation (ADR-003)
- Real MLS group encryption (ADR-001)
- Real sender key signing (ADR-007)
- Real inner/outer envelope construction (ADR-002)
- Real WebSocket relay transport (ADR-004, ADR-005)

The relay is started in-process via ``py_relay_start_in_memory()``.
``configure_relay_transport(relay_url, local_did)`` initializes the
ContextManager with a ``RelayTransportProvider`` so ``py_context_send``
publishes encrypted payloads through the relay.
``transport_connect()`` establishes a second connection for relay-based
context discovery.

NOTE: The Python bridge's ``py_context_receive()`` uses a local channel
(``drain_and_deliver``) that delivers events generated by the local
ContextManager -- it does NOT subscribe to the relay.  Full relay-backed
receive is verified in the TypeScript E2E tests via ``contextSubscribe``.

Prerequisites:
    ``maturin develop --release --features allow_in_memory_custody``

Run:
    PYTHONPATH=bindings/python python3.12 -m pytest bindings/python/tests/test_e2e_relay.py -v
"""

from __future__ import annotations

import json

import pytest

# ---------------------------------------------------------------------------
# Skip entire module if the native extension is not available
# ---------------------------------------------------------------------------

try:
    from scp_sdk import _scp_core  # installed as scp_sdk._scp_core by maturin
except (ImportError, AttributeError):
    pytest.skip(
        "Native _scp_core extension not available -- run maturin develop first",
        allow_module_level=True,
    )

# ---------------------------------------------------------------------------
# Session-scoped relay fixture (started once, shut down after all tests)
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session", autouse=True)
def relay():
    """Start an in-memory relay for the entire test session.

    Initializes the ContextManager with a RelayTransportProvider so
    py_context_send publishes through the relay.  A second connection
    (transport_connect) is established for relay-based discovery.
    """
    handle = _scp_core.py_relay_start_in_memory()

    # Create a bootstrap identity for the MLS credential DID.
    bootstrap = _scp_core.py_identity_create("in_memory")

    # Wire the ContextManager to use a real relay transport provider.
    # Must be called BEFORE any py_context_create (OnceLock — first call wins).
    _scp_core.configure_relay_transport(handle.relay_url, bootstrap.did)

    # Second connection for relay-based context discovery.
    _scp_core.transport_connect(handle.relay_url)

    yield handle
    if not handle.is_shutdown:
        handle.shutdown()


# ---------------------------------------------------------------------------
# 1. Relay lifecycle
# ---------------------------------------------------------------------------


class TestRelayLifecycle:
    """Relay start, URL format, and port validation."""

    def test_relay_reports_valid_url(self, relay) -> None:
        assert relay.relay_url.startswith("ws://127.0.0.1:")
        assert relay.relay_url.endswith("/scp/v1")

    def test_relay_reports_valid_port(self, relay) -> None:
        assert 1 <= relay.relay_port <= 65535

    def test_relay_is_not_shutdown(self, relay) -> None:
        assert not relay.is_shutdown


# ---------------------------------------------------------------------------
# Helper: create identity (sync bridge call)
# ---------------------------------------------------------------------------


def _create_identity() -> str:
    """Create an in-memory identity and return the DID string."""
    handle = _scp_core.py_identity_create("in_memory")
    return handle.did


# ---------------------------------------------------------------------------
# 2. Two-party encrypted send through real relay
# ---------------------------------------------------------------------------


class TestTwoPartyEncryptedMessaging:
    """Alice and Bob exchange messages through real MLS + relay."""

    def test_alice_creates_context_bob_joins_alice_sends(self) -> None:
        alice_did = _create_identity()
        bob_did = _create_identity()

        assert alice_did.startswith("did:dht:")
        assert bob_did.startswith("did:dht:")
        assert alice_did != bob_did

        # Alice creates an encrypted context
        handle = _scp_core.py_context_create(
            alice_did,
            {
                "ceiling": ["messages:read", "messages:write", "member:invite", "role:assign"],
                "memory_scope": "ephemeral",
                "governance": "single_admin",
            },
        )
        assert handle.context_id
        assert handle.state == "active"

        # Bob joins
        _scp_core.py_context_join(handle, bob_did)
        assert _scp_core.py_context_member_count(handle) == 2
        assert _scp_core.py_context_is_member(handle, bob_did)
        assert _scp_core.py_context_is_member(handle, alice_did)

        members = _scp_core.py_context_member_dids(handle)
        assert alice_did in members
        assert bob_did in members

        # Alice sends -- exercises the full pipeline:
        # inner envelope creation (Ed25519 signing) -> MLS encryption ->
        # sender key encryption -> outer envelope -> relay publish.
        _scp_core.py_context_send(handle, alice_did, b"hello from Alice to Bob")

    def test_bob_sends_reply(self) -> None:
        alice_did = _create_identity()
        bob_did = _create_identity()

        handle = _scp_core.py_context_create(
            alice_did,
            {
                "ceiling": ["messages:read", "messages:write", "member:invite", "role:assign"],
                "memory_scope": "ephemeral",
                "governance": "single_admin",
            },
        )

        _scp_core.py_context_join(handle, bob_did)

        # Alice sends
        _scp_core.py_context_send(handle, alice_did, b"message from Alice")

        # Bob replies
        _scp_core.py_context_send(handle, bob_did, b"reply from Bob")


# ---------------------------------------------------------------------------
# 3. Three-party encrypted messaging
# ---------------------------------------------------------------------------


class TestThreePartyEncryptedMessaging:
    """Alice, Bob, and Carol all exchange messages in one context."""

    def test_three_party_send(self) -> None:
        alice_did = _create_identity()
        bob_did = _create_identity()
        carol_did = _create_identity()

        handle = _scp_core.py_context_create(
            alice_did,
            {
                "ceiling": ["messages:read", "messages:write", "member:invite", "role:assign"],
                "memory_scope": "ephemeral",
                "governance": "single_admin",
            },
        )

        _scp_core.py_context_join(handle, bob_did)
        _scp_core.py_context_join(handle, carol_did)

        assert _scp_core.py_context_member_count(handle) == 3

        # Each participant sends
        for did, name in [(alice_did, "Alice"), (bob_did, "Bob"), (carol_did, "Carol")]:
            _scp_core.py_context_send(handle, did, f"{name} says hello".encode())


# ---------------------------------------------------------------------------
# 4. Multiple sequential messages
# ---------------------------------------------------------------------------


class TestMultipleMessages:
    """Sequential message ordering and binary payload."""

    def test_five_messages_sequentially(self) -> None:
        alice_did = _create_identity()
        bob_did = _create_identity()

        handle = _scp_core.py_context_create(
            alice_did,
            {
                "ceiling": ["messages:read", "messages:write", "member:invite", "role:assign"],
                "memory_scope": "ephemeral",
                "governance": "single_admin",
            },
        )

        _scp_core.py_context_join(handle, bob_did)

        for i in range(5):
            _scp_core.py_context_send(handle, alice_did, f"message {i}".encode())

    def test_binary_payload(self) -> None:
        alice_did = _create_identity()

        handle = _scp_core.py_context_create(
            alice_did,
            {
                "ceiling": ["messages:read", "messages:write"],
                "memory_scope": "ephemeral",
                "governance": "single_admin",
            },
        )

        # Raw binary (not UTF-8 text)
        binary_payload = bytes([0x00, 0xFF, 0x42, 0xDE, 0xAD, 0xBE, 0xEF])
        _scp_core.py_context_send(handle, alice_did, binary_payload)


# ---------------------------------------------------------------------------
# 5. Governance after join
# ---------------------------------------------------------------------------


def _make_proposal_json(
    context_id: str,
    proposer_did: str,
    action: dict,
) -> str:
    """Construct a GovernanceProposal JSON for py_governance_execute."""
    import os
    import time

    proposal_id = list(os.urandom(32))
    now = int(time.time())
    return json.dumps(
        {
            "proposal_id": proposal_id,
            "context_id": context_id,
            "proposer_did": proposer_did,
            "action": action,
            "status": "Approved",
            "created_at": now,
            "voting_deadline": now + 3600,
            "approvals": [],
            "rejections": [],
            "created_at_epoch": None,
        }
    )


class TestGovernanceWithRelay:
    """Governance actions on relay-connected contexts.

    NOTE: These tests exercise the governance execution path with pre-approved
    proposals (``"status": "Approved"``). The ``single_admin`` governance engine
    auto-approves proposals from the admin, so these tests verify the happy-path
    execution dispatch -- not the vote validation or quorum logic. The negative
    test ``test_pending_proposal_is_rejected`` below verifies the status gate.
    """

    def test_change_role_after_join(self) -> None:
        alice_did = _create_identity()
        bob_did = _create_identity()

        handle = _scp_core.py_context_create(
            alice_did,
            {
                "ceiling": [
                    "messages:read",
                    "messages:write",
                    "member:invite",
                    "role:assign",
                    "member:remove",
                ],
                "memory_scope": "ephemeral",
                "governance": "single_admin",
            },
        )

        _scp_core.py_context_join(handle, bob_did)

        # Verify Bob is a member
        initial_role = _scp_core.py_context_member_role(handle, bob_did)
        assert initial_role is not None

        # Change Bob's role via governance proposal
        proposal_json = _make_proposal_json(
            handle.context_id,
            alice_did,
            {"ChangeRole": {"did": bob_did, "new_role": "moderator"}},
        )
        result = _scp_core.py_governance_execute(handle, proposal_json)
        assert result is not None

        # Verify role changed to moderator
        new_role = _scp_core.py_context_member_role(handle, bob_did)
        assert new_role is not None
        assert "moderator" in str(new_role).lower()

    def test_remove_member(self) -> None:
        alice_did = _create_identity()
        bob_did = _create_identity()

        handle = _scp_core.py_context_create(
            alice_did,
            {
                "ceiling": [
                    "messages:read",
                    "messages:write",
                    "member:invite",
                    "member:remove",
                    "role:assign",
                ],
                "memory_scope": "ephemeral",
                "governance": "single_admin",
            },
        )

        _scp_core.py_context_join(handle, bob_did)
        assert _scp_core.py_context_is_member(handle, bob_did)

        proposal_json = _make_proposal_json(
            handle.context_id,
            alice_did,
            {"Eject": {"did": bob_did, "reason": None}},
        )
        _scp_core.py_governance_execute(handle, proposal_json)

        assert not _scp_core.py_context_is_member(handle, bob_did)

    def test_pending_proposal_is_rejected(self) -> None:
        """Governance engine must reject proposals that are not Approved.

        This is the negative counterpart to the happy-path tests above: a
        proposal with ``"status": "Pending"`` must be refused, proving that
        the governance engine checks proposal status and does not blindly
        execute any submitted action.
        """
        alice_did = _create_identity()
        bob_did = _create_identity()

        handle = _scp_core.py_context_create(
            alice_did,
            {
                "ceiling": [
                    "messages:read",
                    "messages:write",
                    "member:invite",
                    "role:assign",
                ],
                "memory_scope": "ephemeral",
                "governance": "single_admin",
            },
        )

        _scp_core.py_context_join(handle, bob_did)

        # Construct a proposal with Pending status -- must be rejected.
        import os
        import time

        proposal_id = list(os.urandom(32))
        now = int(time.time())
        pending_proposal = json.dumps(
            {
                "proposal_id": proposal_id,
                "context_id": handle.context_id,
                "proposer_did": alice_did,
                "action": {"ChangeRole": {"did": bob_did, "new_role": "moderator"}},
                "status": "Pending",
                "created_at": now,
                "voting_deadline": now + 3600,
                "approvals": [],
                "rejections": [],
                "created_at_epoch": None,
            }
        )

        with pytest.raises(RuntimeError, match="not approved"):
            _scp_core.py_governance_execute(handle, pending_proposal)

        # Bob's role should be unchanged -- the action was not executed.
        initial_role = _scp_core.py_context_member_role(handle, bob_did)
        assert initial_role is not None


# ---------------------------------------------------------------------------
# 6. Context lifecycle with relay
# ---------------------------------------------------------------------------


class TestContextLifecycleWithRelay:
    """Full create -> join -> send -> leave -> close cycle."""

    def test_full_lifecycle(self) -> None:
        alice_did = _create_identity()
        bob_did = _create_identity()

        handle = _scp_core.py_context_create(
            alice_did,
            {
                "ceiling": [
                    "messages:read",
                    "messages:write",
                    "member:invite",
                    "role:assign",
                    "context:close",
                ],
                "memory_scope": "ephemeral",
                "governance": "single_admin",
            },
        )

        # Join
        _scp_core.py_context_join(handle, bob_did)
        assert _scp_core.py_context_member_count(handle) == 2

        # Send
        _scp_core.py_context_send(handle, alice_did, b"lifecycle test message")

        # Bob leaves
        _scp_core.py_context_leave(handle, bob_did)
        assert _scp_core.py_context_member_count(handle) == 1

        # Alice closes
        _scp_core.py_context_close(handle, alice_did)

    def test_send_on_closed_context_fails(self) -> None:
        alice_did = _create_identity()

        handle = _scp_core.py_context_create(
            alice_did,
            {
                "ceiling": ["messages:read", "messages:write", "context:close"],
                "memory_scope": "ephemeral",
                "governance": "single_admin",
            },
        )

        _scp_core.py_context_close(handle, alice_did)

        # Send on closed context must fail
        with pytest.raises(Exception):
            _scp_core.py_context_send(handle, alice_did, b"should fail")


# ---------------------------------------------------------------------------
# 7. Event log with relay context
# ---------------------------------------------------------------------------


class TestEventLogWithRelay:
    """Event log records on relay-connected contexts."""

    def test_event_log_records_creation(self) -> None:
        alice_did = _create_identity()

        handle = _scp_core.py_context_create(
            alice_did,
            {
                "ceiling": ["messages:read"],
                "memory_scope": "ephemeral",
                "governance": "single_admin",
            },
        )

        events = _scp_core.event_log_query(handle.context_id)
        assert isinstance(events, list)
